CREATE OR REPLACE VIEW CDVINFORM_USOVEH_SINTARJ AS
  SELECT 
    CDINCIDENTES.NUMREQ,
    CDINCIDENTES.NUMREQ AS CG_CONTRATO,
    CDEMPRE_REQ.CIF,
    DFEMP.NOMB,
    CDINCIDENTES.MATRICULA,
    CDVEHICULO_CONT.DSCR,
    CDINCIDENTES.FECINI,
    CDINCIDENTES.FECFIN,
    CDINCIDENTES.PROCEDENCIA,
    CDINCIDENTES.PAIS,
    PAIS.DSCR                    AS DSCRPAIS,
    ((CDINCIDENTES.FECFIN-CDINCIDENTES.FECINI)*60*24)    AS MINUTOS
  FROM CDINCIDENTES, PAIS, CDTIPO_FALLO, CDEMPRE_REQ, DFEMP, CDVEHICULO_CONT, CDTIPO_PROPOSITO
  WHERE  PAIS.COD_PAIS=CDINCIDENTES.PAIS AND
  CDTIPO_FALLO.TPFALLO=CDINCIDENTES.TIPO AND 
 CDEMPRE_REQ.NUMREQ=CDINCIDENTES.NUMREQ AND CDEMPRE_REQ.CIF = DFEMP.CIF  
  AND CDVEHICULO_CONT.MATRICULA    = CDINCIDENTES.MATRICULA
  AND CDVEHICULO_CONT.CG_CONTRATO = CDINCIDENTES.NUMREQ
  AND CDTIPO_PROPOSITO.TPPROPOSITO=CDINCIDENTES.TPPROPOSITO
   AND CDINCIDENTES.TIPO = '4';