SELECT 
	DFEMP.EMAIL, 
	CDVORIGEN_FICHEROS.ORIGEN_DSCR, 
	DFEMP.LOCALE		
FROM 
	CDFICHEROS, 
	CDVORIGEN_FICHEROS, 
	DFEMP
WHERE 
	CDVORIGEN_FICHEROS.IDORIGEN = CDFICHEROS.IDORIGEN 
	AND CDVORIGEN_FICHEROS.CIF = DFEMP.CIF
	AND CDFICHEROS.IDFICHERO = ?