SELECT DISTINCT 
	CDUSU_DFEMP.CIF, 
	NVL(IDDELEGACION, -1) AS IDDELEGACION 
FROM 
	CDUSU_DEL, 
	CDUSU_DFEMP 
WHERE 
	CDUSU_DFEMP.CIF =CDUSU_DEL.CIF(+) 
	AND  CDUSU_DFEMP.USUARIO =CDUSU_DEL.USUARIO(+) 
	AND  CDUSU_DFEMP.USUARIO =  ?