SELECT  DISTINCT 
	DATERANGE, 
	A.IDCONDUCTOR,
	A.NOMBRE,
	A.EXTERNAL_EMPLOYEE_ID,
	A.DNI,
	CONS_SEMANA.TOTAL as TOTAL_SEMANA,
	CONS_MES.TOTAL AS TOTAL_MES, 
	A.DTDIARIO * 60 * 24 AS DTDIARIO, 
	A.DCDIARIO * 60 * 24 AS DCDIARIO, 
	A.DDDIARIO * 60 * 24 AS DDDIARIO, 
	A.DPDIARIO * 60 * 24 AS DPDIARIO, 
	(CASE WHEN (( 1 - A.DTDIARIO - A.DPDIARIO - A.DDDIARIO - A.DCDIARIO) * 60 * 24 ) < 0 THEN 0 ELSE (( 1 - A.DTDIARIO - A.DPDIARIO - A.DDDIARIO - A.DCDIARIO) * 60 * 24 ) END) AS DPINDEF,
	(A.DTDIARIO + A.DCDIARIO + A.DDDIARIO ) * 60 * 24 AS TDIARIO, 
	TO_CHAR(DATERANGE,'Day') AS DIA_SEM,
	TO_CHAR(DATERANGE,'DD') AS DIA, 
	TO_CHAR(DATERANGE,'IW') AS SEMANA, 
	TO_CHAR(DATERANGE,'Month') AS MES2, 
	'MES' || TO_CHAR(DATERANGE,'MM') || '.' || TO_CHAR(DATERANGE,'Month') AS MES, 
	TO_CHAR(trunc(DATERANGE, 'iw'),'DD/MM/YYYY') AS INI_SEMANA, 
	TO_CHAR(trunc(DATERANGE, 'iw') + 6,'DD/MM/YYYY') AS FIN_SEMANA, 
	TO_CHAR(DATERANGE,'YYYY') AS ANHO 
FROM
	( 
		SELECT 
			TRUNC(COND.DATERANGE) AS DATERANGE, 
			COND.IDCONDUCTOR, 
			COND.NOMBRE, 
			COND.DNI, 
			COND.EXTERNAL_EMPLOYEE_ID,
			SUM(CASE WHEN TPACTIVIDAD IN (3) THEN FEC_FIN - FEC_COMIENZO ELSE 0 END)  AS DTDIARIO, 
			SUM(CASE WHEN TPACTIVIDAD IN (4) THEN FEC_FIN - FEC_COMIENZO ELSE 0 END)  AS DCDIARIO, 
			SUM(CASE WHEN TPACTIVIDAD IN (2) THEN FEC_FIN - FEC_COMIENZO ELSE 0 END)  AS DDDIARIO, 
			SUM(CASE WHEN TPACTIVIDAD IN (1) THEN FEC_FIN - FEC_COMIENZO ELSE 0 END)  AS DPDIARIO
		FROM 
			(
				SELECT 
					TRUNC(FEC_COMIENZO) AS T, 
					FEC_COMIENZO, 
					FEC_FIN, 
					TPACTIVIDAD, 
					IDCONDUCTOR
				FROM 
					CDACTIVIDADES 
				WHERE 
--					PROCEDENCIA = 'TC' AND 
					IDCONDUCTOR #SQLCOND# 
					AND  NUMREQ = ? 
					AND FEC_COMIENZO > ? 
					AND FEC_FIN      < TRUNC(?) + 1
			) ACTIVIDADES, 
			(
				SELECT 
					DATERANGE, 
					IDCONDUCTOR, 
					DNI, 
					NOMBRE, 
					EXTERNAL_EMPLOYEE_ID
				FROM
					(
						(
							SELECT 
								? + level AS DateRange 
							FROM    
								DUAL 
							WHERE   
								(? + level) <= ? 
							CONNECT BY 
								LEVEL <= ( TRUNC( ( CAST(? AS DATE)- CAST(? AS DATE) )*24))
						)
					),
					(
						SELECT 
							IDCONDUCTOR, 
							DNI,
							APELLIDOS||', '||NOMBRE AS NOMBRE ,
							EXTERNAL_EMPLOYEE_ID
						FROM 
							CDVCONDUCTOR_CONT 
						WHERE 
							IDCONDUCTOR #SQLCOND# 
							AND  CG_CONTRATO = ?  
					)  
			) COND 
		WHERE 
			T(+) = COND.DATERANGE 
			AND COND.IDCONDUCTOR =  ACTIVIDADES.IDCONDUCTOR(+) 
		GROUP BY 
			TRUNC(COND.DATERANGE), 
			COND.IDCONDUCTOR, 
			COND.NOMBRE, 
			COND.DNI,
			COND.EXTERNAL_EMPLOYEE_ID			
		ORDER BY  
			TRUNC(COND.DATERANGE), 
			COND.NOMBRE 
	) A, 
	( 
		SELECT 
			TO_CHAR(DATERANGE,'IW') AS SEMANA, 
			TO_CHAR(DATERANGE,'YYYY') AS ANHO,
			COND.IDCONDUCTOR, 
			COND.NOMBRE, 
			COND.DNI, 
			SUM(CASE WHEN TPACTIVIDAD IN (3,4,2,1) THEN FEC_FIN - FEC_COMIENZO ELSE 0 END)  AS TOTAL 
		FROM 
			(
				SELECT 
					TRUNC(FEC_COMIENZO) AS T, 
					FEC_COMIENZO, 
					FEC_FIN, 
					TPACTIVIDAD, 
					IDCONDUCTOR 
				FROM 
					CDACTIVIDADES 
				WHERE				
					--PROCEDENCIA = 'TC' AND 
					IDCONDUCTOR  #SQLCOND# 
					AND  NUMREQ = ? 
					AND FEC_COMIENZO > ? 
					AND FEC_FIN      < TRUNC(?) + 1
			) ACTIVIDADES, 
			(
				SELECT 
					DATERANGE, 
					IDCONDUCTOR, 
					DNI,
					NOMBRE 
				FROM
					(
						(
							SELECT 
								? + level AS DateRange 
							FROM    
								DUAL 
							WHERE   
								(? + level) <= ? 
							CONNECT BY LEVEL <= ( TRUNC((CAST(? AS DATE)- CAST(?  AS DATE))*24))
						)
					), 
					(
						SELECT 
							IDCONDUCTOR, 
							DNI, 
							APELLIDOS||', '||NOMBRE AS NOMBRE 
						FROM 
							CDVCONDUCTOR_CONT 
						WHERE 
							IDCONDUCTOR  #SQLCOND#  
							AND CG_CONTRATO = ?  
					)  
			) COND 
		WHERE 
			T(+) = COND.DATERANGE 
			AND COND.IDCONDUCTOR =  ACTIVIDADES.IDCONDUCTOR(+)
		GROUP BY  
			COND.IDCONDUCTOR, 
			TO_CHAR(DATERANGE,'YYYY'),
			TO_CHAR(DATERANGE,'IW'),
			COND.NOMBRE, 
			COND.DNI
		ORDER BY 
			COND.IDCONDUCTOR, 
			TO_CHAR(DATERANGE,'YYYY'),
			TO_CHAR(DATERANGE,'IW'), 
			COND.NOMBRE 
	) CONS_SEMANA,
	(
		SELECT 
			TO_CHAR(DATERANGE,'Month') AS MES, 
			TO_CHAR(DATERANGE,'YYYY') AS ANHO,
			cOND.IDCONDUCTOR, 
			COND.NOMBRE, 
			COND.DNI,
			SUM(CASE WHEN TPACTIVIDAD IN (3,4,2,1) THEN FEC_FIN - FEC_COMIENZO ELSE 0 END)  AS TOTAL 
		FROM 
			(
				SELECT 
					TRUNC(FEC_COMIENZO) AS T, 
					FEC_COMIENZO, 
					FEC_FIN, 
					TPACTIVIDAD, 
					IDCONDUCTOR 
				FROM 
					CDACTIVIDADES 
				WHERE					
					--PROCEDENCIA = 'TC' AND
					IDCONDUCTOR #SQLCOND# 
					AND  NUMREQ = ?  
					AND FEC_COMIENZO > ?
					AND FEC_FIN      < TRUNC(? ) + 1
			) ACTIVIDADES, 
			(
				SELECT 
					DATERANGE, 
					IDCONDUCTOR, 
					DNI,
					NOMBRE 
				FROM
					(
						(
							SELECT 
								?  + level AS DateRange 
							FROM    
								DUAL 
							WHERE   
								(?  + level) <= ?  
							CONNECT BY 
								LEVEL <= ( TRUNC((CAST(? AS DATE)- CAST(? AS DATE))*24))
						)
					),
					(
						SELECT 
							IDCONDUCTOR, 
							DNI, 
							APELLIDOS||', '||NOMBRE AS NOMBRE 
						FROM 
							CDVCONDUCTOR_CONT 
						WHERE 
							IDCONDUCTOR #SQLCOND# 
							AND  CG_CONTRATO = ?  
					)  
			) COND 
		WHERE 
			T(+) = COND.DATERANGE 
			AND COND.IDCONDUCTOR =  ACTIVIDADES.IDCONDUCTOR(+) 
		GROUP BY  
			COND.IDCONDUCTOR, 
			TO_CHAR(DATERANGE,'YYYY'), 
			TO_CHAR(DATERANGE,'Month'),
			COND.NOMBRE, 
			COND.DNI
		ORDER BY  
			COND.IDCONDUCTOR,
			TO_CHAR(DATERANGE,'YYYY'),
			TO_CHAR(DATERANGE,'IW'), 
			COND.NOMBRE 
	) CONS_MES
WHERE 
	TO_CHAR(A.DATERANGE,'IW') = CONS_SEMANA.SEMANA 
	AND TO_CHAR(A.DATERANGE,'YYYY') = CONS_SEMANA.ANHO 
	AND TO_CHAR(A.DATERANGE,'Month') = CONS_MES.MES 
	AND TO_CHAR(A.DATERANGE,'YYYY') = CONS_MES.ANHO 
	AND A.IDCONDUCTOR = CONS_MES.IDCONDUCTOR 
	AND A.IDCONDUCTOR = CONS_SEMANA.IDCONDUCTOR 
order by 
	A.IDCONDUCTOR, 
	A.DATERANGE, 
	TO_CHAR(A.DATERANGE,'YYYY')