/*SELECT 
	DNI,
	CONDUCCION,
	TRABAJO,
	DISPONIBILIDAD,
	DESCANSO,
	INDEFINIDA, 
	(CONDUCCION/TOTAL)*100 AS T_CONDUCCION,
	(TRABAJO/TOTAL)*100 AS T_TRABAJO,
	(DISPONIBILIDAD/TOTAL)*100 AS T_DISPONIBILIDAD,
	(DESCANSO/TOTAL)*100 AS T_DESCANSO,
	(INDEFINIDA/TOTAL)*100 AS T_INDEFINIDA 
FROM 
	(
		SELECT 
			DNI,
			CONDUCCION,
			TRABAJO,
			DISPONIBILIDAD,
			DESCANSO,
			INDEFINIDA, 
			CONDUCCION + TRABAJO + DISPONIBILIDAD + DESCANSO + INDEFINIDA AS TOTAL 
		FROM 
			(
				SELECT 
					DNI, 
					SUM(CONDUCCION) AS CONDUCCION, 
					SUM(TRABAJO) AS TRABAJO, 
					SUM(DISPONIBILIDAD) AS DISPONIBILIDAD, 
					SUM(DESCANSO) AS DESCANSO, 
					SUM(INDETERMINADO) AS INDEFINIDA, 
					0 AS KM, 
					SUM(CONDUCCION) AS TOTALES 
				FROM 
					( 
						SELECT 
							DNI, 
							DECODE(TPACTIVIDAD, 4, MINUTOS, 0) CONDUCCION, 
							DECODE(TPACTIVIDAD, 3, MINUTOS, 0) TRABAJO, 
							DECODE(TPACTIVIDAD, 2, MINUTOS, 0) DISPONIBILIDAD, 
							DECODE(TPACTIVIDAD, 1, MINUTOS, 0) DESCANSO, 
							DECODE(TPACTIVIDAD, 5, MINUTOS, 0) INDETERMINADO 
						FROM 
							( 
								SELECT 
									CDCONDUCTORES_EMP.DNI AS DNI, 
									A.TPACTIVIDAD AS TPACTIVIDAD, 
									SUM(A.MINUTOS) AS MINUTOS 
								FROM 
									CDACTIVIDADES_TEMPPRES A, 
									CDCONDUCTORES_EMP 
								WHERE 
									A.FEC_COMIENZO > ? 
									AND A.FEC_COMIENZO < ?  
									AND A.NUMREQ = ? 			 
									AND A.IDCONDUCTOR = CDCONDUCTORES_EMP.IDCONDUCTOR 									
									#SQLDELEG#	
								GROUP BY 
									CDCONDUCTORES_EMP.DNI, 
									A.TPACTIVIDAD 
							)
					) GROUP BY DNI
			)
	) */
	-- TODO: IDCONDUCTOR-DNI 
	
	SELECT 
	IDCONDUCTOR,
	CONDUCCION,
	TRABAJO,
	DISPONIBILIDAD,
	DESCANSO,
	INDEFINIDA, 
	(CONDUCCION/TOTAL)*100 AS T_CONDUCCION,
	(TRABAJO/TOTAL)*100 AS T_TRABAJO,
	(DISPONIBILIDAD/TOTAL)*100 AS T_DISPONIBILIDAD,
	(DESCANSO/TOTAL)*100 AS T_DESCANSO,
	(INDEFINIDA/TOTAL)*100 AS T_INDEFINIDA 
FROM 
	(
		SELECT 
			IDCONDUCTOR,
			CONDUCCION,
			TRABAJO,
			DISPONIBILIDAD,
			DESCANSO,
			INDEFINIDA, 
			CONDUCCION + TRABAJO + DISPONIBILIDAD + DESCANSO + INDEFINIDA AS TOTAL 
		FROM 
			(
				SELECT 
					IDCONDUCTOR, 
					SUM(CONDUCCION) AS CONDUCCION, 
					SUM(TRABAJO) AS TRABAJO, 
					SUM(DISPONIBILIDAD) AS DISPONIBILIDAD, 
					SUM(DESCANSO) AS DESCANSO, 
					SUM(INDETERMINADO) AS INDEFINIDA, 
					0 AS KM, 
					SUM(CONDUCCION) AS TOTALES 
				FROM 
					( 
						SELECT 
							IDCONDUCTOR, 
							DECODE(TPACTIVIDAD, 4, MINUTOS, 0) CONDUCCION, 
							DECODE(TPACTIVIDAD, 3, MINUTOS, 0) TRABAJO, 
							DECODE(TPACTIVIDAD, 2, MINUTOS, 0) DISPONIBILIDAD, 
							DECODE(TPACTIVIDAD, 1, MINUTOS, 0) DESCANSO, 
							DECODE(TPACTIVIDAD, 5, MINUTOS, 0) INDETERMINADO 
						FROM 
							( 
								SELECT 
									CDCONDUCTORES_EMP.IDCONDUCTOR, 
									A.TPACTIVIDAD AS TPACTIVIDAD, 
									SUM(A.MINUTOS) AS MINUTOS 
								FROM 
									CDACTIVIDADES_TEMPPRES A, 
									CDCONDUCTORES_EMP 
								WHERE 
									A.FEC_COMIENZO > ? 
									AND A.FEC_COMIENZO < ?  
									AND A.NUMREQ = ? 			 
									AND A.IDCONDUCTOR = CDCONDUCTORES_EMP.IDCONDUCTOR 									
									#SQLDELEG#	
								GROUP BY 
									CDCONDUCTORES_EMP.IDCONDUCTOR, 
									A.TPACTIVIDAD 
							)
					) GROUP BY IDCODUCTOR
			)
	) 