SELECT 
TPACTIVIDAD,
TO_CHAR(FEC_COMIENZO, 'DD/MM/YYYY HH24:MI:SS') AS FEC_COMIENZO,
MINUTOS,
TO_CHAR(FEC_FIN, 'DD/MM/YYYY HH24:MI:SS') AS FEC_FIN,
ORIGEN,
REGIMEN,
TRANS_TREN
FROM CDACTIVIDADES
WHERE 
NUMREQ = ? AND
IDCONDUCTOR = ? AND 
FEC_COMIENZO > = (? - 15) AND
FEC_FIN <= ?
UNION ALL
SELECT 
TPACTIVIDAD,
TO_CHAR(FEC_COMIENZO, 'DD/MM/YYYY HH24:MI:SS') AS FEC_COMIENZO,
(? - FEC_COMIENZO)*24*60 AS MINUTOS,
TO_CHAR(?, 'DD/MM/YYYY HH24:MI:SS') AS FEC_FIN,
ORIGEN,
REGIMEN,
TRANS_TREN
FROM CDACTIVIDADES
WHERE 
NUMREQ = ? AND
IDCONDUCTOR = ? AND 
FEC_COMIENZO < ? AND
FEC_FIN > ?
UNION ALL 
SELECT 
4 AS TPACTIVIDAD,
TO_CHAR(?, 'DD/MM/YYYY HH24:MI:SS') AS FEC_COMIENZO,
48*60 AS MINUTOS,
TO_CHAR(? +2 , 'DD/MM/YYYY HH24:MI:SS') AS FEC_FIN,
'M' as ORIGEN,
'0' as REGIMEN,
'N' as TRANS_TREN
FROM DUAL