SELECT 
  CDCONDUCTORES_EMP.IDCONDUCTOR 
FROM 
  CDCONDUCTOR_CONT, 
  CDCONDUCTORES_EMP, 
  CDVEMPRE_REQ_REALES 
WHERE 
  CDCONDUCTOR_CONT.CG_CONTRATO = CDVEMPRE_REQ_REALES.NUMREQ 
  AND CDCONDUCTORES_EMP.IDCONDUCTOR = CDCONDUCTOR_CONT.IDCONDUCTOR
  AND CDCONDUCTORES_EMP.CIF = CDVEMPRE_REQ_REALES.CIF  
  AND NUMREQ=?
  AND CDCONDUCTORES_EMP.CIF = ? 