/*
 * Volvo Group Tachograph Files API
 * Volvo Group Tachograph Files API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.opentach.server.remotevehicle.provider.volvo.client.api;

import java.util.Date;
import java.util.List;
import java.util.UUID;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.web.client.RestClientResponseException;

import com.ontimize.jee.common.tools.DateTools;
import com.opentach.server.remotevehicle.provider.volvo.client.model.TachoFileResponseObject;

/**
 * API tests for VolvoApi
 */
// @Ignore
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = { VolvoTestConfig.class })
public class VolvoApiTest {

	@Autowired
	private VolvoApi api;


	/**
	 * Tachograph Files
	 *
	 * The tachograph files resource is used to retreive driver card files for one or several drivers and/or tachograph (data memory) files for one or several vehicles. The result for both driver card files and tachograph files are ordered by ReceivedDateTime, latest entry last. The max number of items returned in one call is OEM specific.
	 *
	 * @throws ApiException
	 *          if the Api call fails
	 */
	@Test
	public void tachofilesGetTest() {
		Date starttime = DateTools.createDate(2018, 10, 9);
		String xCorrelationId = UUID.randomUUID().toString();
		Date stoptime = null;
		List<String> vin = null;
		List<String> driverId = null;
		List<String> contentFilter = null;
		String fileNameType = "ES";
		Boolean includeFileContent = Boolean.TRUE;
		try {
			TachoFileResponseObject response = this.api.tachofilesGet("015DED2EC1", "IOwiz8b0FS", starttime, xCorrelationId, stoptime, vin, driverId, contentFilter, fileNameType,
					includeFileContent);
			System.out.println(response);
		} catch (RestClientResponseException err) {
			System.out.println(err.getResponseBodyAsString());

		}
		// TODO: test validations
	}


}
