/*
 * Volvo Group Tachograph Files API Volvo Group Tachograph Files API The version of the OpenAPI document: 1.0.0 NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
 */

package com.opentach.server.remotevehicle.provider.volvo.client.model;

import java.util.Arrays;
import java.util.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DriverCardFilesObject
 */
@JsonPropertyOrder({ DriverCardFilesObject.JSON_PROPERTY_FILENAME, DriverCardFilesObject.JSON_PROPERTY_RECEIVED_DATE_TIME, DriverCardFilesObject.JSON_PROPERTY_DRIVER_ID, DriverCardFilesObject.JSON_PROPERTY_FIRST_NAME, DriverCardFilesObject.JSON_PROPERTY_LAST_NAME, DriverCardFilesObject.JSON_PROPERTY_FILE_CONTENT })
public class DriverCardFilesObject {
	public static final String	JSON_PROPERTY_FILENAME				= "filename";
	private String				filename;

	public static final String	JSON_PROPERTY_RECEIVED_DATE_TIME	= "receivedDateTime";
	private Date				receivedDateTime;

	public static final String	JSON_PROPERTY_DRIVER_ID				= "driverId";
	private DriverIdObject		driverId;

	public static final String	JSON_PROPERTY_FIRST_NAME			= "firstName";
	private String				firstName;

	public static final String	JSON_PROPERTY_LAST_NAME				= "lastName";
	private String				lastName;

	public static final String	JSON_PROPERTY_FILE_CONTENT			= "fileContent";
	private byte[]				fileContent;

	public DriverCardFilesObject filename(String filename) {
		this.filename = filename;
		return this;
	}

	/**
	 * Name of file
	 *
	 * @return filename
	 **/
	@JsonProperty(DriverCardFilesObject.JSON_PROPERTY_FILENAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public DriverCardFilesObject receivedDateTime(Date receivedDateTime) {

		this.receivedDateTime = receivedDateTime;
		return this;
	}

	/**
	 * Reception at Server. To be used for handling of \&quot;more data available\&quot;
	 *
	 * @return receivedDateTime
	 **/
	@JsonProperty(DriverCardFilesObject.JSON_PROPERTY_RECEIVED_DATE_TIME)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)
	public Date getReceivedDateTime() {
		return this.receivedDateTime;
	}

	public void setReceivedDateTime(Date receivedDateTime) {
		this.receivedDateTime = receivedDateTime;
	}

	public DriverCardFilesObject driverId(DriverIdObject driverId) {

		this.driverId = driverId;
		return this;
	}

	/**
	 * Get driverId
	 *
	 * @return driverId
	 **/
	@JsonProperty(DriverCardFilesObject.JSON_PROPERTY_DRIVER_ID)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)
	public DriverIdObject getDriverId() {
		return this.driverId;
	}

	public void setDriverId(DriverIdObject driverId) {
		this.driverId = driverId;
	}

	public DriverCardFilesObject firstName(String firstName) {

		this.firstName = firstName;
		return this;
	}

	/**
	 * Get firstName
	 *
	 * @return firstName
	 **/
	@JsonProperty(DriverCardFilesObject.JSON_PROPERTY_FIRST_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public DriverCardFilesObject lastName(String lastName) {

		this.lastName = lastName;
		return this;
	}

	/**
	 * Get lastName
	 *
	 * @return lastName
	 **/
	@JsonProperty(DriverCardFilesObject.JSON_PROPERTY_LAST_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public DriverCardFilesObject fileContent(byte[] fileContent) {

		this.fileContent = fileContent;
		return this;
	}

	/**
	 * Get fileContent
	 *
	 * @return fileContent
	 **/
	@JsonProperty(DriverCardFilesObject.JSON_PROPERTY_FILE_CONTENT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public byte[] getFileContent() {
		return this.fileContent;
	}

	public void setFileContent(byte[] fileContent) {
		this.fileContent = fileContent;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (this.getClass() != o.getClass())) {
			return false;
		}
		DriverCardFilesObject driverCardFilesObject = (DriverCardFilesObject) o;
		return Objects.equals(this.filename, driverCardFilesObject.filename) && Objects.equals(this.receivedDateTime, driverCardFilesObject.receivedDateTime) && Objects
				.equals(this.driverId, driverCardFilesObject.driverId) && Objects.equals(this.firstName, driverCardFilesObject.firstName) && Objects.equals(this.lastName,
						driverCardFilesObject.lastName) && Arrays.equals(this.fileContent, driverCardFilesObject.fileContent);
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.filename, this.receivedDateTime, this.driverId, this.firstName, this.lastName, Arrays.hashCode(this.fileContent));
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class DriverCardFilesObject {\n");
		sb.append("    filename: ").append(this.toIndentedString(this.filename)).append("\n");
		sb.append("    receivedDateTime: ").append(this.toIndentedString(this.receivedDateTime)).append("\n");
		sb.append("    driverId: ").append(this.toIndentedString(this.driverId)).append("\n");
		sb.append("    firstName: ").append(this.toIndentedString(this.firstName)).append("\n");
		sb.append("    lastName: ").append(this.toIndentedString(this.lastName)).append("\n");
		sb.append("    fileContent: ").append(this.toIndentedString(this.fileContent)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
