/*
 * Volvo Group Tachograph Files API Volvo Group Tachograph Files API The version of the OpenAPI document: 1.0.0 NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
 */

package com.opentach.server.remotevehicle.provider.volvo.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DriverIdObjectTachoDriverIdentification
 */
@JsonPropertyOrder({ DriverIdObjectTachoDriverIdentification.JSON_PROPERTY_DRIVER_IDENTIFICATION, DriverIdObjectTachoDriverIdentification.JSON_PROPERTY_CARD_ISSUING_MEMBER_STATE, DriverIdObjectTachoDriverIdentification.JSON_PROPERTY_CARD_REPLACEMENT_INDEX, DriverIdObjectTachoDriverIdentification.JSON_PROPERTY_CARD_RENEWAL_INDEX })
public class DriverIdObjectTachoDriverIdentification {
	public static final String	JSON_PROPERTY_DRIVER_IDENTIFICATION		= "driverIdentification";
	private String				driverIdentification;

	public static final String	JSON_PROPERTY_CARD_ISSUING_MEMBER_STATE	= "cardIssuingMemberState";
	private String				cardIssuingMemberState;

	public static final String	JSON_PROPERTY_CARD_REPLACEMENT_INDEX	= "cardReplacementIndex";
	private String				cardReplacementIndex;

	public static final String	JSON_PROPERTY_CARD_RENEWAL_INDEX		= "cardRenewalIndex";
	private String				cardRenewalIndex;

	public DriverIdObjectTachoDriverIdentification driverIdentification(String driverIdentification) {

		this.driverIdentification = driverIdentification;
		return this;
	}

	/**
	 * The unique identification of a driver in a Member State. This fields is formatted according the definition for driverIdentification in COMMISSION REGULATION (EC) No
	 * 1360/2002 Annex 1b
	 *
	 * @return driverIdentification
	 **/
	@JsonProperty(DriverIdObjectTachoDriverIdentification.JSON_PROPERTY_DRIVER_IDENTIFICATION)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)
	public String getDriverIdentification() {
		return this.driverIdentification;
	}

	public void setDriverIdentification(String driverIdentification) {
		this.driverIdentification = driverIdentification;
	}

	public DriverIdObjectTachoDriverIdentification cardIssuingMemberState(String cardIssuingMemberState) {

		this.cardIssuingMemberState = cardIssuingMemberState;
		return this;
	}

	/**
	 * The country alpha code of the Member State having issued the card. This fields is formatted according the definition for NationAlpha in COMMISSION REGULATION (EC) No
	 * 1360/2002 Annex 1b
	 *
	 * @return cardIssuingMemberState
	 **/
	@JsonProperty(DriverIdObjectTachoDriverIdentification.JSON_PROPERTY_CARD_ISSUING_MEMBER_STATE)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)
	public String getCardIssuingMemberState() {
		return this.cardIssuingMemberState;
	}

	public void setCardIssuingMemberState(String cardIssuingMemberState) {
		this.cardIssuingMemberState = cardIssuingMemberState;
	}

	public DriverIdObjectTachoDriverIdentification cardReplacementIndex(String cardReplacementIndex) {

		this.cardReplacementIndex = cardReplacementIndex;
		return this;
	}

	/**
	 * A card replacement index. This fields is formatted according the definition for CardReplacementIndex (chap 2.26) in: COMMISSION REGULATION (EC) No 1360/2002 Annex 1b
	 *
	 * @return cardReplacementIndex
	 **/
	@JsonProperty(DriverIdObjectTachoDriverIdentification.JSON_PROPERTY_CARD_REPLACEMENT_INDEX)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getCardReplacementIndex() {
		return this.cardReplacementIndex;
	}

	public void setCardReplacementIndex(String cardReplacementIndex) {
		this.cardReplacementIndex = cardReplacementIndex;
	}

	public DriverIdObjectTachoDriverIdentification cardRenewalIndex(String cardRenewalIndex) {

		this.cardRenewalIndex = cardRenewalIndex;
		return this;
	}

	/**
	 * A card renewal index. This fields is formatted according the definition for CardRenewalIndex (chap 2.25) in: COMMISSION REGULATION (EC) No 1360/2002 Annex 1b
	 *
	 * @return cardRenewalIndex
	 **/
	@JsonProperty(DriverIdObjectTachoDriverIdentification.JSON_PROPERTY_CARD_RENEWAL_INDEX)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getCardRenewalIndex() {
		return this.cardRenewalIndex;
	}

	public void setCardRenewalIndex(String cardRenewalIndex) {
		this.cardRenewalIndex = cardRenewalIndex;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (this.getClass() != o.getClass())) {
			return false;
		}
		DriverIdObjectTachoDriverIdentification driverIdObjectTachoDriverIdentification = (DriverIdObjectTachoDriverIdentification) o;
		return Objects.equals(this.driverIdentification, driverIdObjectTachoDriverIdentification.driverIdentification) && Objects.equals(this.cardIssuingMemberState,
				driverIdObjectTachoDriverIdentification.cardIssuingMemberState) && Objects.equals(this.cardReplacementIndex,
						driverIdObjectTachoDriverIdentification.cardReplacementIndex) && Objects.equals(this.cardRenewalIndex,
								driverIdObjectTachoDriverIdentification.cardRenewalIndex);
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.driverIdentification, this.cardIssuingMemberState, this.cardReplacementIndex, this.cardRenewalIndex);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class DriverIdObjectTachoDriverIdentification {\n");
		sb.append("    driverIdentification: ").append(this.toIndentedString(this.driverIdentification)).append("\n");
		sb.append("    cardIssuingMemberState: ").append(this.toIndentedString(this.cardIssuingMemberState)).append("\n");
		sb.append("    cardReplacementIndex: ").append(this.toIndentedString(this.cardReplacementIndex)).append("\n");
		sb.append("    cardRenewalIndex: ").append(this.toIndentedString(this.cardRenewalIndex)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
