/*
 * Volvo Group Tachograph Files API Volvo Group Tachograph Files API The version of the OpenAPI document: 1.0.0 NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
 */

package com.opentach.server.remotevehicle.provider.volvo.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Optional responses for error codes, detailing the error if needed
 */
@JsonPropertyOrder({ ErrorObject.JSON_PROPERTY_ERROR, ErrorObject.JSON_PROPERTY_ERROR_DESCRIPTION, ErrorObject.JSON_PROPERTY_ERROR_URI })
public class ErrorObject {
	public static final String	JSON_PROPERTY_ERROR				= "error";
	private String				error;

	public static final String	JSON_PROPERTY_ERROR_DESCRIPTION	= "error_description";
	private String				errorDescription;

	public static final String	JSON_PROPERTY_ERROR_URI			= "error_uri";
	private String				errorUri;

	public ErrorObject error(String error) {

		this.error = error;
		return this;
	}

	/**
	 * An identifier for this error
	 *
	 * @return error
	 **/
	@JsonProperty(ErrorObject.JSON_PROPERTY_ERROR)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getError() {
		return this.error;
	}

	public void setError(String error) {
		this.error = error;
	}

	public ErrorObject errorDescription(String errorDescription) {

		this.errorDescription = errorDescription;
		return this;
	}

	/**
	 * A description of the error
	 *
	 * @return errorDescription
	 **/
	@JsonProperty(ErrorObject.JSON_PROPERTY_ERROR_DESCRIPTION)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getErrorDescription() {
		return this.errorDescription;
	}

	public void setErrorDescription(String errorDescription) {
		this.errorDescription = errorDescription;
	}

	public ErrorObject errorUri(String errorUri) {

		this.errorUri = errorUri;
		return this;
	}

	/**
	 * A URI providing more information
	 *
	 * @return errorUri
	 **/
	@JsonProperty(ErrorObject.JSON_PROPERTY_ERROR_URI)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getErrorUri() {
		return this.errorUri;
	}

	public void setErrorUri(String errorUri) {
		this.errorUri = errorUri;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (this.getClass() != o.getClass())) {
			return false;
		}
		ErrorObject errorObject = (ErrorObject) o;
		return Objects.equals(this.error, errorObject.error) && Objects.equals(this.errorDescription, errorObject.errorDescription) && Objects.equals(this.errorUri,
				errorObject.errorUri);
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.error, this.errorDescription, this.errorUri);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ErrorObject {\n");
		sb.append("    error: ").append(this.toIndentedString(this.error)).append("\n");
		sb.append("    errorDescription: ").append(this.toIndentedString(this.errorDescription)).append("\n");
		sb.append("    errorUri: ").append(this.toIndentedString(this.errorUri)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
