/*
 * Volvo Group Tachograph Files API Volvo Group Tachograph Files API The version of the OpenAPI document: 1.0.0 NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
 */

package com.opentach.server.remotevehicle.provider.volvo.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * TachoFileResponseObjectTachoFilesResponse
 */
@JsonPropertyOrder({ TachoFileResponseObjectTachoFilesResponse.JSON_PROPERTY_DRIVER_CARD_FILES, TachoFileResponseObjectTachoFilesResponse.JSON_PROPERTY_TACHO_FILES })
public class TachoFileResponseObjectTachoFilesResponse {
	public static final String			JSON_PROPERTY_DRIVER_CARD_FILES	= "driverCardFiles";
	private List<DriverCardFilesObject>	driverCardFiles					= null;

	public static final String			JSON_PROPERTY_TACHO_FILES		= "tachoFiles";
	private List<TachoFilesObject>		tachoFiles						= null;

	public TachoFileResponseObjectTachoFilesResponse driverCardFiles(List<DriverCardFilesObject> driverCardFiles) {

		this.driverCardFiles = driverCardFiles;
		return this;
	}

	public TachoFileResponseObjectTachoFilesResponse addDriverCardFilesItem(DriverCardFilesObject driverCardFilesItem) {
		if (this.driverCardFiles == null) {
			this.driverCardFiles = new ArrayList<>();
		}
		this.driverCardFiles.add(driverCardFilesItem);
		return this;
	}

	/**
	 * Get driverCardFiles
	 *
	 * @return driverCardFiles
	 **/
	@JsonProperty(TachoFileResponseObjectTachoFilesResponse.JSON_PROPERTY_DRIVER_CARD_FILES)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public List<DriverCardFilesObject> getDriverCardFiles() {
		return this.driverCardFiles;
	}

	public void setDriverCardFiles(List<DriverCardFilesObject> driverCardFiles) {
		this.driverCardFiles = driverCardFiles;
	}

	public TachoFileResponseObjectTachoFilesResponse tachoFiles(List<TachoFilesObject> tachoFiles) {

		this.tachoFiles = tachoFiles;
		return this;
	}

	public TachoFileResponseObjectTachoFilesResponse addTachoFilesItem(TachoFilesObject tachoFilesItem) {
		if (this.tachoFiles == null) {
			this.tachoFiles = new ArrayList<>();
		}
		this.tachoFiles.add(tachoFilesItem);
		return this;
	}

	/**
	 * Get tachoFiles
	 *
	 * @return tachoFiles
	 **/
	@JsonProperty(TachoFileResponseObjectTachoFilesResponse.JSON_PROPERTY_TACHO_FILES)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public List<TachoFilesObject> getTachoFiles() {
		return this.tachoFiles;
	}

	public void setTachoFiles(List<TachoFilesObject> tachoFiles) {
		this.tachoFiles = tachoFiles;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (this.getClass() != o.getClass())) {
			return false;
		}
		TachoFileResponseObjectTachoFilesResponse tachoFileResponseObjectTachoFilesResponse = (TachoFileResponseObjectTachoFilesResponse) o;
		return Objects.equals(this.driverCardFiles, tachoFileResponseObjectTachoFilesResponse.driverCardFiles) && Objects.equals(this.tachoFiles,
				tachoFileResponseObjectTachoFilesResponse.tachoFiles);
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.driverCardFiles, this.tachoFiles);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class TachoFileResponseObjectTachoFilesResponse {\n");
		sb.append("    driverCardFiles: ").append(this.toIndentedString(this.driverCardFiles)).append("\n");
		sb.append("    tachoFiles: ").append(this.toIndentedString(this.tachoFiles)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
