/*
 * Tachograph File Archive Access meta data about about stored tachograph files, download and upload tachograph files The version of the OpenAPI document: 1.1.5 Contact:
 * team_tachograph_remote_download@rio.cloud NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package com.opentach.server.remotevehicle.provider.man.client.model;

import java.util.Objects;
import java.util.UUID;

import org.threeten.bp.OffsetDateTime;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Tachograph File Metadata Response
 */
@JsonPropertyOrder({ FileMetadataModel.JSON_PROPERTY_REFERENCE_ID, FileMetadataModel.JSON_PROPERTY_FILE_ID, FileMetadataModel.JSON_PROPERTY_CUSTOMER_ID, FileMetadataModel.JSON_PROPERTY_FILE_NAME, FileMetadataModel.JSON_PROPERTY_SIZE, FileMetadataModel.JSON_PROPERTY_FILE_TYPE, FileMetadataModel.JSON_PROPERTY_HAS_SECTIONS_VALID, FileMetadataModel.JSON_PROPERTY_IS_CORRUPTED, FileMetadataModel.JSON_PROPERTY_TIME_CREATED, FileMetadataModel.JSON_PROPERTY_TIME_MODIFIED, FileMetadataModel.JSON_PROPERTY_CREATED_BY, FileMetadataModel.JSON_PROPERTY_MODIFIED_BY })
public class FileMetadataModel {
	public static final String	JSON_PROPERTY_REFERENCE_ID			= "reference_id";
	private UUID				referenceId;

	public static final String	JSON_PROPERTY_FILE_ID				= "file_id";
	private Integer				fileId;

	public static final String	JSON_PROPERTY_CUSTOMER_ID			= "customer_id";
	private String				customerId;

	public static final String	JSON_PROPERTY_FILE_NAME				= "file_name";
	private String				fileName;

	public static final String	JSON_PROPERTY_SIZE					= "size";
	private Integer				size;

	public static final String	JSON_PROPERTY_FILE_TYPE				= "file_type";
	private String				fileType;

	public static final String	JSON_PROPERTY_HAS_SECTIONS_VALID	= "has_sections_valid";
	private Boolean				hasSectionsValid;

	public static final String	JSON_PROPERTY_IS_CORRUPTED			= "is_corrupted";
	private Boolean				isCorrupted;

	public static final String	JSON_PROPERTY_TIME_CREATED			= "time_created";
	private OffsetDateTime		timeCreated;

	public static final String	JSON_PROPERTY_TIME_MODIFIED			= "time_modified";
	private OffsetDateTime		timeModified;

	public static final String	JSON_PROPERTY_CREATED_BY			= "created_by";
	private String				createdBy;

	public static final String	JSON_PROPERTY_MODIFIED_BY			= "modified_by";
	private String				modifiedBy;

	public FileMetadataModel referenceId(UUID referenceId) {
		this.referenceId = referenceId;
		return this;
	}

	/**
	 * In case of file_type driver this is the driverId, when file_type vehicle this is the vehicle id / asset id, for other cases this is empty
	 *
	 * @return referenceId
	 **/
	@JsonProperty(FileMetadataModel.JSON_PROPERTY_REFERENCE_ID)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public UUID getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(UUID referenceId) {
		this.referenceId = referenceId;
	}

	public FileMetadataModel fileId(Integer fileId) {

		this.fileId = fileId;
		return this;
	}

	/**
	 * File identification. Globally unique.
	 *
	 * @return fileId
	 **/
	@JsonProperty(FileMetadataModel.JSON_PROPERTY_FILE_ID)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public FileMetadataModel customerId(String customerId) {

		this.customerId = customerId;
		return this;
	}

	/**
	 * Customer id
	 *
	 * @return customerId
	 **/
	@JsonProperty(FileMetadataModel.JSON_PROPERTY_CUSTOMER_ID)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public FileMetadataModel fileName(String fileName) {
		this.fileName = fileName;
		return this;
	}

	/**
	 * File name
	 *
	 * @return fileName
	 **/
	@JsonProperty(FileMetadataModel.JSON_PROPERTY_FILE_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public FileMetadataModel size(Integer size) {

		this.size = size;
		return this;
	}

	/**
	 * File size
	 *
	 * @return size
	 **/
	@JsonProperty(FileMetadataModel.JSON_PROPERTY_SIZE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	public FileMetadataModel fileType(String fileType) {

		this.fileType = fileType;
		return this;
	}

	/**
	 * File type
	 *
	 * @return fileType
	 **/
	@JsonProperty(FileMetadataModel.JSON_PROPERTY_FILE_TYPE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public FileMetadataModel hasSectionsValid(Boolean hasSectionsValid) {

		this.hasSectionsValid = hasSectionsValid;
		return this;
	}

	/**
	 * Has sections valid
	 *
	 * @return hasSectionsValid
	 **/
	@JsonProperty(FileMetadataModel.JSON_PROPERTY_HAS_SECTIONS_VALID)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public Boolean getHasSectionsValid() {
		return this.hasSectionsValid;
	}

	public void setHasSectionsValid(Boolean hasSectionsValid) {
		this.hasSectionsValid = hasSectionsValid;
	}

	public FileMetadataModel isCorrupted(Boolean isCorrupted) {

		this.isCorrupted = isCorrupted;
		return this;
	}

	/**
	 * Is corrupted
	 *
	 * @return isCorrupted
	 **/
	@JsonProperty(FileMetadataModel.JSON_PROPERTY_IS_CORRUPTED)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public Boolean getIsCorrupted() {
		return this.isCorrupted;
	}

	public void setIsCorrupted(Boolean isCorrupted) {
		this.isCorrupted = isCorrupted;
	}

	public FileMetadataModel timeCreated(OffsetDateTime timeCreated) {

		this.timeCreated = timeCreated;
		return this;
	}

	/**
	 * UTC value formatted as date-time (see: RFC 3339, section 5.6)
	 *
	 * @return timeCreated
	 **/
	@JsonProperty(FileMetadataModel.JSON_PROPERTY_TIME_CREATED)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public OffsetDateTime getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(OffsetDateTime timeCreated) {
		this.timeCreated = timeCreated;
	}

	public FileMetadataModel timeModified(OffsetDateTime timeModified) {

		this.timeModified = timeModified;
		return this;
	}

	/**
	 * UTC value formatted as date-time (see: RFC 3339, section 5.6)
	 *
	 * @return timeModified
	 **/
	@JsonProperty(FileMetadataModel.JSON_PROPERTY_TIME_MODIFIED)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public OffsetDateTime getTimeModified() {
		return this.timeModified;
	}

	public void setTimeModified(OffsetDateTime timeModified) {
		this.timeModified = timeModified;
	}

	public FileMetadataModel createdBy(String createdBy) {

		this.createdBy = createdBy;
		return this;
	}

	/**
	 * Created by
	 *
	 * @return createdBy
	 **/
	@JsonProperty(FileMetadataModel.JSON_PROPERTY_CREATED_BY)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public FileMetadataModel modifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
		return this;
	}

	/**
	 * Last modified by
	 *
	 * @return modifiedBy
	 **/
	@JsonProperty(FileMetadataModel.JSON_PROPERTY_MODIFIED_BY)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (this.getClass() != o.getClass())) {
			return false;
		}
		FileMetadataModel fileMetadataModel = (FileMetadataModel) o;
		return Objects.equals(this.referenceId, fileMetadataModel.referenceId) && Objects.equals(this.fileId, fileMetadataModel.fileId) && Objects.equals(this.customerId,
				fileMetadataModel.customerId) && Objects.equals(this.fileName, fileMetadataModel.fileName) && Objects.equals(this.size, fileMetadataModel.size) && Objects
				.equals(this.fileType, fileMetadataModel.fileType) && Objects.equals(this.hasSectionsValid, fileMetadataModel.hasSectionsValid) && Objects
				.equals(this.isCorrupted, fileMetadataModel.isCorrupted) && Objects.equals(this.timeCreated, fileMetadataModel.timeCreated) && Objects
				.equals(this.timeModified, fileMetadataModel.timeModified) && Objects.equals(this.createdBy,
						fileMetadataModel.createdBy) && Objects.equals(this.modifiedBy, fileMetadataModel.modifiedBy);
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.referenceId, this.fileId, this.customerId, this.fileName, this.size, this.fileType, this.hasSectionsValid, this.isCorrupted, this.timeCreated,
				this.timeModified, this.createdBy, this.modifiedBy);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FileMetadataModel {\n");
		sb.append("    referenceId: ").append(this.toIndentedString(this.referenceId)).append("\n");
		sb.append("    fileId: ").append(this.toIndentedString(this.fileId)).append("\n");
		sb.append("    customerId: ").append(this.toIndentedString(this.customerId)).append("\n");
		sb.append("    fileName: ").append(this.toIndentedString(this.fileName)).append("\n");
		sb.append("    size: ").append(this.toIndentedString(this.size)).append("\n");
		sb.append("    fileType: ").append(this.toIndentedString(this.fileType)).append("\n");
		sb.append("    hasSectionsValid: ").append(this.toIndentedString(this.hasSectionsValid)).append("\n");
		sb.append("    isCorrupted: ").append(this.toIndentedString(this.isCorrupted)).append("\n");
		sb.append("    timeCreated: ").append(this.toIndentedString(this.timeCreated)).append("\n");
		sb.append("    timeModified: ").append(this.toIndentedString(this.timeModified)).append("\n");
		sb.append("    createdBy: ").append(this.toIndentedString(this.createdBy)).append("\n");
		sb.append("    modifiedBy: ").append(this.toIndentedString(this.modifiedBy)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
