/*
 * Tachograph File Archive Access meta data about about stored tachograph files, download and upload tachograph files The version of the OpenAPI document: 1.1.5 Contact:
 * team_tachograph_remote_download@rio.cloud NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package com.opentach.server.remotevehicle.provider.man.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PaginationModel
 */
@JsonPropertyOrder({ PaginationModel.JSON_PROPERTY_OFFSET, PaginationModel.JSON_PROPERTY_LIMIT, PaginationModel.JSON_PROPERTY_PREVIOUS, PaginationModel.JSON_PROPERTY_NEXT })
public class PaginationModel {
	public static final String	JSON_PROPERTY_OFFSET	= "offset";
	private Integer				offset;

	public static final String	JSON_PROPERTY_LIMIT		= "limit";
	private Integer				limit;

	public static final String	JSON_PROPERTY_PREVIOUS	= "previous";
	private String				previous;

	public static final String	JSON_PROPERTY_NEXT		= "next";
	private String				next;

	/**
	 * Get offset
	 *
	 * @return offset
	 **/
	@JsonProperty(PaginationModel.JSON_PROPERTY_OFFSET)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public Integer getOffset() {
		return this.offset;
	}

	/**
	 * Get limit
	 *
	 * @return limit
	 **/
	@JsonProperty(PaginationModel.JSON_PROPERTY_LIMIT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public Integer getLimit() {
		return this.limit;
	}

	/**
	 * Get previous
	 *
	 * @return previous
	 **/
	@JsonProperty(PaginationModel.JSON_PROPERTY_PREVIOUS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getPrevious() {
		return this.previous;
	}

	/**
	 * Get next
	 *
	 * @return next
	 **/
	@JsonProperty(PaginationModel.JSON_PROPERTY_NEXT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getNext() {
		return this.next;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (this.getClass() != o.getClass())) {
			return false;
		}
		PaginationModel paginationModel = (PaginationModel) o;
		return Objects.equals(this.offset, paginationModel.offset) && Objects.equals(this.limit, paginationModel.limit) && Objects.equals(this.previous,
				paginationModel.previous) && Objects.equals(this.next, paginationModel.next);
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.offset, this.limit, this.previous, this.next);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PaginationModel {\n");
		sb.append("    offset: ").append(this.toIndentedString(this.offset)).append("\n");
		sb.append("    limit: ").append(this.toIndentedString(this.limit)).append("\n");
		sb.append("    previous: ").append(this.toIndentedString(this.previous)).append("\n");
		sb.append("    next: ").append(this.toIndentedString(this.next)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
