/*
 * Tachograph File Archive Access meta data about about stored tachograph files, download and upload tachograph files The version of the OpenAPI document: 1.1.5 Contact:
 * team_tachograph_remote_download@rio.cloud NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package com.opentach.server.remotevehicle.provider.common.rest.invoker;

import java.text.FieldPosition;
import java.util.Date;

import com.fasterxml.jackson.databind.util.ISO8601DateFormat;
import com.fasterxml.jackson.databind.util.ISO8601Utils;

public class RFC3339DateFormat extends ISO8601DateFormat {

	// Same as ISO8601DateFormat but serializing milliseconds.
	@Override
	public StringBuffer format(Date date, StringBuffer toAppendTo, FieldPosition fieldPosition) {
		String value = ISO8601Utils.format(date, true);
		toAppendTo.append(value);
		return toAppendTo;
	}

}