CREATE OR REPLACE VIEW CDVINFORM_PENDDESCARGA AS 
  SELECT 
		CG_CONTRATO,
		CIF,
		EMP,                  
		TELF,
		FAX,
		EMAIL,
		MOVIL, 
		IDORIGEN,
		DSCR,
		TIPO,		
		(case when MAX_FFIN is null then max_f_descarga_datos when max_f_descarga_datos is null then MAX_FFIN else GREATEST (MAX_FFIN,MAX_F_DESCARGA_DATOS) end) as F_DESCARGA_DATOS,
		TRUNC(SYSDATE-(case when MAX_FFIN is null then max_f_descarga_datos when max_f_descarga_datos is null then MAX_FFIN else GREATEST (MAX_FFIN,MAX_F_DESCARGA_DATOS) end)) AS DIAS,
		IDDELEGACION,
		ZONA,
		VDATOS_DESCARGAS.CG_PROV,
        PROVINCIAS.NOMB AS PROVINCIA
	FROM
		(
		SELECT 
			CDVEHICULO_CONT.MATRICULA AS IDORIGEN,
			CDVEHICULOS_EMP.DSCR,
			CDVEHICULO_CONT.CG_CONTRATO,
			CDVEHICULOS_EMP.CIF          AS CIF,
			0 AS TIPO,
			DFEMP.NOMB               AS EMP,            
			DFEMP.TELF               AS TELF,
			DFEMP.FAX               AS FAX,
			DFEMP.EMAIL               AS EMAIL,
			DFEMP.MOVIL               AS MOVIL, 
			IDDELEGACION,
			(SELECT 
				MAX(CDFICHEROS.FECFIN) 
			FROM 
				CDFICHEROS,CDFICHEROS_CONTRATO 
			WHERE 
				CDFICHEROS.IDFICHERO   = CDFICHEROS_CONTRATO.IDFICHERO
				AND CDVEHICULO_CONT.CG_CONTRATO = CDFICHEROS_CONTRATO.CG_CONTRATO
				AND CDVEHICULO_CONT.MATRICULA = CDFICHEROS.IDORIGEN
				AND CDFICHEROS.TIPO = 'VU') as MAX_FFIN,
			(SELECT 
				MAX(CDFICHEROS.F_DESCARGA_DATOS) 
			FROM 
				CDFICHEROS,CDFICHEROS_CONTRATO 
			WHERE 
				CDFICHEROS.IDFICHERO   = CDFICHEROS_CONTRATO.IDFICHERO
				AND CDVEHICULO_CONT.CG_CONTRATO = CDFICHEROS_CONTRATO.CG_CONTRATO
				AND CDVEHICULO_CONT.MATRICULA = CDFICHEROS.IDORIGEN
				AND CDFICHEROS.TIPO = 'VU') as MAX_F_DESCARGA_DATOS,
			DFEMP.CG_PROV,
			CDVEMPRE_REQ_REALES.ZONA
		FROM 
			CDVEHICULO_CONT,
			CDVEHICULOS_EMP,
			CDVEMPRE_REQ_REALES,
			DFEMP
		WHERE 
			CDVEHICULO_CONT.F_BAJA  IS NULL
			AND CDVEHICULO_CONT.MATRICULA  =CDVEHICULOS_EMP.MATRICULA
			AND CDVEHICULO_CONT.CG_CONTRATO=CDVEMPRE_REQ_REALES.NUMREQ
			AND CDVEMPRE_REQ_REALES.CIF            = CDVEHICULOS_EMP.CIF
			AND CDVEMPRE_REQ_REALES.CIF             = DFEMP.CIF
			AND CDVEHICULOS_EMP.DURMIENTE  = 'N'
			AND CDVEMPRE_REQ_REALES.F_BAJA         IS NULL
		UNION ALL		
		SELECT 
			CDCONDUCTORES_EMP.IDCONDUCTOR AS IDORIGEN,
			CDCONDUCTORES_EMP.APELLIDOS || ', ' || CDCONDUCTORES_EMP.NOMBRE AS DSCR,
			CDCONDUCTOR_CONT.CG_CONTRATO,
			CDCONDUCTORES_EMP.CIF,
			1 AS TIPO,
			DFEMP.NOMB               AS EMP,            
			DFEMP.TELF               AS TELF,
			DFEMP.FAX               AS FAX,
			DFEMP.EMAIL               AS EMAIL,
			DFEMP.MOVIL               AS MOVIL, 
			IDDELEGACION,						
			(SELECT 
				MAX(CDFICHEROS.FECFIN) 
			FROM 
				CDFICHEROS,CDFICHEROS_CONTRATO 
			WHERE 
				CDFICHEROS.IDFICHERO   = CDFICHEROS_CONTRATO.IDFICHERO
				AND CDCONDUCTOR_CONT.CG_CONTRATO = CDFICHEROS_CONTRATO.CG_CONTRATO
				AND CDCONDUCTORES_EMP.IDCONDUCTOR = CDFICHEROS.IDORIGEN
				AND CDFICHEROS.TIPO = 'TC') as MAX_FFIN,
			(SELECT 
				MAX(CDFICHEROS.F_DESCARGA_DATOS) 
			FROM 
				CDFICHEROS,CDFICHEROS_CONTRATO 
			WHERE 
				CDFICHEROS.IDFICHERO   = CDFICHEROS_CONTRATO.IDFICHERO
				AND CDCONDUCTOR_CONT.CG_CONTRATO = CDFICHEROS_CONTRATO.CG_CONTRATO
				AND CDCONDUCTORES_EMP.IDCONDUCTOR = CDFICHEROS.IDORIGEN
				AND CDFICHEROS.TIPO = 'TC') as MAX_F_DESCARGA_DATOS,
			DFEMP.CG_PROV,
			CDVEMPRE_REQ_REALES.ZONA	
		FROM 
			CDCONDUCTOR_CONT,
			CDCONDUCTORES_EMP,
			CDVEMPRE_REQ_REALES,
			DFEMP
		WHERE 
			CDCONDUCTOR_CONT.F_BAJA  IS NULL
			AND CDCONDUCTOR_CONT.DNI        =CDCONDUCTORES_EMP.DNI
			AND CDCONDUCTOR_CONT.CG_CONTRATO=CDVEMPRE_REQ_REALES.NUMREQ
			AND CDVEMPRE_REQ_REALES.CIF             = CDCONDUCTORES_EMP.CIF
			AND CDVEMPRE_REQ_REALES.CIF             = DFEMP.CIF
			AND CDCONDUCTORES_EMP.DURMIENTE = 'N'
			AND CDVEMPRE_REQ_REALES.F_BAJA         IS NULL						
		) VDATOS_DESCARGAS, PROVINCIAS
	WHERE 
    VDATOS_DESCARGAS.CG_PROV = PROVINCIAS.CG_PROV AND 
		((case when MAX_FFIN is null then max_f_descarga_datos when max_f_descarga_datos is null then MAX_FFIN else GREATEST (MAX_FFIN,MAX_F_DESCARGA_DATOS) end) < ( SYSDATE - (CASE WHEN (TIPO=1)	THEN 28	ELSE 90  END))
		OR (case when MAX_FFIN is null then max_f_descarga_datos when max_f_descarga_datos is null then MAX_FFIN else GREATEST (MAX_FFIN,MAX_F_DESCARGA_DATOS) end) IS NULL);