ALTER TABLE LAB_AGREEMENT ADD AGR_FOUR_MONTHLY_MINUTES NUMBER;
ALTER TABLE LAB_AGREEMENT ADD AGR_FOUR_WEEKLY_MINUTES NUMBER;


ALTER TABLE LAB_DRIVER_CONTRACTS ADD DRC_PARTIAL_4WEEKLY_MINUTES NUMBER;
ALTER TABLE LAB_DRIVER_CONTRACTS ADD DRC_PARTIAL_4MONTHLY_MINUTES NUMBER;
ALTER TABLE LAB_DRIVER_CONTRACTS ADD DRC_COMPL_4WEEKLY_MINUTES NUMBER;
ALTER TABLE LAB_DRIVER_CONTRACTS ADD DRC_COMPL_4MONTHLY_MINUTES NUMBER;


CREATE OR REPLACE VIEW VLAB_DRIVER_CONTRACTS AS 
  SELECT
	LAB_DRIVER_CONTRACTS.IDCONDUCTOR,
	LAB_DRIVER_CONTRACTS.CIF,
	LAB_DRIVER_CONTRACTS.DRC_ID,
	LAB_DRIVER_CONTRACTS.DRC_TYPE,
	LAB_DRIVER_CONTRACTS.AGR_ID,
	LAB_DRIVER_CONTRACTS.DRC_IRREGULAR_JOURNAL,
	LAB_DRIVER_CONTRACTS.DRC_DATE_FROM,
	LAB_DRIVER_CONTRACTS.DRC_DATE_TO,
	LAB_DRIVER_CONTRACTS.DRC_PARTIAL_DAILY_MINUTES,
	LAB_DRIVER_CONTRACTS.DRC_PARTIAL_WEEKLY_MINUTES,
	LAB_DRIVER_CONTRACTS.DRC_PARTIAL_BIWEEKLY_MINUTES,
    LAB_DRIVER_CONTRACTS.DRC_PARTIAL_4WEEKLY_MINUTES,
	LAB_DRIVER_CONTRACTS.DRC_PARTIAL_MONTHLY_MINUTES,
    LAB_DRIVER_CONTRACTS.DRC_PARTIAL_4MONTHLY_MINUTES,
	LAB_DRIVER_CONTRACTS.DRC_PARTIAL_ANNUAL_MINUTES,
	LAB_DRIVER_CONTRACTS.DRC_COMPL_DAILY_MINUTES,
	LAB_DRIVER_CONTRACTS.DRC_COMPL_WEEKLY_MINUTES,
	LAB_DRIVER_CONTRACTS.DRC_COMPL_BIWEEKLY_MINUTES,
    LAB_DRIVER_CONTRACTS.DRC_COMPL_4WEEKLY_MINUTES,
	LAB_DRIVER_CONTRACTS.DRC_COMPL_MONTHLY_MINUTES,
    LAB_DRIVER_CONTRACTS.DRC_COMPL_4MONTHLY_MINUTES,
	LAB_DRIVER_CONTRACTS.DRC_COMPL_ANNUAL_MINUTES,
    LAB_AGREEMENT.AGR_NAME,
	CDCONDUCTORES_EMP.NOMBRE,
	CDCONDUCTORES_EMP.APELLIDOS,
	CDCONDUCTORES_EMP.DNI
FROM 
  LAB_DRIVER_CONTRACTS,
  LAB_AGREEMENT,
  CDCONDUCTORES_EMP
WHERE
  LAB_DRIVER_CONTRACTS.AGR_ID = LAB_AGREEMENT.AGR_ID
  AND CDCONDUCTORES_EMP.IDCONDUCTOR = LAB_DRIVER_CONTRACTS.IDCONDUCTOR
  AND CDCONDUCTORES_EMP.CIF = LAB_DRIVER_CONTRACTS.CIF;
