
  CREATE OR REPLACE VIEW CDVINFORM_ACTIVIDADES AS 
  SELECT
	CDVEMPRE_REQ_REALES.FECINID AS INSP_FECINI,
	CDVEMPRE_REQ_REALES.FECFIND AS INSP_FECFIN,
	CDCONDUCTORES_EMP.DNI,
	CDCONDUCTORES_EMP.NOMBRE,
	CDCONDUCTORES_EMP.APELLIDOS,
	CDCONDUCTORES_EMP.NOMBRE ||' '|| CDCONDUCTORES_EMP.APELLIDOS as DSCR_CONDUCTOR,
	CDVEMPRE_REQ_REALES.CIF,
	(SELECT A.NOMB FROM DFEMP A WHERE A.CIF = CDVEMPRE_REQ_REALES.CIF) AS NOMB,
	CDVEMPRE_REQ_REALES.IDINSPECCION,
	CDACTIVIDADES.NUMREQ,
	CDACTIVIDADES.NUMREQ AS CG_CONTRATO,
	CDACTIVIDADES.IDCONDUCTOR,
	CDACTIVIDADES.TPACTIVIDAD,
	CDACTIVIDADES.FEC_COMIENZO,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'Day') AS DIA_SEM,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'DD') AS DIA,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'HH24') AS HORA,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'IW') AS SEMANA,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'Month') AS MES2,
	 'MES' || TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'MM') || '.' || TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'Month') AS MES,
	TO_CHAR(trunc(CDACTIVIDADES.FEC_COMIENZO, 'ww'),'DD/MM/YYYY') AS INI_SEMANA,
	TO_CHAR(trunc(CDACTIVIDADES.FEC_COMIENZO, 'ww') + 6,'DD/MM/YYYY') AS FIN_SEMANA,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'YYYY') AS ANHO,
	CDACTIVIDADES.FEC_FIN,
	CDACTIVIDADES.MINUTOS,
	(CDACTIVIDADES.MINUTOS / 60 ) AS HORAS_COND,
	(CDACTIVIDADES.MINUTOS * 60 ) AS SEGUNDOS,
	CDACTIVIDADES.TRANS_TREN,
	CDACTIVIDADES.FUERA_AMBITO,
	CDACTIVIDADES.PROCEDENCIA,
	CDACTIVIDADES.MATRICULA,
	CDACTIVIDADES.USUARIO_ALTA,
	CDACTIVIDADES.F_ALTA,
	CDACTIVIDADES.USUARIO_MODIF,
	CDACTIVIDADES.F_MODIF,
	CDTIPO_ACTIVIDAD.DSCR AS DSCR_ACT,
	CDACTIVIDADES.ORIGEN,
	(CASE WHEN CDACTIVIDADES.ORIGEN='M' THEN 'MANUAL' WHEN  CDACTIVIDADES.ORIGEN='A' THEN 'AUTOMATICO' ELSE NULL END) ORIGEN_DSCR,
	CDACTIVIDADES.REGIMEN,
	(CASE  WHEN CDACTIVIDADES.REGIMEN='0' THEN 'EN_SOLITARIO' WHEN  CDACTIVIDADES.REGIMEN='1' THEN 'EN_EQUIPO' ELSE NULL END) REGIMEN_DSCR,
	CDACTIVIDADES.RANURA,
	CDACTIVIDADES.ESTADO_TRJ_RANURA,
	(CASE WHEN CDACTIVIDADES.RANURA='0' THEN 'CONDUCTOR' WHEN CDACTIVIDADES.RANURA='1' THEN 'CONDUCTOR2' ELSE NULL END) RANURA_DSCR,
	(CASE WHEN CDACTIVIDADES.ESTADO_TRJ_RANURA='0' THEN 'INSERTADA' WHEN CDACTIVIDADES.ESTADO_TRJ_RANURA ='1' THEN 'NO_INSERTADA' ELSE NULL END) ESTADO_TRJ_RANURA_DSCR
FROM 
	CDACTIVIDADES ,
	CDTIPO_ACTIVIDAD, 
	CDVEMPRE_REQ_REALES, 
	CDCONDUCTORES_EMP, 
	CDCONDUCTOR_CONT
WHERE 
	CDTIPO_ACTIVIDAD.TPACTIVIDAD   = CDACTIVIDADES.TPACTIVIDAD
    AND CDACTIVIDADES.NUMREQ  = CDVEMPRE_REQ_REALES.NUMREQ
    AND CDCONDUCTORES_EMP.IDCONDUCTOR  = CDACTIVIDADES.IDCONDUCTOR
    AND CDCONDUCTORES_EMP.CIF          = CDVEMPRE_REQ_REALES.CIF
    AND CDCONDUCTOR_CONT.IDCONDUCTOR           = CDCONDUCTORES_EMP.IDCONDUCTOR
    AND CDCONDUCTOR_CONT.CG_CONTRATO   = CDVEMPRE_REQ_REALES.NUMREQ
UNION ALL
SELECT
	CDVEMPRE_REQ_REALES.FECINID AS INSP_FECINI,
	CDVEMPRE_REQ_REALES.FECFIND AS INSP_FECFIN,
	'DESCONOCIDO' AS DNI,
	'DESCONOCIDO' AS NOMBRE,
	'DESCONOCIDO' AS APELLIDOS,
	'DESCONOCIDO' AS DSCR_CONDUCTOR,
	CDVEMPRE_REQ_REALES.CIF,
	(SELECT A.NOMB FROM DFEMP A WHERE A.CIF = CDVEMPRE_REQ_REALES.CIF) AS NOMB,
	CDVEMPRE_REQ_REALES.IDINSPECCION,
	CDACTIVIDADES.NUMREQ,
	CDACTIVIDADES.NUMREQ AS CG_CONTRATO,
	CDACTIVIDADES.IDCONDUCTOR,
	CDACTIVIDADES.TPACTIVIDAD,
	CDACTIVIDADES.FEC_COMIENZO,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'Day') AS DIA_SEM,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'DD') AS DIA,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'HH24') AS HORA,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'IW') AS SEMANA,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'Month') AS MES2,
	 'MES' || TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'MM') || '.' || TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'Month') AS MES,
	TO_CHAR(trunc(CDACTIVIDADES.FEC_COMIENZO, 'ww'),'DD/MM/YYYY') AS INI_SEMANA,
	TO_CHAR(trunc(CDACTIVIDADES.FEC_COMIENZO, 'ww') + 6,'DD/MM/YYYY') AS FIN_SEMANA,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'YYYY') AS ANHO,
	CDACTIVIDADES.FEC_FIN,
	CDACTIVIDADES.MINUTOS,
	(CDACTIVIDADES.MINUTOS / 60 ) AS HORAS_COND,
	(CDACTIVIDADES.MINUTOS * 60 ) AS SEGUNDOS,
	CDACTIVIDADES.TRANS_TREN,
	CDACTIVIDADES.FUERA_AMBITO,
	CDACTIVIDADES.PROCEDENCIA,
	CDACTIVIDADES.MATRICULA,
	CDACTIVIDADES.USUARIO_ALTA,
	CDACTIVIDADES.F_ALTA,
	CDACTIVIDADES.USUARIO_MODIF,
	CDACTIVIDADES.F_MODIF,
	CDTIPO_ACTIVIDAD.DSCR AS DSCR_ACT,
	CDACTIVIDADES.ORIGEN,
	(CASE WHEN CDACTIVIDADES.ORIGEN='M' THEN 'MANUAL' WHEN  CDACTIVIDADES.ORIGEN='A' THEN 'AUTOMATICO' ELSE NULL END) ORIGEN_DSCR,
	CDACTIVIDADES.REGIMEN,
	(CASE  WHEN CDACTIVIDADES.REGIMEN='0' THEN 'EN_SOLITARIO' WHEN  CDACTIVIDADES.REGIMEN='1' THEN 'EN_EQUIPO' ELSE NULL END) REGIMEN_DSCR,
	CDACTIVIDADES.RANURA,
	CDACTIVIDADES.ESTADO_TRJ_RANURA,
	(CASE WHEN CDACTIVIDADES.RANURA='0' THEN 'CONDUCTOR' WHEN CDACTIVIDADES.RANURA='1' THEN 'CONDUCTOR2' ELSE NULL END) RANURA_DSCR,
	(CASE WHEN CDACTIVIDADES.ESTADO_TRJ_RANURA='0' THEN 'INSERTADA' WHEN CDACTIVIDADES.ESTADO_TRJ_RANURA ='1' THEN 'NO_INSERTADA' ELSE NULL END) ESTADO_TRJ_RANURA_DSCR
FROM 
	CDACTIVIDADES ,
	CDTIPO_ACTIVIDAD, 
	CDVEMPRE_REQ_REALES
WHERE 
	CDTIPO_ACTIVIDAD.TPACTIVIDAD   = CDACTIVIDADES.TPACTIVIDAD
	AND CDACTIVIDADES.NUMREQ  = CDVEMPRE_REQ_REALES.NUMREQ
    AND CDACTIVIDADES.IDCONDUCTOR = 'XXXXXXXXX'
    AND CDACTIVIDADES.RANURA = 0
UNION ALL
SELECT
	CDVEMPRE_REQ_REALES.FECINID AS INSP_FECINI,
	CDVEMPRE_REQ_REALES.FECFIND AS INSP_FECFIN,
	'NO_ASOCIADO' AS DNI,
	'NO_ASOCIADO' AS NOMBRE,
	'NO_ASOCIADO' AS APELLIDOS,
	'NO_ASOCIADO' AS DSCR_CONDUCTOR,
	CDVEMPRE_REQ_REALES.CIF,
	(SELECT A.NOMB FROM DFEMP A WHERE A.CIF = CDVEMPRE_REQ_REALES.CIF) AS NOMB,
	CDVEMPRE_REQ_REALES.IDINSPECCION,
	CDACTIVIDADES.NUMREQ,
	CDACTIVIDADES.NUMREQ AS CG_CONTRATO,
	CDACTIVIDADES.IDCONDUCTOR,
	CDACTIVIDADES.TPACTIVIDAD,
	CDACTIVIDADES.FEC_COMIENZO,
	--CDACTIVIDADES_TEMPPRES.FEC_COMIENZO AS fecini,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'Day') AS DIA_SEM,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'DD') AS DIA,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'HH24') AS HORA,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'IW') AS SEMANA,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'Month') AS MES2,
	 'MES' || TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'MM') || '.' || TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'Month') AS MES,
	TO_CHAR(trunc(CDACTIVIDADES.FEC_COMIENZO, 'ww'),'DD/MM/YYYY') AS INI_SEMANA,
	TO_CHAR(trunc(CDACTIVIDADES.FEC_COMIENZO, 'ww') + 6,'DD/MM/YYYY') AS FIN_SEMANA,
	TO_CHAR(CDACTIVIDADES.FEC_COMIENZO,'YYYY') AS ANHO,
	CDACTIVIDADES.FEC_FIN,
	--CDACTIVIDADES_TEMPPRES.fec_fin AS fecfin,
	CDACTIVIDADES.MINUTOS,
	(CDACTIVIDADES.MINUTOS / 60 ) AS HORAS_COND,
     (CDACTIVIDADES.MINUTOS * 60 ) AS SEGUNDOS,
	CDACTIVIDADES.TRANS_TREN,
	CDACTIVIDADES.FUERA_AMBITO,
	CDACTIVIDADES.PROCEDENCIA,
	CDACTIVIDADES.MATRICULA,
	CDACTIVIDADES.USUARIO_ALTA,
	CDACTIVIDADES.F_ALTA,
	CDACTIVIDADES.USUARIO_MODIF,
	CDACTIVIDADES.F_MODIF,
	CDTIPO_ACTIVIDAD.DSCR AS DSCR_ACT,
	CDACTIVIDADES.ORIGEN,
	(CASE WHEN CDACTIVIDADES.ORIGEN='M' THEN 'MANUAL' WHEN  CDACTIVIDADES.ORIGEN='A' THEN 'AUTOMATICO' ELSE NULL END) ORIGEN_DSCR,
	CDACTIVIDADES.REGIMEN,
	(CASE  WHEN CDACTIVIDADES.REGIMEN='0' THEN 'EN_SOLITARIO' WHEN  CDACTIVIDADES.REGIMEN='1' THEN 'EN_EQUIPO' ELSE NULL END) REGIMEN_DSCR,
	CDACTIVIDADES.RANURA,
	CDACTIVIDADES.ESTADO_TRJ_RANURA,
	(CASE WHEN CDACTIVIDADES.RANURA='0' THEN 'CONDUCTOR' WHEN CDACTIVIDADES.RANURA='1' THEN 'CONDUCTOR2' ELSE NULL END) RANURA_DSCR,
	(CASE WHEN CDACTIVIDADES.ESTADO_TRJ_RANURA='0' THEN 'INSERTADA' WHEN CDACTIVIDADES.ESTADO_TRJ_RANURA ='1' THEN 'NO_INSERTADA' ELSE NULL END) ESTADO_TRJ_RANURA_DSCR
FROM 
	CDACTIVIDADES ,
	CDTIPO_ACTIVIDAD, 
	CDVEMPRE_REQ_REALES,
   (
	SELECT 
		CDCONDUCTORES_EMP.IDCONDUCTOR, 
		CDCONDUCTOR_CONT.CG_CONTRATO
	FROM   
		CDCONDUCTOR_CONT, 
		CDCONDUCTORES_EMP, 
		CDVEMPRE_REQ_REALES
	WHERE  
		CDCONDUCTOR_CONT.IDCONDUCTOR  = CDCONDUCTORES_EMP.IDCONDUCTOR
		AND  CDCONDUCTORES_EMP.CIF = CDVEMPRE_REQ_REALES.CIF
		AND  CDVEMPRE_REQ_REALES.NUMREQ    = CDCONDUCTOR_CONT.CG_CONTRATO
	) DATOSCOND
WHERE 
	CDTIPO_ACTIVIDAD.TPACTIVIDAD       = CDACTIVIDADES.TPACTIVIDAD
	AND CDACTIVIDADES.NUMREQ      = CDVEMPRE_REQ_REALES.NUMREQ
	AND CDACTIVIDADES.IDCONDUCTOR = DATOSCOND.IDCONDUCTOR(+)
	AND CDACTIVIDADES.NUMREQ      = DATOSCOND.CG_CONTRATO(+)
	AND  CDACTIVIDADES.IDCONDUCTOR != 'XXXXXXXXX'
	AND DATOSCOND.IDCONDUCTOR IS NULL
	AND DATOSCOND.CG_CONTRATO IS NULL;



  CREATE OR REPLACE  VIEW CDVUSO_TARJETA AS 
  SELECT  CDUSO_TARJETA.NUMREQ,
        CDUSO_TARJETA.NUMREQ AS CG_CONTRATO,
        CDUSO_TARJETA.MATRICULA,
        CDUSO_TARJETA.MATRICULA_PREV,
        CDUSO_TARJETA.IDCONDUCTOR,
        CDUSO_TARJETA.FEC_INS,
        CDUSO_TARJETA.FEC_EXT,
        CDUSO_TARJETA.KM_INS,
        CDUSO_TARJETA.KM_EXT,
        CDUSO_TARJETA.NUM_TRJ_CONDU,
        CDUSO_TARJETA.RANURA,
        CDUSO_TARJETA.USUARIO_ALTA,
        CDUSO_TARJETA.F_ALTA,
        CDUSO_TARJETA.USUARIO_MODIF,
        CDUSO_TARJETA.F_MODIF,
        (CASE WHEN CDUSO_TARJETA.RANURA='0' THEN 'CONDUCTOR' WHEN CDUSO_TARJETA.RANURA='1' THEN 'CONDUCTOR2' ELSE NULL END) RANURA_DSCR,
        CDCONDUCTORES_EMP.NOMBRE,
        CDCONDUCTORES_EMP.APELLIDOS 
FROM CDUSO_TARJETA, CDCONDUCTORES_EMP, CDVEMPRE_REQ_REALES 
WHERE CDUSO_TARJETA.IDCONDUCTOR = CDCONDUCTORES_EMP.IDCONDUCTOR
  AND CDVEMPRE_REQ_REALES.NUMREQ        = CDUSO_TARJETA.NUMREQ
  AND CDCONDUCTORES_EMP.CIF     = CDVEMPRE_REQ_REALES.CIF;
  
  
  
CREATE OR REPLACE VIEW CDVUSO_VEHICULO AS 
  SELECT
	CDVEMPRE_REQ_REALES.FECINID AS INSP_FECINI,
	CDVEMPRE_REQ_REALES.FECFIND AS INSP_FECFIN,
	(CDVEMPRE_REQ_REALES.FECFIND-CDVEMPRE_REQ_REALES.FECINID) AS DIAS,
	CDVEMPRE_REQ_REALES.CIF,
	DFEMP.NOMB,
	CDVEMPRE_REQ_REALES.IDINSPECCION,
    CDUSO_VEHICULO.NUMREQ,
    CDUSO_VEHICULO.NUMREQ AS CG_CONTRATO,
    CDUSO_VEHICULO.MATRICULA,
    CDUSO_VEHICULO.IDCONDUCTOR,
    CDUSO_VEHICULO.FECINI,
    CDUSO_VEHICULO.FECFIN,
    CDUSO_VEHICULO.KM_INI,
    CDUSO_VEHICULO.KM_FIN,
    CDUSO_VEHICULO.PROCEDENCIA,
    CDUSO_VEHICULO.NUM_TRJ_CONDU,
    CDUSO_VEHICULO.NUMDISCO,
    CDUSO_VEHICULO.USUARIO_ALTA,
    CDUSO_VEHICULO.F_ALTA,
    CDUSO_VEHICULO.USUARIO_MODIF,
    CDUSO_VEHICULO.F_MODIF,
    CDUSO_VEHICULO.ORIGEN,
    CDUSO_VEHICULO.DESTINO,
    CDCONDUCTORES_EMP.NOMBRE,
    CDCONDUCTORES_EMP.APELLIDOS,
    (CDUSO_VEHICULO.KM_FIN-CDUSO_VEHICULO.KM_INI) KM_REC,
    (CASE WHEN (CDUSO_VEHICULO.PROCEDENCIA='VU' OR CDUSO_VEHICULO.PROCEDENCIA='TC') THEN 'SI' ELSE 'NO' END) TC_DIG,
    (CASE WHEN(CDUSO_VEHICULO.FECFIN > CDUSO_VEHICULO.FECINI) THEN ((CDUSO_VEHICULO.FECFIN-CDUSO_VEHICULO.FECINI)*24) ELSE 0 END) AS HORAS
FROM CDUSO_VEHICULO, CDVEMPRE_REQ_REALES,  CDCONDUCTORES_EMP, CDCONDUCTOR_CONT, DFEMP 
WHERE CDUSO_VEHICULO.NUMREQ       = CDVEMPRE_REQ_REALES.NUMREQ
  AND CDUSO_VEHICULO.NUMREQ       = CDCONDUCTOR_CONT.CG_CONTRATO
  AND CDUSO_VEHICULO.IDCONDUCTOR  = CDCONDUCTORES_EMP.IDCONDUCTOR
  AND CDVEMPRE_REQ_REALES.CIF		          = CDCONDUCTORES_EMP.CIF AND DFEMP.CIF = CDVEMPRE_REQ_REALES.CIF 
  AND CDCONDUCTOR_CONT.F_BAJA IS NULL
 ;
 
 
 
 
 
 
 ----------------------------------------------------------------
 ----------------------------------------------------------------
 ----------------------------------------------------------------
 ----------------------------------------------------------------
 ----------------------------------------------------------------
  
 
 ALTER TABLE CDEMPRE_REQ ADD DSCR_MODALIDAD_DIGITAL VARCHAR2(100);
 
 

  CREATE OR REPLACE FORCE EDITIONABLE VIEW CDVEMPRE_REQ_REALES AS 
  SELECT  
  CDEMPRE_REQ.NUMREQ,
  CDEMPRE_REQ.CIF,
  DFEMP.NOMB,
  CDEMPRE_REQ.IDINSPECCION,
  CDEMPRE_REQ.F_REQ,
  CDEMPRE_REQ.USUARIO_ALTA,
  CDEMPRE_REQ.F_ALTA,
  CDEMPRE_REQ.F_MODIF,
  CDEMPRE_REQ.USUARIO_MODIF,
  CDEMPRE_REQ.F_BAJA,
  CDEMPRE_REQ.CG_ORGA,
  CDEMPRE_REQ.FECINI AS FECINID,
  CDEMPRE_REQ.FECFIN AS FECFIND,
  CDEMPRE_REQ.AVISO_EXPIRACION,
  CDEMPRE_REQ.CG_CONTRATO,
  CDEMPRE_REQ.F_CONTRATO,
  CDEMPRE_REQ.MAX_COND,
  CDEMPRE_REQ.MAX_VEH,
  DFEMP.FLOTA_AUTOM,
  CDEMPRE_REQ.TERMDATEDEMO,
  CDEMPRE_REQ.ENDDATEDEMO,
  CDEMPRE_REQ.ESTADO,
  CDEMPRE_REQ.DSCR,
  CDEMPRE_REQ.AGENTE,
  CDEMPRE_REQ.ZONA,
  CDEMPRE_REQ.F_RENOVACION,
  CDEMPRE_REQ.ESTADO_VALIDACION,
  CDEMPRE_REQ.IDKIT,
  CDEMPRE_REQ.DSCR_KIT,
  CDEMPRE_REQ.OBSR_KIT,
  CDEMPRE_REQ.MODALIDAD_DIGITAL,
  CDEMPRE_REQ.DSCR_MODALIDAD_DIGITAL,
  CDEMPRE_REQ.Z_FECHA,
  CDEMPRE_REQ.RENOV_CONTRATO,
  CDEMPRE_REQ.RENUEVA,
  CDEMPRE_REQ.Z_ERRORES,
  CDEMPRE_REQ.Z_PROCESADO,
  CDEMPRE_REQ.F_ANULACION,
  CDEMPRE_REQ.U_NUM_MAXIMO,
  CDEMPRE_REQ.FICTICIO
FROM CDEMPRE_REQ, DFEMP WHERE CDEMPRE_REQ.CIF = DFEMP.CIF 
AND FICTICIO = 'N'
UNION ALL
SELECT   
  CDEMPRE_REQ.NUMREQ,
  DFEMP_FIC.CIF,
  DFEMP_FIC.NOMB,
  CDEMPRE_REQ.IDINSPECCION,
  CDEMPRE_REQ.F_REQ,
  CDEMPRE_REQ.USUARIO_ALTA,
  CDEMPRE_REQ.F_ALTA,
  CDEMPRE_REQ.F_MODIF,
  CDEMPRE_REQ.USUARIO_MODIF,
  CDEMPRE_REQ.F_BAJA,
  CDEMPRE_REQ.CG_ORGA,
  CDEMPRE_REQ.FECINI AS FECINID,
  CDEMPRE_REQ.FECFIN AS FECFIND,
  CDEMPRE_REQ.AVISO_EXPIRACION,
  CDEMPRE_REQ.CG_CONTRATO,
  CDEMPRE_REQ.F_CONTRATO,
  CDEMPRE_REQ.MAX_COND,
  CDEMPRE_REQ.MAX_VEH,
  DFEMP_FIC.FLOTA_AUTOM,
  CDEMPRE_REQ.TERMDATEDEMO,
  CDEMPRE_REQ.ENDDATEDEMO,
  CDEMPRE_REQ.ESTADO,
  CDEMPRE_REQ.DSCR,
  CDEMPRE_REQ.AGENTE,
  CDEMPRE_REQ.ZONA,
  CDEMPRE_REQ.F_RENOVACION,
  CDEMPRE_REQ.ESTADO_VALIDACION,
  CDEMPRE_REQ.IDKIT,
  CDEMPRE_REQ.DSCR_KIT,
  CDEMPRE_REQ.OBSR_KIT,
  CDEMPRE_REQ.MODALIDAD_DIGITAL,
  CDEMPRE_REQ.DSCR_MODALIDAD_DIGITAL,
  CDEMPRE_REQ.Z_FECHA,
  CDEMPRE_REQ.RENOV_CONTRATO,
  CDEMPRE_REQ.RENUEVA,
  CDEMPRE_REQ.Z_ERRORES,
  CDEMPRE_REQ.Z_PROCESADO,
  CDEMPRE_REQ.F_ANULACION,
  CDEMPRE_REQ.U_NUM_MAXIMO,
  CDEMPRE_REQ.FICTICIO
  FROM CDEMPRE_REQ, (SELECT DFEMP.CIF, DFEMP.NOMB,CIF_COOPERATIVA, NUMREQ, FLOTA_AUTOM FROM CDEMPRE_REQ, DFEMP WHERE CDEMPRE_REQ.CIF = DFEMP.CIF AND FICTICIO='S')DFEMP_FIC
  WHERE FICTICIO='N'  AND DFEMP_FIC.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND CIF_COOPERATIVA IS NOT NULL AND F_BAJA IS NULL;

  
  
  
  
 CREATE OR REPLACE  VIEW CDVCONTRATO_EMPRESA AS 
  SELECT 
	(case when DFEMP.CONTRATO_COOP='S' then ( SELECT  CDEMPRE_REQ.NUMREQ  FROM DFEMP DF, CDEMPRE_REQ WHERE DF.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND CDEMPRE_REQ.F_BAJA IS NULL AND DFEMP.CIF = DF.CIF) else CDEMPRE_REQ.NUMREQ end) as NUMREQ,
	(case when DFEMP.CONTRATO_COOP='S' then ( SELECT  CDEMPRE_REQ.NUMREQ  FROM DFEMP DF, CDEMPRE_REQ WHERE DF.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND CDEMPRE_REQ.F_BAJA IS NULL AND DFEMP.CIF = DF.CIF) else CDEMPRE_REQ.NUMREQ end) as CG_CONTRATO,	
	CDEMPRE_REQ.F_CONTRATO,
	DFEMP.CIF,
	CDEMPRE_REQ.IDINSPECCION,
	CDEMPRE_REQ.F_REQ,
	CDEMPRE_REQ.USUARIO_ALTA,
	CDEMPRE_REQ.F_ALTA,
	CDEMPRE_REQ.F_ANULACION,
	CDEMPRE_REQ.USUARIO_MODIF,
	CDEMPRE_REQ.F_MODIF,
	CDEMPRE_REQ.F_BAJA,
	DFEMP.NOMB,
	DFEMP.NOMB as NOMB_EMP,
	TO_CHAR(CDEMPRE_REQ.FECINID,'DD/MM/YYYY')||' - '|| TO_CHAR(CDEMPRE_REQ.FECFIND,'DD/MM/YYYY') AS NOMBRECOMPLETO,
	CDEMPRE_REQ.CG_ORGA,
	CDEMPRE_REQ.AVISO_EXPIRACION,
	CDEMPRE_REQ.FECINID AS FECINI,
	CDEMPRE_REQ.FECFIND AS FECFIN,
	CDEMPRE_REQ.MAX_COND,
	CDEMPRE_REQ.MAX_VEH,	
	CDEMPRE_REQ.TERMDATEDEMO,
	CDEMPRE_REQ.ENDDATEDEMO,
	CDEMPRE_REQ.ESTADO,
	CDEMPRE_REQ.DSCR,
	CDEMPRE_REQ.AGENTE,
	CDEMPRE_REQ.ZONA,
	CDEMPRE_REQ.F_RENOVACION,
	CDEMPRE_REQ.ESTADO_VALIDACION,
	CDEMPRE_REQ.IDKIT,
	CDEMPRE_REQ.DSCR_KIT,
	CDEMPRE_REQ.OBSR_KIT,
	CDEMPRE_REQ.MODALIDAD_DIGITAL,
	CDEMPRE_REQ.Z_FECHA,
	CDEMPRE_REQ.RENOV_CONTRATO,
	CDEMPRE_REQ.RENUEVA,
	CDEMPRE_REQ.Z_ERRORES,
	CDEMPRE_REQ.Z_PROCESADO,
	DFEMP.FLOTA_AUTOM,
	CDEMPRE_REQ.FICTICIO,
	CDEMPRE_REQ.U_NUM_MAXIMO,
	CDEMPRE_REQ.DSCR_MODALIDAD_DIGITAL
FROM 	
	DFEMP,
	cdvempre_req_reales CDEMPRE_REQ
WHERE 
	DFEMP.CIF = CDEMPRE_REQ.CIF AND
	CDEMPRE_REQ.F_BAJA IS NULL 
UNION ALL
select 
	CDEMPRE_REQ.NUMREQ,
	CDEMPRE_REQ.CG_CONTRATO,
	CDEMPRE_REQ.F_CONTRATO,
	CDEMPRE_REQ.CIF,
	CDEMPRE_REQ.IDINSPECCION,
	CDEMPRE_REQ.F_REQ,
	CDEMPRE_REQ.USUARIO_ALTA,
	CDEMPRE_REQ.F_ALTA,
	CDEMPRE_REQ.F_ANULACION,
	CDEMPRE_REQ.USUARIO_MODIF,
	CDEMPRE_REQ.F_MODIF,
	CDEMPRE_REQ.F_BAJA,
	DFEMP.NOMB,
	DFEMP.NOMB as NOMB_EMP,	
	TO_CHAR(CDEMPRE_REQ.FECINI,'DD/MM/YYYY')||' - '|| TO_CHAR(CDEMPRE_REQ.FECFIN,'DD/MM/YYYY') AS NOMBRECOMPLETO,
	CDEMPRE_REQ.CG_ORGA,
	CDEMPRE_REQ.AVISO_EXPIRACION,
	CDEMPRE_REQ.FECINI,
	CDEMPRE_REQ.FECFIN,
	CDEMPRE_REQ.MAX_COND,
	CDEMPRE_REQ.MAX_VEH,	
	CDEMPRE_REQ.TERMDATEDEMO,
	CDEMPRE_REQ.ENDDATEDEMO,
	CDEMPRE_REQ.ESTADO,
	CDEMPRE_REQ.DSCR,
	CDEMPRE_REQ.AGENTE,
	CDEMPRE_REQ.ZONA,
	CDEMPRE_REQ.F_RENOVACION,
	CDEMPRE_REQ.ESTADO_VALIDACION,
	CDEMPRE_REQ.IDKIT,
	CDEMPRE_REQ.DSCR_KIT,
	CDEMPRE_REQ.OBSR_KIT,
	CDEMPRE_REQ.MODALIDAD_DIGITAL,
	CDEMPRE_REQ.Z_FECHA,
	CDEMPRE_REQ.RENOV_CONTRATO,
	CDEMPRE_REQ.RENUEVA,
	CDEMPRE_REQ.Z_ERRORES,
	CDEMPRE_REQ.Z_PROCESADO,
	DFEMP.FLOTA_AUTOM,
	CDEMPRE_REQ.FICTICIO,
	CDEMPRE_REQ.U_NUM_MAXIMO,
	CDEMPRE_REQ.DSCR_MODALIDAD_DIGITAL
from 
	CDEMPRE_REQ, 
	DFEMP
where
	CDEMPRE_REQ.CIF = DFEMP.CIF AND 
	CDEMPRE_REQ.F_BAJA IS NOT NULL AND
	(CONTRATO_COOP IS NULL OR CONTRATO_COOP = 'N')
 ;

  
  