CREATE OR REPLACE VIEW CDVINFORM_PENDDESCARGA AS 
  SELECT 
		CG_CONTRATO,
		CIF,
		EMP,                  
		TELF,
		FAX,
		EMAIL,
		MOVIL, 
		IDORIGEN,
		DSCR,
		TIPO,		
		(case when MAX_FFIN is null then max_f_descarga_datos when max_f_descarga_datos is null then MAX_FFIN else GREATEST (MAX_FFIN,MAX_F_DESCARGA_DATOS) end) as F_DESCARGA_DATOS,
		TRUNC(SYSDATE-(case when MAX_FFIN is null then max_f_descarga_datos when max_f_descarga_datos is null then MAX_FFIN else GREATEST (MAX_FFIN,MAX_F_DESCARGA_DATOS) end)) AS DIAS,
		IDDELEGACION
	FROM
		(
		SELECT 
			CDVEHICULO_CONT.MATRICULA AS IDORIGEN,
			CDVEHICULOS_EMP.DSCR,
			CDVEHICULO_CONT.CG_CONTRATO,
			CDVEHICULOS_EMP.CIF          AS CIF,
			0 AS TIPO,
			DFEMP.NOMB               AS EMP,            
			DFEMP.TELF               AS TELF,
			DFEMP.FAX               AS FAX,
			DFEMP.EMAIL               AS EMAIL,
			DFEMP.MOVIL               AS MOVIL, 
			IDDELEGACION,
			(SELECT 
				MAX(CDFICHEROS.FECFIN) 
			FROM 
				CDFICHEROS,CDFICHEROS_CONTRATO 
			WHERE 
				CDFICHEROS.IDFICHERO   = CDFICHEROS_CONTRATO.IDFICHERO
				AND CDVEHICULO_CONT.CG_CONTRATO = CDFICHEROS_CONTRATO.CG_CONTRATO
				AND CDVEHICULO_CONT.MATRICULA = CDFICHEROS.IDORIGEN
				AND CDFICHEROS.TIPO = 'VU') as MAX_FFIN,
			(SELECT 
				MAX(CDFICHEROS.F_DESCARGA_DATOS) 
			FROM 
				CDFICHEROS,CDFICHEROS_CONTRATO 
			WHERE 
				CDFICHEROS.IDFICHERO   = CDFICHEROS_CONTRATO.IDFICHERO
				AND CDVEHICULO_CONT.CG_CONTRATO = CDFICHEROS_CONTRATO.CG_CONTRATO
				AND CDVEHICULO_CONT.MATRICULA = CDFICHEROS.IDORIGEN
				AND CDFICHEROS.TIPO = 'VU') as MAX_F_DESCARGA_DATOS	
		FROM 
			CDVEHICULO_CONT,
			CDVEHICULOS_EMP,
			CDVEMPRE_REQ_REALES,
			DFEMP
		WHERE 
			CDVEHICULO_CONT.F_BAJA  IS NULL
			AND CDVEHICULO_CONT.MATRICULA  =CDVEHICULOS_EMP.MATRICULA
			AND CDVEHICULO_CONT.CG_CONTRATO=CDVEMPRE_REQ_REALES.NUMREQ
			AND CDVEMPRE_REQ_REALES.CIF            = CDVEHICULOS_EMP.CIF
			AND CDVEMPRE_REQ_REALES.CIF             = DFEMP.CIF
			AND CDVEHICULOS_EMP.DURMIENTE  = 'N'
			AND CDVEMPRE_REQ_REALES.F_BAJA         IS NULL
			
		UNION ALL
		
		SELECT 
			CDCONDUCTORES_EMP.IDCONDUCTOR AS IDORIGEN,
			CDCONDUCTORES_EMP.APELLIDOS || ', ' || CDCONDUCTORES_EMP.NOMBRE AS DSCR,
			CDCONDUCTOR_CONT.CG_CONTRATO,
			CDCONDUCTORES_EMP.CIF,
			1 AS TIPO,
			DFEMP.NOMB               AS EMP,            
			DFEMP.TELF               AS TELF,
			DFEMP.FAX               AS FAX,
			DFEMP.EMAIL               AS EMAIL,
			DFEMP.MOVIL               AS MOVIL, 
			IDDELEGACION,						
			(SELECT 
				MAX(CDFICHEROS.FECFIN) 
			FROM 
				CDFICHEROS,CDFICHEROS_CONTRATO 
			WHERE 
				CDFICHEROS.IDFICHERO   = CDFICHEROS_CONTRATO.IDFICHERO
				AND CDCONDUCTOR_CONT.CG_CONTRATO = CDFICHEROS_CONTRATO.CG_CONTRATO
				AND CDCONDUCTORES_EMP.IDCONDUCTOR = CDFICHEROS.IDORIGEN
				AND CDFICHEROS.TIPO = 'TC') as MAX_FFIN,
			(SELECT 
				MAX(CDFICHEROS.F_DESCARGA_DATOS) 
			FROM 
				CDFICHEROS,CDFICHEROS_CONTRATO 
			WHERE 
				CDFICHEROS.IDFICHERO   = CDFICHEROS_CONTRATO.IDFICHERO
				AND CDCONDUCTOR_CONT.CG_CONTRATO = CDFICHEROS_CONTRATO.CG_CONTRATO
				AND CDCONDUCTORES_EMP.IDCONDUCTOR = CDFICHEROS.IDORIGEN
				AND CDFICHEROS.TIPO = 'TC') as MAX_F_DESCARGA_DATOS					
		FROM 
			CDCONDUCTOR_CONT,
			CDCONDUCTORES_EMP,
			CDVEMPRE_REQ_REALES,
			DFEMP
		WHERE 
			CDCONDUCTOR_CONT.F_BAJA  IS NULL
			AND CDCONDUCTOR_CONT.DNI        =CDCONDUCTORES_EMP.DNI
			AND CDCONDUCTOR_CONT.CG_CONTRATO=CDVEMPRE_REQ_REALES.NUMREQ
			AND CDVEMPRE_REQ_REALES.CIF             = CDCONDUCTORES_EMP.CIF
			AND CDVEMPRE_REQ_REALES.CIF             = DFEMP.CIF
			AND CDCONDUCTORES_EMP.DURMIENTE = 'N'
			AND CDVEMPRE_REQ_REALES.F_BAJA         IS NULL						
		) VDATOS_DESCARGAS
	WHERE 
		((case when MAX_FFIN is null then max_f_descarga_datos when max_f_descarga_datos is null then MAX_FFIN else GREATEST (MAX_FFIN,MAX_F_DESCARGA_DATOS) end) < ( SYSDATE - (CASE WHEN (TIPO=1)	THEN 28	ELSE 90  END))
		OR (case when MAX_FFIN is null then max_f_descarga_datos when max_f_descarga_datos is null then MAX_FFIN else GREATEST (MAX_FFIN,MAX_F_DESCARGA_DATOS) end) IS NULL)
/
CREATE OR REPLACE VIEW CDVINFORM_EVENTOS_TACO AS 
  SELECT A.CG_CONTRATO,A.GRUPO,A.FECINI,A.FECFIN,A.MATRICULA,A.DSCR,
A.VMAX,
A.VMED,
A.NUM_TRJ_CONTROL,
A.TPCONTROL,
A.NUM_TRJ_TALLER,
A.TPCALIBRADO,
A.V1,
A.V2,
DFEMP.CIF,
DFEMP.NOMB AS EMP, CDVVEHICULO_CONT.IDDELEGACION
FROM
(
SELECT
   CDINCIDENTES.NUMREQ AS CG_CONTRATO,
	 'EXCESOS_VELOCIDAD' AS GRUPO,
	 FECINI AS FECINI,
	 FECFIN AS FECFIN,
	 MATRICULA,
	 NULL AS DSCR,
	 TO_CHAR(VMAX) AS VMAX,
	 TO_CHAR(VMED) AS VMED,
         NULL AS NUM_TRJ_CONTROL,
         NULL AS TPCONTROL,
         NULL AS NUM_TRJ_TALLER,
         NULL AS TPCALIBRADO,
         TO_CHAR(VMAX) AS V1,
         TO_CHAR(VMED) AS V2
	FROM CDINCIDENTES
	WHERE TIPO=7
UNION
	SELECT
	  CDCONTROLES.NUMREQ AS CG_CONTRATO,
	  'CONTROLES' AS GRUPO,
	  FEC_HORA AS FECINI,
	  FEC_HORA AS FECFIN,
	  MATRICULA ,
	  CDTIPO_CONTROL.DSCR AS DSCR,
          NULL AS VMAX,
          NULL AS VMED,
	  NUM_TRJ_CONTROL,
	  CDTIPO_CONTROL.DSCR AS TPCONTROL,
          NULL AS NUM_TRJ_TALLER,
         NULL AS TPCALIBRADO,
         NUM_TRJ_CONTROL AS V1,
         CDTIPO_CONTROL.DSCR  AS V2
	FROM CDCONTROLES,CDTIPO_CONTROL
	  WHERE CDCONTROLES.TPCONTROL=CDTIPO_CONTROL.TPCONTROL(+)
UNION
	SELECT
	  CDCALIBRADO.NUMREQ AS CG_CONTRATO,
	  'CALIBRADOS' AS GRUPO,
	  FEC_PROXIMO AS FECINI,
	  FEC_PROXIMO AS FECFIN,
	  MATRICULA,
	  CDTIPO_CALIBRADO.DSCR AS DSCR,
          NULL AS VMAX,
          NULL AS VMED,
          NULL AS NUM_TRJ_CONTROL,
          NULL AS TPCONTROL,
	  NUM_TRJ_TALLER,
	  CDTIPO_CALIBRADO.DSCR AS TPCALIBRADO,
         NUM_TRJ_TALLER AS V1,
         CDTIPO_CALIBRADO.DSCR AS V2
	FROM CDCALIBRADO,CDTIPO_CALIBRADO
	WHERE CDCALIBRADO.TPCALIBRADO=CDTIPO_CALIBRADO.TPCALIBRADO(+)
	)A,CDVEMPRE_REQ_REALES,DFEMP, CDVVEHICULO_CONT
WHERE A.CG_CONTRATO = CDVEMPRE_REQ_REALES.NUMREQ
  AND A.CG_CONTRATO = CDVVEHICULO_CONT.CG_CONTRATO
  AND A.MATRICULA   = CDVVEHICULO_CONT.MATRICULA
  AND CDVEMPRE_REQ_REALES.F_BAJA IS NULL
  AND CDVEMPRE_REQ_REALES.CIF=DFEMP.CIF(+)
/
CREATE OR REPLACE VIEW CDVPROX_CALIBRADO AS 
  SELECT 
(CASE WHEN (MAX(CDCALIBRADO.FEC_PROXIMO)) IS NULL THEN 'NO HAY DATOS' ELSE 
(CASE WHEN (MAX(CDCALIBRADO.FEC_PROXIMO)) < SYSDATE THEN 'NO SE HA PASADO'  ELSE 
 TO_CHAR(MAX(CDCALIBRADO.FEC_PROXIMO),'DD/MM/YYYY') END) END)  AS FEC_PROXIMO, 
 MAX(CDCALIBRADO.FEC_PROXIMO) AS FEC_PROXIMO_DATE,
A.NUMREQ,
A.NUMREQ AS CG_CONTRATO,
A.MATRICULA,
A.DSCR,
A.CIF,
A.NOMBRE_EMPRESA      
FROM (
SELECT	
	CDVEMPRE_REQ_REALES.NUMREQ,
        CDVEMPRE_REQ_REALES.NUMREQ AS CG_CONTRATO,
	CDVEHICULO_CONT.MATRICULA,
        CDVEHICULOS_EMP.DSCR,
        DFEMP.CIF,
        DFEMP.NOMB AS NOMBRE_EMPRESA      
FROM CDVEHICULOS_EMP,CDVEHICULO_CONT, DFEMP, CDVEMPRE_REQ_REALES
WHERE 
CDVEHICULO_CONT.MATRICULA = CDVEHICULOS_EMP.MATRICULA AND
CDVEHICULO_CONT.CG_CONTRATO = CDVEMPRE_REQ_REALES.NUMREQ AND
CDVEHICULOS_EMP.CIF = CDVEMPRE_REQ_REALES.CIF AND
CDVEMPRE_REQ_REALES.CIF = DFEMP.CIF 
ORDER BY MATRICULA ) A,
 CDCALIBRADO
WHERE 
A.MATRICULA = CDCALIBRADO.MATRICULA(+) AND
A.NUMREQ = CDCALIBRADO.NUMREQ(+)      
GROUP BY A.NUMREQ,
	A.MATRICULA,
        A.DSCR, 
        A.CIF,
        A.NOMBRE_EMPRESA 
ORDER BY A.MATRICULA
/
 
