ALTER TABLE CDEMPRE_REQ ADD ESTADO VARCHAR2(1)
/
ALTER TABLE CDEMPRE_REQ ADD DSCR VARCHAR2(254)
/
ALTER TABLE CDEMPRE_REQ ADD AGENTE NUMBER(6,0) DEFAULT 0
/
ALTER TABLE CDEMPRE_REQ ADD ZONA NUMBER(6,0) DEFAULT 0
/
ALTER TABLE CDEMPRE_REQ ADD F_RENOVACION DATE
/
ALTER TABLE CDEMPRE_REQ ADD ESTADO_VALIDACION VARCHAR2(1)
/
ALTER TABLE CDEMPRE_REQ ADD IDKIT VARCHAR2(30)
/
ALTER TABLE CDEMPRE_REQ ADD DSCR_KIT VARCHAR2(150)
/
ALTER TABLE CDEMPRE_REQ ADD OBSR_KIT VARCHAR2(254)
/
ALTER TABLE CDEMPRE_REQ ADD MODALIDAD_DIGITAL VARCHAR2(30)
/
ALTER TABLE CDEMPRE_REQ ADD RENUEVA NUMBER(11,0) NOT NULL DEFAULT 0
/
ALTER TABLE CDEMPRE_REQ ADD RENOV_CONTRATO NUMBER(11,0) NOT NULL DEFAULT 0
/
ALTER TABLE CDEMPRE_REQ ADD U_NUM_MAXIMO NUMBER (6,0)
/
ALTER TABLE CDEMPRE_REQ ADD Z_PROCESADO VARCHAR2(1)
/
ALTER TABLE CDEMPRE_REQ ADD Z_ERRORES VARCHAR2(254)
/
ALTER TABLE CDEMPRE_REQ ADD Z_FECHA DATE
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN TP_EMPRESA
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN COD_AGENTE
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN AMBITO
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN REGULAR
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN F_CARGADATOS
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN F_ANALISIS
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN F_ANULACION
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN ACTIVIDAD
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN NUM_COPIAS
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN NIF_INSPEC
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN NOMB
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN GRUPO
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN AREA
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN PROCEDENCIA
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN CG_RENOVACION
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN TIPO
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN ITEMCODE
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN U_CODE_CARGADOR
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN SITCONTRACT
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN ENTREPRISE_CODE
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN STATUS
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN U_CODE_COMERCIAL
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN U_CODE_AGENTE
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN U_CODE_FACTURACION
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN U_CODE_PAGO
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN REMARKS2
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN U_NUM_MAXIMO
/
ALTER TABLE CDEMPRE_REQ DROP COLUMN U_CUOTA
/
CREATE OR REPLACE FORCE VIEW CDVEMPRE_REQ_REALES AS 
  SELECT  
  CDEMPRE_REQ.NUMREQ,
  CDEMPRE_REQ.CIF,
  DFEMP.NOMB,
  CDEMPRE_REQ.IDINSPECCION,
  CDEMPRE_REQ.F_REQ,
  CDEMPRE_REQ.USUARIO_ALTA,
  CDEMPRE_REQ.F_ALTA,
  CDEMPRE_REQ.F_MODIF,
  CDEMPRE_REQ.USUARIO_MODIF,
  CDEMPRE_REQ.F_BAJA,
  CDEMPRE_REQ.CG_ORGA,
  CDEMPRE_REQ.FECINI AS FECINID,
  CDEMPRE_REQ.FECFIN AS FECFIND,
  CDEMPRE_REQ.AVISO_EXPIRACION,
  CDEMPRE_REQ.CG_CONTRATO,
  CDEMPRE_REQ.F_CONTRATO,
  CDEMPRE_REQ.MAX_COND,
  CDEMPRE_REQ.MAX_VEH,
  CDEMPRE_REQ.FLOTA_AUTOM,
  CDEMPRE_REQ.TERMDATEDEMO,
  CDEMPRE_REQ.ENDDATEDEMO,
  CDEMPRE_REQ.ESTADO,
  CDEMPRE_REQ.DSCR,
  CDEMPRE_REQ.AGENTE,
  CDEMPRE_REQ.ZONA,
  CDEMPRE_REQ.F_RENOVACION,
  CDEMPRE_REQ.ESTADO_VALIDACION,
  CDEMPRE_REQ.IDKIT,
  CDEMPRE_REQ.DSCR_KIT,
  CDEMPRE_REQ.OBSR_KIT,
  CDEMPRE_REQ.MODALIDAD_DIGITAL,
  CDEMPRE_REQ.Z_FECHA,
  CDEMPRE_REQ.RENOV_CONTRATO,
  CDEMPRE_REQ.RENUEVA,
  CDEMPRE_REQ.Z_ERRORES,
  CDEMPRE_REQ.Z_PROCESADO,
  CDEMPRE_REQ.F_ANULACION
FROM CDEMPRE_REQ, DFEMP WHERE CDEMPRE_REQ.CIF = DFEMP.CIF 
AND FICTICIO = 'N'
UNION ALL
SELECT   
  CDEMPRE_REQ.NUMREQ,
  DFEMP_FIC.CIF,
  DFEMP_FIC.NOMB,
  CDEMPRE_REQ.IDINSPECCION,
  CDEMPRE_REQ.F_REQ,
  CDEMPRE_REQ.USUARIO_ALTA,
  CDEMPRE_REQ.F_ALTA,
  CDEMPRE_REQ.F_MODIF,
  CDEMPRE_REQ.USUARIO_MODIF,
  CDEMPRE_REQ.F_BAJA,
  CDEMPRE_REQ.CG_ORGA,
  CDEMPRE_REQ.FECINI AS FECINID,
  CDEMPRE_REQ.FECFIN AS FECFIND,
  CDEMPRE_REQ.AVISO_EXPIRACION,
  CDEMPRE_REQ.CG_CONTRATO,
  CDEMPRE_REQ.F_CONTRATO,
  CDEMPRE_REQ.MAX_COND,
  CDEMPRE_REQ.MAX_VEH,
  CDEMPRE_REQ.FLOTA_AUTOM,
  CDEMPRE_REQ.TERMDATEDEMO,
  CDEMPRE_REQ.ENDDATEDEMO,
  CDEMPRE_REQ.ESTADO,
  CDEMPRE_REQ.DSCR,
  CDEMPRE_REQ.AGENTE,
  CDEMPRE_REQ.ZONA,
  CDEMPRE_REQ.F_RENOVACION,
  CDEMPRE_REQ.ESTADO_VALIDACION,
  CDEMPRE_REQ.IDKIT,
  CDEMPRE_REQ.DSCR_KIT,
  CDEMPRE_REQ.OBSR_KIT,
  CDEMPRE_REQ.MODALIDAD_DIGITAL,
  CDEMPRE_REQ.Z_FECHA,
  CDEMPRE_REQ.RENOV_CONTRATO,
  CDEMPRE_REQ.RENUEVA,
  CDEMPRE_REQ.Z_ERRORES,
  CDEMPRE_REQ.Z_PROCESADO,
  CDEMPRE_REQ.F_ANULACION
  FROM CDEMPRE_REQ, (SELECT DFEMP.CIF, DFEMP.NOMB,CIF_COOPERATIVA, NUMREQ FROM CDEMPRE_REQ, DFEMP WHERE CDEMPRE_REQ.CIF = DFEMP.CIF AND FICTICIO='S')DFEMP_FIC
  WHERE FICTICIO='N'  AND DFEMP_FIC.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND CIF_COOPERATIVA IS NOT NULL AND F_BAJA IS NULL
/ 
CREATE OR REPLACE FORCE VIEW CDVACTIVIDADES AS 
  SELECT	
	CDACTIVIDADES.NUMREQ,
	CDACTIVIDADES.IDCONDUCTOR,
	CDACTIVIDADES.TPACTIVIDAD,
	CDACTIVIDADES.FEC_COMIENZO,
	CDACTIVIDADES.FEC_FIN,
	CDACTIVIDADES.MINUTOS,
	CDACTIVIDADES.TRANS_TREN,
	CDACTIVIDADES.FUERA_AMBITO,
	CDACTIVIDADES.PROCEDENCIA,
	CDACTIVIDADES.MATRICULA,
	CDACTIVIDADES.USUARIO_ALTA,
	CDACTIVIDADES.F_ALTA,
	CDACTIVIDADES.USUARIO_MODIF,
	CDACTIVIDADES.F_MODIF,
  CDTIPO_ACTIVIDAD.DSCR AS DSCR_ACT,
  CDACTIVIDADES.ORIGEN,
  (CASE WHEN CDACTIVIDADES.ORIGEN='M' THEN 'MANUAL' WHEN  CDACTIVIDADES.ORIGEN='A' THEN 'AUTOMATICO' ELSE NULL END) ORIGEN_DSCR,
 	CDACTIVIDADES.REGIMEN,
  (CASE  WHEN CDACTIVIDADES.REGIMEN='0' THEN 'EN_SOLITARIO' WHEN  CDACTIVIDADES.REGIMEN='1' THEN 'EN_EQUIPO' ELSE NULL END) REGIMEN_DSCR,
 	CDACTIVIDADES.RANURA,
  CDACTIVIDADES.ESTADO_TRJ_RANURA,
  (CASE WHEN CDACTIVIDADES.RANURA='0' THEN 'CONDUCTOR' WHEN CDACTIVIDADES.RANURA='1' THEN 'CONDUCTOR2' ELSE NULL END) RANURA_DSCR,
	(CASE WHEN CDACTIVIDADES.ESTADO_TRJ_RANURA='0' THEN 'INSERTADA' WHEN CDACTIVIDADES.ESTADO_TRJ_RANURA ='1' THEN 'NO_INSERTADA' ELSE NULL END) ESTADO_TRJ_RANURA_DSCR, 
	CDCONDUCTORES_EMP.NOMBRE,
	CDCONDUCTORES_EMP.APELLIDOS,
	CDEMPRE_REQ.CIF,
	DFEMP.NOMB,
	CDEMPRE_REQ.IDINSPECCION,
	CDEMPRE_REQ.FECINI AS INSP_FECINI,
	CDEMPRE_REQ.FECFIN AS INSP_FECFIN
FROM
    CDACTIVIDADES, CDTIPO_ACTIVIDAD, CDCONDUCTOR_CONT, CDCONDUCTORES_EMP, CDEMPRE_REQ, DFEMP 
WHERE CDACTIVIDADES.TPACTIVIDAD = CDTIPO_ACTIVIDAD.TPACTIVIDAD
  AND ((CDACTIVIDADES.NUMREQ 		= CDCONDUCTOR_CONT.CG_CONTRATO
  AND CDACTIVIDADES.IDCONDUCTOR = CDCONDUCTORES_EMP.IDCONDUCTOR 
  AND CDCONDUCTOR_CONT.CG_CONTRATO   = CDEMPRE_REQ.NUMREQ
  AND CDEMPRE_REQ.CIF 		           = CDCONDUCTORES_EMP.CIF
  AND CDCONDUCTOR_CONT.DNI      = CDCONDUCTORES_EMP.DNI
  AND CDCONDUCTOR_CONT.F_BAJA IS NULL)) 
  AND CDEMPRE_REQ.NUMREQ        = CDACTIVIDADES.NUMREQ 
  AND DFEMP.CIF = CDEMPRE_REQ.CIF
/ 
CREATE OR REPLACE FORCE VIEW CDVEMPRE_REQ AS 
  SELECT 
  CDEMPRE_REQ.NUMREQ,
  DFEMP.CIF,
  CDEMPRE_REQ.IDINSPECCION,
  CDEMPRE_REQ.F_REQ,
  CDEMPRE_REQ.USUARIO_ALTA,
  CDEMPRE_REQ.F_ALTA,
  CDEMPRE_REQ.F_MODIF,
  CDEMPRE_REQ.USUARIO_MODIF,
  CDEMPRE_REQ.F_BAJA,
  CDEMPRE_REQ.CG_ORGA,
  CDEMPRE_REQ.FECINI AS FECINID,
  CDEMPRE_REQ.FECFIN AS FECFIND,
  CDEMPRE_REQ.AVISO_EXPIRACION, 
  CDEMPRE_REQ.CG_CONTRATO,
  CDEMPRE_REQ.F_CONTRATO,
  CDEMPRE_REQ.MAX_COND,
  CDEMPRE_REQ.MAX_VEH,
  CDEMPRE_REQ.FLOTA_AUTOM,
  CDEMPRE_REQ.FICTICIO,
  CDEMPRE_REQ.TERMDATEDEMO,
  CDEMPRE_REQ.ENDDATEDEMO,
  CDEMPRE_REQ.ESTADO,
  CDEMPRE_REQ.DSCR,
  CDEMPRE_REQ.AGENTE,
  CDEMPRE_REQ.ZONA,
  CDEMPRE_REQ.F_RENOVACION,
  CDEMPRE_REQ.ESTADO_VALIDACION,
  CDEMPRE_REQ.IDKIT,
  CDEMPRE_REQ.DSCR_KIT,
  CDEMPRE_REQ.OBSR_KIT,
  CDEMPRE_REQ.MODALIDAD_DIGITAL,
  CDEMPRE_REQ.Z_FECHA,
  CDEMPRE_REQ.RENOV_CONTRATO,
  CDEMPRE_REQ.RENUEVA,
  CDEMPRE_REQ.Z_ERRORES,
  CDEMPRE_REQ.Z_PROCESADO,
  CDEMPRE_REQ.F_ANULACION
FROM 
 DFEMP, CDEMPRE_REQ
WHERE 
DFEMP.CIF = CDEMPRE_REQ.CIF AND F_BAJA IS NULL
/ 
CREATE OR REPLACE FORCE VIEW CDVCONTRATO_EMPRESA AS 
  SELECT 
	(case when DFEMP.CONTRATO_COOP='S' then ( SELECT  CDEMPRE_REQ.NUMREQ  FROM DFEMP DF, CDEMPRE_REQ WHERE DF.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND CDEMPRE_REQ.F_BAJA IS NULL AND DFEMP.CIF = DF.CIF) else CDEMPRE_REQ.NUMREQ end) as NUMREQ,
	(case when DFEMP.CONTRATO_COOP='S' then ( SELECT  CDEMPRE_REQ.NUMREQ  FROM DFEMP DF, CDEMPRE_REQ WHERE DF.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND CDEMPRE_REQ.F_BAJA IS NULL AND DFEMP.CIF = DF.CIF) else CDEMPRE_REQ.NUMREQ end) as CG_CONTRATO,	
	CDEMPRE_REQ.F_CONTRATO,
	DFEMP.CIF,
	CDEMPRE_REQ.IDINSPECCION,
	CDEMPRE_REQ.F_REQ,
	CDEMPRE_REQ.USUARIO_ALTA,
	CDEMPRE_REQ.F_ALTA,
	CDEMPRE_REQ.F_ANULACION,
	CDEMPRE_REQ.USUARIO_MODIF,
	CDEMPRE_REQ.F_MODIF,
	CDEMPRE_REQ.F_BAJA,
	DFEMP.NOMB,
	DFEMP.NOMB as NOMB_EMP,
	TO_CHAR(CDEMPRE_REQ.FECINID,'DD/MM/YYYY')||' - '|| TO_CHAR(CDEMPRE_REQ.FECFIND,'DD/MM/YYYY') AS NOMBRECOMPLETO,
	CDEMPRE_REQ.CG_ORGA,
	CDEMPRE_REQ.AVISO_EXPIRACION,
	CDEMPRE_REQ.FECINID AS FECINI,
	CDEMPRE_REQ.FECFIND AS FECFIN,
	CDEMPRE_REQ.MAX_COND,
	CDEMPRE_REQ.MAX_VEH,	
	CDEMPRE_REQ.TERMDATEDEMO,
	CDEMPRE_REQ.ENDDATEDEMO,
	CDEMPRE_REQ.ESTADO,
	CDEMPRE_REQ.DSCR,
	CDEMPRE_REQ.AGENTE,
	CDEMPRE_REQ.ZONA,
	CDEMPRE_REQ.F_RENOVACION,
	CDEMPRE_REQ.ESTADO_VALIDACION,
	CDEMPRE_REQ.IDKIT,
	CDEMPRE_REQ.DSCR_KIT,
	CDEMPRE_REQ.OBSR_KIT,
	CDEMPRE_REQ.MODALIDAD_DIGITAL,
	CDEMPRE_REQ.Z_FECHA,
	CDEMPRE_REQ.RENOV_CONTRATO,
	CDEMPRE_REQ.RENUEVA,
	CDEMPRE_REQ.Z_ERRORES,
	CDEMPRE_REQ.Z_PROCESADO,
	DFEMP.FLOTA_AUTOM
FROM 	
	DFEMP,
	cdvempre_req_reales CDEMPRE_REQ
WHERE 
	DFEMP.CIF = CDEMPRE_REQ.CIF AND
	CDEMPRE_REQ.F_BAJA IS NULL 
UNION ALL
select 
	CDEMPRE_REQ.NUMREQ,
	CDEMPRE_REQ.CG_CONTRATO,
	CDEMPRE_REQ.F_CONTRATO,
	CDEMPRE_REQ.CIF,
	CDEMPRE_REQ.IDINSPECCION,
	CDEMPRE_REQ.F_REQ,
	CDEMPRE_REQ.USUARIO_ALTA,
	CDEMPRE_REQ.F_ALTA,
	CDEMPRE_REQ.F_ANULACION,
	CDEMPRE_REQ.USUARIO_MODIF,
	CDEMPRE_REQ.F_MODIF,
	CDEMPRE_REQ.F_BAJA,
	DFEMP.NOMB,
	DFEMP.NOMB as NOMB_EMP,	
	TO_CHAR(CDEMPRE_REQ.FECINI,'DD/MM/YYYY')||' - '|| TO_CHAR(CDEMPRE_REQ.FECFIN,'DD/MM/YYYY') AS NOMBRECOMPLETO,
	CDEMPRE_REQ.CG_ORGA,
	CDEMPRE_REQ.AVISO_EXPIRACION,
	CDEMPRE_REQ.FECINI,
	CDEMPRE_REQ.FECFIN,
	CDEMPRE_REQ.MAX_COND,
	CDEMPRE_REQ.MAX_VEH,	
	CDEMPRE_REQ.TERMDATEDEMO,
	CDEMPRE_REQ.ENDDATEDEMO,
	CDEMPRE_REQ.ESTADO,
	CDEMPRE_REQ.DSCR,
	CDEMPRE_REQ.AGENTE,
	CDEMPRE_REQ.ZONA,
	CDEMPRE_REQ.F_RENOVACION,
	CDEMPRE_REQ.ESTADO_VALIDACION,
	CDEMPRE_REQ.IDKIT,
	CDEMPRE_REQ.DSCR_KIT,
	CDEMPRE_REQ.OBSR_KIT,
	CDEMPRE_REQ.MODALIDAD_DIGITAL,
	CDEMPRE_REQ.Z_FECHA,
	CDEMPRE_REQ.RENOV_CONTRATO,
	CDEMPRE_REQ.RENUEVA,
	CDEMPRE_REQ.Z_ERRORES,
	CDEMPRE_REQ.Z_PROCESADO,
	DFEMP.FLOTA_AUTOM
from 
	CDEMPRE_REQ, 
	DFEMP
where
	CDEMPRE_REQ.CIF = DFEMP.CIF AND 
	CDEMPRE_REQ.F_BAJA IS NOT NULL AND
	(CONTRATO_COOP IS NULL OR CONTRATO_COOP = 'N')
/	
CREATE OR REPLACE VIEW CDVFALLOS AS 
  SELECT	
	CDFALLOS.TPFALLO,
	CDFALLOS.FECINI,
	CDFALLOS.FECFIN,
	CDFALLOS.NUM_TRJ_CONDU_INI,
	CDFALLOS.NUM_TRJ_CONDU_FIN,
	CDFALLOS.NUM_TRJ_COPI_INI,
	CDFALLOS.NUM_TRJ_COPI_FIN,
        (SELECT MAX(NOMBRE || ' ' || APELLIDOS) AS NOMBRE_APEL FROM CDCONDUCTOR_CONT WHERE 
        substr(CDFALLOS.NUM_TRJ_CONDU_INI,0,14) = CDCONDUCTOR_CONT.IDCONDUCTOR) AS DSCR_TRJ_CONDU_INI,
        (SELECT MAX(NOMBRE || ' ' || APELLIDOS) AS NOMBRE_APEL FROM CDCONDUCTOR_CONT WHERE 
        substr(CDFALLOS.NUM_TRJ_CONDU_FIN,0,14) = CDCONDUCTOR_CONT.IDCONDUCTOR) AS DSCR_TRJ_CONDU_FIN,
        (SELECT MAX(NOMBRE || ' ' || APELLIDOS) AS NOMBRE_APEL FROM CDCONDUCTOR_CONT WHERE 
         substr(CDFALLOS.NUM_TRJ_COPI_INI,0,14) = CDCONDUCTOR_CONT.IDCONDUCTOR) AS DSCR_TRJ_COPI_INI,
        (SELECT MAX(NOMBRE || ' ' || APELLIDOS) AS NOMBRE_APEL FROM CDCONDUCTOR_CONT WHERE 
        substr(CDFALLOS.NUM_TRJ_COPI_FIN,0,14)  = CDCONDUCTOR_CONT.IDCONDUCTOR) AS DSCR_TRJ_COPI_FIN,
	CDFALLOS.MATRICULA,
        CDVVEHICULOS.DSCR AS DSCR_VEHICULO,
	CDFALLOS.NUMREQ,
	CDFALLOS.NUMREQ AS CG_CONTRATO,
	DFEMP.NOMB,
	CDEMPRE_REQ.CIF,
	DFEMP.NOMB AS NOMB_EMP,
	CDFALLOS.USUARIO_ALTA,
	CDFALLOS.F_ALTA,
	CDTIPO_PROPOSITO.TPPROPOSITO AS TPPROPOSITO,
	CDTIPO_PROPOSITO.DSCR        AS TPPROPOSITO_DSCR,		
	((CDFALLOS.FECFIN-CDFALLOS.FECINI)*60*24*60) AS  DURACION_SEGUNDOS,
	CDTIPO_FALLO.DSCR
FROM  CDFALLOS, CDTIPO_FALLO, CDEMPRE_REQ, CDTIPO_PROPOSITO, CDVVEHICULOS, DFEMP 
WHERE CDFALLOS.TPFALLO     = CDTIPO_FALLO.TPFALLO
  AND CDFALLOS.NUMREQ      = CDEMPRE_REQ.NUMREQ
  AND CDFALLOS.TPPROPOSITO = CDTIPO_PROPOSITO.TPPROPOSITO(+)
  AND CDVVEHICULOS.MATRICULA(+) = CDFALLOS.MATRICULA
  AND CDVVEHICULOS.NUMREQ(+) = CDFALLOS.NUMREQ AND CDEMPRE_REQ.CIF = DFEMP.CIF
/
CREATE OR REPLACE VIEW CDVINCIDENTES AS 
  SELECT 
     CDVEHICULO_CONT.DSCR,
    CDINCIDENTES.FECINI,
    CDINCIDENTES.FECFIN,
    CDINCIDENTES.NUM_SIMILARES,
    CDINCIDENTES.VMAX,
    CAST((
    CASE
      WHEN (CDINCIDENTES.FECFIN > CDINCIDENTES.FECINI)
      THEN ((CDINCIDENTES.FECFIN-CDINCIDENTES.FECINI)*24)
      ELSE 0
    END) AS INTEGER) AS HORAS,
    CDINCIDENTES.VMED,
    CDINCIDENTES.NUM_TRJ_CONDU_INI,
    CDINCIDENTES.NUM_TRJ_CONDU_FIN,
    CDINCIDENTES.NUM_TRJ_COPI_INI,
    CDINCIDENTES.NUM_TRJ_COPI_FIN,
    (SELECT MAX(NOMBRE || ' ' || APELLIDOS) AS NOMBRE_APEL FROM CDCONDUCTOR_CONT WHERE 
    substr(CDINCIDENTES.NUM_TRJ_CONDU_INI,0,14) = CDCONDUCTOR_CONT.IDCONDUCTOR) AS DSCR_TRJ_CONDU_INI,
    (SELECT MAX(NOMBRE || ' ' || APELLIDOS) AS NOMBRE_APEL FROM CDCONDUCTOR_CONT WHERE 
    substr(CDINCIDENTES.NUM_TRJ_CONDU_FIN,0,14) = CDCONDUCTOR_CONT.IDCONDUCTOR) AS DSCR_TRJ_CONDU_FIN,
    (SELECT MAX(NOMBRE || ' ' || APELLIDOS) AS NOMBRE_APEL FROM CDCONDUCTOR_CONT WHERE 
     substr(CDINCIDENTES.NUM_TRJ_COPI_INI,0,14) = CDCONDUCTOR_CONT.IDCONDUCTOR) AS DSCR_TRJ_COPI_INI,
    (SELECT MAX(NOMBRE || ' ' || APELLIDOS) AS NOMBRE_APEL FROM CDCONDUCTOR_CONT WHERE 
    substr(CDINCIDENTES.NUM_TRJ_COPI_FIN,0,14)  = CDCONDUCTOR_CONT.IDCONDUCTOR) AS DSCR_TRJ_COPI_FIN,
    (
    CASE
      WHEN(CDINCIDENTES.MATRICULA IS NOT NULL)
      THEN (CDINCIDENTES.MATRICULA)
      ELSE ('MATRICULA_DESCONOCIDO')
    END) AS MATRICULA,
    CDINCIDENTES.PROCEDENCIA,
    CDINCIDENTES.NUMREQ,
    CDINCIDENTES.NUMREQ AS CG_CONTRATO,
    DFEMP.NOMB,
    CDEMPRE_REQ.CIF,
    CDINCIDENTES.USUARIO_ALTA,
    CDINCIDENTES.F_ALTA,
    CDINCIDENTES.USUARIO_MODIF,
    CDINCIDENTES.F_MODIF,
    CDINCIDENTES.OBSR,
    CDINCIDENTES.PAIS,
    PAIS.DSCR                    AS DSCRPAIS,
    CDTIPO_PROPOSITO.DSCR        AS TPPROPOSITO_DSCR,
    CDTIPO_PROPOSITO.TPPROPOSITO AS TPPROPOSITO,
    -- LA DIF DE FECHAS RETORNA EL VALOR EN DIAS--> PASO A SEGUNDOS.
    ((CDINCIDENTES.FECFIN-CDINCIDENTES.FECINI)*60*24*60) AS DURACION_SEGUNDOS,
    ((CDINCIDENTES.FECFIN-CDINCIDENTES.FECINI)*60*24)    AS MINUTOS,
    CDTIPO_FALLO.DSCR                                    AS TIPO_DSCR_INC,
    CDINCIDENTES.TIPO                                    AS TIPO
  FROM CDINCIDENTES
  LEFT JOIN PAIS
  ON PAIS.COD_PAIS=CDINCIDENTES.PAIS
  LEFT JOIN CDTIPO_FALLO
  ON CDTIPO_FALLO.TPFALLO=CDINCIDENTES.TIPO
  LEFT JOIN CDEMPRE_REQ
  ON CDEMPRE_REQ.NUMREQ=CDINCIDENTES.NUMREQ LEFT JOIN DFEMP ON CDEMPRE_REQ.CIF = DFEMP.CIF  
  LEFT JOIN CDVEHICULO_CONT
  ON CDVEHICULO_CONT.MATRICULA    = CDINCIDENTES.MATRICULA
  AND CDVEHICULO_CONT.CG_CONTRATO = CDINCIDENTES.NUMREQ
  LEFT JOIN CDTIPO_PROPOSITO
  ON CDTIPO_PROPOSITO.TPPROPOSITO=CDINCIDENTES.TPPROPOSITO
/
CREATE OR REPLACE FORCE VIEW CDVINFORM_USOTARJETA AS 
  SELECT 
   CDVCONDUCTORES.dni || ': ' || CDVCONDUCTORES.apellidos || ' ' || CDVCONDUCTORES.nombre AS dscr_conductor,
    CDVCONDUCTORES.nombre || ' ' || CDVCONDUCTORES.apellidos AS NOMBRE_APEL,
   CDVCONDUCTORES.dni,
   uso.cif, 
   nomb,
   uso.numreq,
   cg_contrato,
   uso.matricula,
   uso.idconductor,
  CDVVEHICULOS.DSCR,
  to_date (to_char(fec_ins,'DD/MM/YYYY')) as fecha,
  TO_CHAR(fec_ins,'YYYY') || ' - ' || TO_CHAR (fec_ins,'month') AS MES_ANYO,
  sum(minutos) as minutos,
  dia_sem,
  dia,
  semana,
  mes,
  mes2,
  anho,
  to_date(ini_semana,'dd/mm/yyyy') as ini_semana,
  to_date(fin_semana,'dd/mm/yyyy') as fin_semana,
  num_trj_condu,
  sum(km_rec) as km_rec,
  sum(km_rec_0) as km_rec_0,
  sum(km_rec_1) as km_rec_1,
  nombre,
  apellidos,
  dias,
  DIA|| MES||ANHO AS DIA_ANUAL,
  RANURA
FROM
  (SELECT DISTINCT cdempre_req.fecini AS
   insp_fecini,
     cdempre_req.fecfin AS
   insp_fecfin,
    (cdempre_req.fecfin -cdempre_req.fecini) AS
  dias,
     cdempre_req.cif,
     dfemp.nomb,
     cdempre_req.idinspeccion,
     cduso_tarjeta_temp.numreq,
     cduso_tarjeta_temp.numreq AS
   cg_contrato,
     cduso_tarjeta_temp.matricula,
     cduso_tarjeta_temp.idconductor,
     cduso_tarjeta_temp.fec_ins,
     cduso_tarjeta_temp.fec_ext,
    (
   CASE
   WHEN(cduso_tarjeta_temp.fec_ext > cduso_tarjeta_temp.fec_ins) THEN((cduso_tarjeta_temp.fec_ext -cduso_tarjeta_temp.fec_ins) *24 *60)
   ELSE 0
   END) AS
  minutos,
    (
   CASE
   WHEN(cduso_tarjeta_temp.fec_ext > cduso_tarjeta_temp.fec_ins) THEN((cduso_tarjeta_temp.fec_ext -cduso_tarjeta_temp.fec_ins) *24)
   ELSE 0
   END) AS
  horas,
     to_char(cduso_tarjeta_temp.fec_ins,    'Day') AS
  dia_sem,
     to_char(cduso_tarjeta_temp.fec_ins,    'DD') AS
  dia,
     to_char(cduso_tarjeta_temp.fec_ins,    'HH24') AS
  hora,
     to_char(cduso_tarjeta_temp.fec_ins,    'IW') AS
  semana,
     'MES' || to_char(cduso_tarjeta_temp.fec_ins,    'MM') || '.' || to_char(cduso_tarjeta_temp.fec_ins,    'Month') AS
  mes,
     to_char(cduso_tarjeta_temp.fec_ins,    'Month') AS
  mes2,
     to_char(cduso_tarjeta_temp.fec_ins,    'YYYY') AS
  anho,
     to_char(TRUNC(cduso_tarjeta_temp.fec_ins,    'iw'),    'DD/MM/YYYY') AS
  ini_semana,
     to_char(TRUNC(cduso_tarjeta_temp.fec_ins,    'iw') + 6,    'DD/MM/YYYY') AS
  fin_semana,
     cduso_tarjeta_temp.km_ins,
     cduso_tarjeta_temp.km_ext,
     cduso_tarjeta_temp.num_trj_condu,
     NULL AS
   usuario_alta,
     NULL AS
   f_alta,
     NULL AS
   usuario_modif,
     NULL AS
   f_modif,
	   CAST((
   CASE
   WHEN( ranura = 0 and cduso_tarjeta_temp.km_ext > cduso_tarjeta_temp.km_ins) THEN cduso_tarjeta_temp.km_ext -cduso_tarjeta_temp.km_ins
   ELSE 0
   END) AS
   INTEGER) km_rec_0,
   CAST((
   CASE
   WHEN( ranura = 1 and cduso_tarjeta_temp.km_ext > cduso_tarjeta_temp.km_ins) THEN cduso_tarjeta_temp.km_ext -cduso_tarjeta_temp.km_ins
   ELSE 0
   END) AS
   INTEGER) km_rec_1,
     CAST((
   CASE
   WHEN(cduso_tarjeta_temp.km_ext > cduso_tarjeta_temp.km_ins) THEN cduso_tarjeta_temp.km_ext -cduso_tarjeta_temp.km_ins
   ELSE 0
   END) AS
   INTEGER) km_rec,
     CAST((
   CASE
   WHEN(cduso_tarjeta_temp.km_ext > cduso_tarjeta_temp.km_ins) THEN(cduso_tarjeta_temp.km_ext -cduso_tarjeta_temp.km_ins) /((cduso_tarjeta_temp.fec_ext -cduso_tarjeta_temp.fec_ins) *24)
   ELSE 0
   END) AS
   INTEGER) vel_med ,
   RANURA
   FROM cduso_tarjeta_temp,
     cdempre_req, DFEMP
   WHERE  cduso_tarjeta_temp.numreq = cdempre_req.numreq AND dfemp.cif = cdempre_req.cif)
uso,
  CDVCONDUCTORES,
  CDVVEHICULOS
WHERE uso.matricula = CDVVEHICULOS.matricula
 AND uso.cif = CDVVEHICULOS.cif
 AND uso.cif = CDVCONDUCTORES.cif(+)
  and uso.numreq = CDVVEHICULOS.numreq 
  and uso.numreq = CDVCONDUCTORES.numreq 
 AND uso.idconductor = CDVCONDUCTORES.idconductor(+)
 group by 
  CDVCONDUCTORES.dni || ': ' || CDVCONDUCTORES.apellidos || ' ' || CDVCONDUCTORES.nombre,
    CDVCONDUCTORES.nombre || ' ' || CDVCONDUCTORES.apellidos ,
   CDVCONDUCTORES.dni,
   uso.cif, 
   nomb,
   uso.numreq,
   cg_contrato,
   uso.matricula,
   uso.idconductor,
  CDVVEHICULOS.DSCR,
  to_date (to_char(fec_ins,'DD/MM/YYYY')),
  TO_CHAR(fec_ins,'YYYY') || ' - ' || TO_CHAR (fec_ins,'month') ,
  dia_sem,
  dia,
  semana,
  mes,
  mes2,
  anho,
  to_date(ini_semana,'dd/mm/yyyy'),
  to_date(fin_semana,'dd/mm/yyyy'),
  num_trj_condu,
  nombre,
  apellidos,
  dias,
  DIA|| MES||ANHO,
  RANURA
 order by fecha
/
CREATE OR REPLACE FORCE VIEW CDVVEHICULO_CONT_FICTICIO AS 
  SELECT
	A.CG_CONTRATO AS NUMREQ,
	A.CG_CONTRATO,
	A.DSCR,
	A.CIF,
	A.F_ALTA,
	A.USUARIO_ALTA,
	A.MATRICULA,
	IDDELEGACION, 
	CDVEHICULOS_EMP.DURMIENTE,
	CDVEHICULOS_EMP.F_ALTA AS F_TRABAJO
FROM
	(
		SELECT 
			CDVEHICULO_CONT.CG_CONTRATO,
			CDVEHICULO_CONT.DSCR,
			cdempre_req.CIF,
			CDVEHICULO_CONT.F_ALTA,
			CDVEHICULO_CONT.USUARIO_ALTA,
			MATRICULA
		FROM 
			CDVEHICULO_CONT, 
			cdempre_req
		WHERE 
			CDVEHICULO_CONT.CG_CONTRATO = CDEMPRE_REQ.CG_CONTRATO 
			AND CDVEHICULO_CONT.F_BAJA IS NULL
	) A ,
	CDVEHICULOS_EMP
WHERE 
	A.CIF = CDVEHICULOS_EMP.CIF AND A.MATRICULA = CDVEHICULOS_EMP.MATRICULA
UNION 
select 
	EMP_REQ.numreq,
	EMP_REQ.numreq as cg_contrato,
	CDVEHICULOS_EMP.DSCR,
	EMP_REQ.cif,
	CDVEHICULOS_EMP.F_ALTA,
	CDVEHICULOS_EMP.USUARIO_ALTA,
	CDVEHICULOS_EMP.MATRICULA,
	IDDELEGACION, 
	CDVEHICULOS_EMP.DURMIENTE,
	CDVEHICULOS_EMP.F_ALTA AS F_TRABAJO
from 
	( 
		SELECT 
			DFEMP.CIF , 
			NUMREQ, 
			CIF_COOPERATIVA  
		FROM 
			DFEMP, 
			CDEMPRE_REQ 
		WHERE 
			DFEMP.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND F_BAJA IS NULL
	) EMP_REQ
	, CDVEHICULOS_EMP
	, CDVEHICULO_CONT
where 
	EMP_REQ.cif = CDVEHICULOS_EMP.cif 
	AND CDVEHICULO_CONT.CG_CONTRATO =  EMP_REQ.NUMREQ 
	AND	CDVEHICULO_CONT.MATRICULA = CDVEHICULOS_EMP.MATRICULA
/
CREATE OR REPLACE FORCE VIEW CDVUSO_VEHICULO AS 
  SELECT
	CDEMPRE_REQ.FECINI AS INSP_FECINI,
	CDEMPRE_REQ.FECFIN AS INSP_FECFIN,
	(CDEMPRE_REQ.FECFIN-CDEMPRE_REQ.FECINI) AS DIAS,
	CDEMPRE_REQ.CIF,
	DFEMP.NOMB,
	CDEMPRE_REQ.IDINSPECCION,
    CDUSO_VEHICULO.NUMREQ,
    CDUSO_VEHICULO.NUMREQ AS CG_CONTRATO,
    CDUSO_VEHICULO.MATRICULA,
    CDUSO_VEHICULO.IDCONDUCTOR,
    CDUSO_VEHICULO.FECINI,
    CDUSO_VEHICULO.FECFIN,
    CDUSO_VEHICULO.KM_INI,
    CDUSO_VEHICULO.KM_FIN,
    CDUSO_VEHICULO.PROCEDENCIA,
    CDUSO_VEHICULO.NUM_TRJ_CONDU,
    CDUSO_VEHICULO.NUMDISCO,
    CDUSO_VEHICULO.USUARIO_ALTA,
    CDUSO_VEHICULO.F_ALTA,
    CDUSO_VEHICULO.USUARIO_MODIF,
    CDUSO_VEHICULO.F_MODIF,
    CDUSO_VEHICULO.ORIGEN,
    CDUSO_VEHICULO.DESTINO,
    CDCONDUCTORES_EMP.NOMBRE,
    CDCONDUCTORES_EMP.APELLIDOS,
    (CDUSO_VEHICULO.KM_FIN-CDUSO_VEHICULO.KM_INI) KM_REC,
    (CASE WHEN (CDUSO_VEHICULO.PROCEDENCIA='VU' OR CDUSO_VEHICULO.PROCEDENCIA='TC') THEN 'SI' ELSE 'NO' END) TC_DIG,
    (CASE WHEN(CDUSO_VEHICULO.FECFIN > CDUSO_VEHICULO.FECINI) THEN ((CDUSO_VEHICULO.FECFIN-CDUSO_VEHICULO.FECINI)*24) ELSE 0 END) AS HORAS
FROM CDUSO_VEHICULO, CDEMPRE_REQ,  CDCONDUCTORES_EMP, CDCONDUCTOR_CONT, DFEMP 
WHERE CDUSO_VEHICULO.NUMREQ       = CDEMPRE_REQ.NUMREQ
  AND CDUSO_VEHICULO.NUMREQ       = CDCONDUCTOR_CONT.CG_CONTRATO
  AND CDUSO_VEHICULO.IDCONDUCTOR  = CDCONDUCTORES_EMP.IDCONDUCTOR
  AND CDEMPRE_REQ.CIF		          = CDCONDUCTORES_EMP.CIF AND DFEMP.CIF = CDEMPRE_REQ.CIF 
  AND CDCONDUCTOR_CONT.F_BAJA IS NULL
/
ALTER TABLE DFEMP MODIFY NOMB VARCHAR2(100)
/
ALTER TABLE DFEMP MODIFY DIRECCION VARCHAR2(100)
/
ALTER TABLE DFEMP MODIFY CG_POSTAL VARCHAR2(20)
/
ALTER TABLE DFEMP ADD MOVIL2 VARCHAR2(25)
/
ALTER TABLE DFEMP ADD GRUPOCLIENTE NUMBER(6,0) DEFAULT 0
/
ALTER TABLE DFEMP ADD Z_PROCESADO VARCHAR2(1)
/
ALTER TABLE DFEMP ADD Z_ERRORES VARCHAR2(254)
/ 
ALTER TABLE DFEMP ADD Z_FECHA DATE
/
ALTER TABLE CDEMPRE_REQ MODIFY MAX_VEH VARCHAR2(6)
/
ALTER TABLE CDCONDUCTOR_CONT ADD Z_PROCESADO VARCHAR2(1)
/
ALTER TABLE CDCONDUCTOR_CONT ADD Z_ERRORES VARCHAR2(254)
/ 
ALTER TABLE CDCONDUCTOR_CONT ADD Z_FECHA DATE
/
ALTER TABLE CDVEHICULO_CONT ADD Z_PROCESADO VARCHAR2(1)
/
ALTER TABLE CDVEHICULO_CONT ADD Z_ERRORES VARCHAR2(254)
/ 
ALTER TABLE CDVEHICULO_CONT ADD Z_FECHA DATE
/
ALTER TABLE CDVEHICULO_CONT ADD TIPOMATRICULA VARCHAR2(1)
/
CREATE OR REPLACE FORCE VIEW CDVVEHICULO_CONT AS 
  SELECT
 A.CG_CONTRATO,  
  A.MATRICULA,
  A.F_ALTA,
  A.F_BAJA,
  A.USUARIO_ALTA,
  A.DSCR,
  CDVEHICULOS_EMP.CIF,
  CDVEHICULOS_EMP.IDDELEGACION,
  A.TIPOMATRICULA,
  A.Z_PROCESADO,
  A.Z_ERRORES,
  A.Z_FECHA,
  CDVEHICULOS_EMP.DURMIENTE
FROM
(SELECT 
 CDVEHICULO_CONT.CG_CONTRATO,  
  CDVEHICULO_CONT.MATRICULA,
  CDVEHICULO_CONT.F_ALTA,
  CDVEHICULO_CONT.F_BAJA,
  CDVEHICULO_CONT.USUARIO_ALTA,
  CDVEHICULO_CONT.DSCR,
  CDVEHICULO_CONT.TIPOMATRICULA,
  CDVEHICULO_CONT.Z_PROCESADO,
  CDVEHICULO_CONT.Z_ERRORES,
  CDVEHICULO_CONT.Z_FECHA,
  cdempre_req.CIF
FROM CDVEHICULO_CONT, cdempre_req
WHERE CDEMPRE_REQ.FICTICIO = 'N'
AND CDVEHICULO_CONT.CG_CONTRATO = CDEMPRE_REQ.CG_CONTRATO
UNION ALL
SELECT 
   NUM_COOP.NUMREQ AS CG_CONTRATO,  
  CDVEHICULO_CONT.MATRICULA,
  CDVEHICULO_CONT.F_ALTA,
  CDVEHICULO_CONT.F_BAJA,
  CDVEHICULO_CONT.USUARIO_ALTA,
  CDVEHICULO_CONT.DSCR,
  CDVEHICULO_CONT.TIPOMATRICULA,
  CDVEHICULO_CONT.Z_PROCESADO,
  CDVEHICULO_CONT.Z_ERRORES,
  CDVEHICULO_CONT.Z_FECHA,
  NUM_COOP.CIF
FROM CDVEHICULO_CONT, cdempre_req, (SELECT DFEMP.CIF, CIF_COOPERATIVA , NUMREQ FROM DFEMP, CDEMPRE_REQ WHERE CIF_COOPERATIVA = CDEMPRE_REQ.CIF) NUM_COOP
WHERE CDEMPRE_REQ.FICTICIO = 'S'
AND CDVEHICULO_CONT.CG_CONTRATO = CDEMPRE_REQ.CG_CONTRATO
and NUM_COOP.CIF = CDEMPRE_REQ.CIF ) A , CDVEHICULOS_EMP
WHERE 
A.CIF = CDVEHICULOS_EMP.CIF AND A.MATRICULA = CDVEHICULOS_EMP.MATRICULA
/
CREATE OR REPLACE FORCE VIEW CDVVEHICULO_CONT_FICTICIO AS 
  SELECT
	A.CG_CONTRATO AS NUMREQ,
	A.CG_CONTRATO,
	A.DSCR,
	A.CIF,
	A.F_ALTA,
	A.USUARIO_ALTA,
    A.TIPOMATRICULA,
    A.Z_PROCESADO,
    A.Z_ERRORES,
    A.Z_FECHA,
	A.MATRICULA,
	IDDELEGACION, 
	CDVEHICULOS_EMP.DURMIENTE,
	CDVEHICULOS_EMP.F_ALTA AS F_TRABAJO
FROM
	(
		SELECT 
			CDVEHICULO_CONT.CG_CONTRATO,
			CDVEHICULO_CONT.DSCR,
			cdempre_req.CIF,
			CDVEHICULO_CONT.F_ALTA,
			CDVEHICULO_CONT.USUARIO_ALTA,
            CDVEHICULO_CONT.TIPOMATRICULA,
            CDVEHICULO_CONT.Z_PROCESADO,
            CDVEHICULO_CONT.Z_ERRORES,
            CDVEHICULO_CONT.Z_FECHA,
			MATRICULA
		FROM 
			CDVEHICULO_CONT, 
			cdempre_req
		WHERE 
			CDVEHICULO_CONT.CG_CONTRATO = CDEMPRE_REQ.CG_CONTRATO 
			AND CDVEHICULO_CONT.F_BAJA IS NULL
	) A ,
	CDVEHICULOS_EMP
WHERE 
	A.CIF = CDVEHICULOS_EMP.CIF AND A.MATRICULA = CDVEHICULOS_EMP.MATRICULA
UNION 
select 
	EMP_REQ.numreq,
	EMP_REQ.numreq as cg_contrato,
	CDVEHICULOS_EMP.DSCR,
	EMP_REQ.cif,
	CDVEHICULOS_EMP.F_ALTA,
	CDVEHICULOS_EMP.USUARIO_ALTA,
    CDVEHICULO_CONT.TIPOMATRICULA,
    CDVEHICULO_CONT.Z_PROCESADO,
    CDVEHICULO_CONT.Z_ERRORES,
    CDVEHICULO_CONT.Z_FECHA,
	CDVEHICULOS_EMP.MATRICULA,
	IDDELEGACION, 
	CDVEHICULOS_EMP.DURMIENTE,
	CDVEHICULOS_EMP.F_ALTA AS F_TRABAJO
from 
	( 
		SELECT 
			DFEMP.CIF , 
			NUMREQ, 
			CIF_COOPERATIVA  
		FROM 
			DFEMP, 
			CDEMPRE_REQ 
		WHERE 
			DFEMP.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND F_BAJA IS NULL
	) EMP_REQ
	, CDVEHICULOS_EMP
	, CDVEHICULO_CONT
where 
	EMP_REQ.cif = CDVEHICULOS_EMP.cif 
	AND CDVEHICULO_CONT.CG_CONTRATO =  EMP_REQ.NUMREQ 
	AND	CDVEHICULO_CONT.MATRICULA = CDVEHICULOS_EMP.MATRICULA
/
CREATE OR REPLACE FORCE VIEW CDVVEHICULO_CONT_VALIDO AS 
  SELECT A.CG_CONTRATO,  
  A.MATRICULA,
  A.F_ALTA,
  A.F_BAJA,
  A.USUARIO_ALTA,
  A.TIPOMATRICULA,
  A.Z_PROCESADO,
  A.Z_ERRORES,
  A.Z_FECHA,
  CDVEHICULOS_EMP.DSCR,
  CDVEHICULOS_EMP.CIF,
  CDVEHICULOS_EMP.IDDELEGACION
FROM
(SELECT 
  CDVEHICULO_CONT.MATRICULA,
  CDVEHICULO_CONT.F_ALTA,
  CDVEHICULO_CONT.F_BAJA,
  CDVEHICULO_CONT.USUARIO_ALTA,
  CDVEHICULO_CONT.TIPOMATRICULA,
  CDVEHICULO_CONT.Z_PROCESADO,
  CDVEHICULO_CONT.Z_ERRORES,
  CDVEHICULO_CONT.Z_FECHA,
  CDVEMPRE_REQ.CIF,
  CDVEHICULO_CONT.CG_CONTRATO
FROM  CDVEHICULO_CONT, CDVEMPRE_REQ
WHERE CDVEHICULO_CONT.CG_CONTRATO =  CDVEMPRE_REQ.CG_CONTRATO) A, CDVEHICULOS_EMP 
WHERE A.MATRICULA = CDVEHICULOS_EMP.MATRICULA(+)
  AND A.CIF       = CDVEHICULOS_EMP.CIF(+)
  AND CDVEHICULOS_EMP.MATRICULA IS NOT NULL
  AND A.F_BAJA IS NULL
/
CREATE OR REPLACE VIEW CDVCONDUCTOR_CONT AS 
  SELECT
	A.CG_CONTRATO AS NUMREQ,
	A.CG_CONTRATO,
	A.CIF,
	A.F_ALTA,
	A.USUARIO_ALTA,
	A.F_BAJA,  
    A.Z_ERRORES,
    A.Z_PROCESADO,
    A.Z_FECHA,
	CDCONDUCTORES_EMP.DNI,
	CDCONDUCTORES_EMP.NOMBRE,
	CDCONDUCTORES_EMP.APELLIDOS,
	CDCONDUCTORES_EMP.EMAIL,
	CDCONDUCTORES_EMP.MOVIL,
	CDCONDUCTORES_EMP.NOTIFICAR_MOVIL,
	CDCONDUCTORES_EMP.NOTIFICAR_EMAIL,
	CDCONDUCTORES_EMP.IDCONDUCTOR,
	CDCONDUCTORES_EMP.IDDELEGACION, 
	CDCONDUCTORES_EMP.DURMIENTE,
	CDCONDUCTORES_EMP.F_ALTA AS F_TRABAJO, 
	CDCONDUCTORES_EMP.F_NAC
FROM
	(
	SELECT 
		CDCONDUCTOR_CONT.CG_CONTRATO,
		cdvempre_req_reales.CIF,
		CDCONDUCTOR_CONT.F_ALTA,
		CDCONDUCTOR_CONT.USUARIO_ALTA,
		CDCONDUCTOR_CONT.F_BAJA,
		CDCONDUCTOR_CONT.IDCONDUCTOR,
        CDCONDUCTOR_CONT.Z_ERRORES,
        CDCONDUCTOR_CONT.Z_PROCESADO,
        CDCONDUCTOR_CONT.Z_FECHA
	FROM 
		CDCONDUCTOR_CONT, 
		cdvempre_req_reales
	WHERE 
		CDCONDUCTOR_CONT.CG_CONTRATO = cdvempre_req_reales.CG_CONTRATO	
	) A,
	CDCONDUCTORES_EMP
WHERE 
	A.CIF = CDCONDUCTORES_EMP.CIF AND 
	A.IDCONDUCTOR = CDCONDUCTORES_EMP.IDCONDUCTOR
/
CREATE OR REPLACE VIEW CDVCONDUCTOR_CONT_VALIDO AS 
  SELECT
  CG_CONTRATO,
  DNI,
  F_ALTA,
  F_BAJA,
  USUARIO_ALTA,
  CIF, 
  IDCONDUCTOR,
  NOMBRE,
  APELLIDOS,
  MOVIL,
  EMAIL,
  NOTIFICAR_MOVIL,
  NOTIFICAR_EMAIL,
  IDDELEGACION,
  DURMIENTE,
  F_TRABAJO,
  F_NAC,
  Z_PROCESADO,
  Z_ERRORES,
  Z_FECHA
FROM CDVCONDUCTOR_CONT
WHERE CDVCONDUCTOR_CONT.IDCONDUCTOR IS NOT NULL 
  AND CDVCONDUCTOR_CONT.F_BAJA IS NULL
/
CREATE OR REPLACE FORCE VIEW CDVDFEMP AS 
  SELECT 
    DFEMP.CIF,
    DFEMP.NOMB,
    DFEMP.IS_DEMO,
    CG_EMPR,
    DOMI,
    CG_PROV,
    CG_MUNI,
    CG_POBL,
    CG_POSTAL,
    TELF,
    FAX,
    CIF_CO,
    F_FIN_HF,
    CL_PROR,
    IDENTIFICADOR,
    REGI_IDEN,
    TIPO_IDEN,
    F_ALTA,
    EMAIL,
    PAG_WEB,
    DFEMP.CG_NACI,
    DIRECCION,
    USUARIO_ALTA,
    F_MODIF,
    USUARIO_MODIF,
    MUNI,
    POBL,
    OBSR,
    TIPO,
    IDGRUPO,
    MOVIL,
    PCONTACTO,
    MCONTACTO,
    LOCALE,
    MAILINFORMEANALISIS,
    PAIS.DSCR    AS PAIS,
    PAIS.PREFIJO AS PREFIJO,
    FLOTA_AUTOM,
    IS_COOPERATIVA,
    DFEMP.CIF_COOPERATIVA,
    CONTRATO_COOP,
    DFEMP.TDI,
    DFEMP.TDI_IP,
    DFEMP.TDI_PORT,
    DFEMP.TDI_USER,
    DFEMP.TDI_PASS,
    DFEMP.TDI_GROUPID,
    DFEMP.GRUPOCLIENTE,
    DFEMP.MOVIL2,
    DFEMP.Z_ERRORES,
    DFEMP.Z_PROCESADO,
    DFEMP.Z_FECHA
FROM 
    DFEMP,
    PAIS
WHERE 
    DFEMP.CG_NACI = PAIS.CG_NACI (+)
/
CREATE OR REPLACE VIEW CDVDFEMP_COOP AS 
  SELECT 
	CIF,
	NOMB,
	CG_EMPR,
	DOMI,
	CG_PROV,
	CG_MUNI,
	CG_POBL,
	CG_POSTAL,
	TELF,
	FAX,
	CIF_CO,
	F_FIN_HF,
	CL_PROR,
	IDENTIFICADOR,
	REGI_IDEN,
	TIPO_IDEN,
	F_ALTA,
	EMAIL,
	PAG_WEB,
	DFEMP.CG_NACI,
	DIRECCION,
	USUARIO_ALTA,
	F_MODIF,
	USUARIO_MODIF,
	MUNI,
	POBL,
	OBSR,
	TIPO,
	IDGRUPO,
	MOVIL,
	PCONTACTO,
	MCONTACTO,
	LOCALE,
	MAILINFORMEANALISIS,
	PAIS.DSCR    AS PAIS,
	PAIS.PREFIJO AS PREFIJO,
	FLOTA_AUTOM,
	IS_COOPERATIVA,
	NULL AS CIF_COOPERATIVA,
	CONTRATO_COOP,
    DFEMP.GRUPOCLIENTE,
    DFEMP.MOVIL2,
    DFEMP.Z_ERRORES,
    DFEMP.Z_PROCESADO,
    DFEMP.Z_FECHA
FROM 
	DFEMP,
	PAIS
WHERE 
	DFEMP.CG_NACI = PAIS.CG_NACI (+) 
	AND (IS_COOPERATIVA = 'S' OR CIF_COOPERATIVA IS NULL)
/
CREATE OR REPLACE VIEW CDVDFEMP_NO_COOP AS 
  SELECT 
	DFEMP.CIF,
	DFEMP.NOMB,
	DFEMP.CG_EMPR,
	DFEMP.DOMI,
	DFEMP.CG_PROV,
	DFEMP.CG_MUNI,
	DFEMP.CG_POBL,
	DFEMP.CG_POSTAL,
	DFEMP.TELF,
	DFEMP.FAX,
	DFEMP.CIF_CO,
	DFEMP.F_FIN_HF,
	DFEMP.CL_PROR,
	DFEMP.IDENTIFICADOR,
	DFEMP.REGI_IDEN,
	DFEMP.TIPO_IDEN,
	DFEMP.F_ALTA,
	DFEMP.EMAIL,
	DFEMP.PAG_WEB,
	DFEMP.CG_NACI,
	DFEMP.DIRECCION,
	DFEMP.USUARIO_ALTA,
	DFEMP.F_MODIF,
	DFEMP.USUARIO_MODIF,
	DFEMP.MUNI,
	DFEMP.POBL,
	DFEMP.OBSR,
	DFEMP.TIPO,
	DFEMP.IDGRUPO,
	DFEMP.MOVIL,
	DFEMP.PCONTACTO,
	DFEMP.MCONTACTO,
	DFEMP.LOCALE,
	DFEMP.MAILINFORMEANALISIS,
	PAIS.DSCR    AS PAIS,
	PAIS.PREFIJO AS PREFIJO,
	DFEMP.FLOTA_AUTOM,
	DFEMP.IS_COOPERATIVA,
	DFEMP.CIF_COOPERATIVA,
	NVL((SELECT D.NOMB FROM DFEMP D WHERE D.CIF = DFEMP.CIF_COOPERATIVA), NULL) AS NOMB_COOP,
	DFEMP.CONTRATO_COOP,
    DFEMP.GRUPOCLIENTE,
    DFEMP.MOVIL2,
    DFEMP.Z_ERRORES,
    DFEMP.Z_PROCESADO,
    DFEMP.Z_FECHA
FROM 
	DFEMP, 
	PAIS
WHERE 
	DFEMP.CG_NACI = PAIS.CG_NACI(+) 
	AND (DFEMP.IS_COOPERATIVA = 'N')
/
CREATE OR REPLACE VIEW CDVPERIODOS_TRABAJO AS 
  SELECT    
    CDPERIODOS_TRABAJO.NUM_TARJ as NUM_TARJETA,
    CDPERIODOS_TRABAJO.TPPERIODO,
    CDPERIODOS_TRABAJO.FECINI,
    CDPERIODOS_TRABAJO.PAIS,
    CDPERIODOS_TRABAJO.IDREGION,
    CDPERIODOS_TRABAJO.PROCEDENCIA,
    CDPERIODOS_TRABAJO.NUMREQ,
    CDPERIODOS_TRABAJO.NUMREQ AS CG_CONTRATO,
    CDPERIODOS_TRABAJO.IDCONDUCTOR,
    CDPERIODOS_TRABAJO.USUARIO_ALTA,
    CDPERIODOS_TRABAJO.F_ALTA,
    CDCONDUCTORES_EMP.DNI,
    CDCONDUCTORES_EMP.NOMBRE,
    CDCONDUCTORES_EMP.APELLIDOS,
    CDREGIONES.DSCR AS DSCRREGION,
    PAIS.DSCR AS DSCRPAIS,
    CDTIPO_PERIODO_TRAB.DSCR AS DSCRTIPO, 
    CDPERIODOS_TRaBAJO.ERROR
FROM 
 (
 SELECT TPPERIODO, FECINI, PAIS, IDREGION, PROCEDENCIA, NUMREQ, IDCONDUCTOR, USUARIO_ALTA,F_ALTA, num_tarj, CASE WHEN TPPERIODO IN (0,2,4) AND TPPERIODONEXT IN(1,3,5) AND IDREGION != IDREGNEXT THEN 'S' ELSE 'N' END AS ERROR  FROM( 
   SELECT TPPERIODO, FECINI, PAIS, IDREGION, PROCEDENCIA, NUMREQ, IDCONDUCTOR, USUARIO_ALTA,F_ALTA,num_tarj, IDREGNEXT, TPPERIODONEXT FROM(
    SELECT TPPERIODO, FECINI, PAIS, IDREGION, PROCEDENCIA, NUMREQ, IDCONDUCTOR,USUARIO_ALTA,F_ALTA,num_tarj,
           LEAD(IDREGION, 1, NULL) OVER (PARTITION BY IDCONDUCTOR ORDER BY  NUMREQ, IDCONDUCTOR, FECINI DESC) AS IDREGNEXT,
           LEAD(TPPERIODO, 1, NULL) OVER (PARTITION BY IDCONDUCTOR ORDER BY  NUMREQ, IDCONDUCTOR, FECINI DESC ) AS TPPERIODONEXT
     FROM CDPERIODOS_TRABAJO
     GROUP BY NUMREQ, IDCONDUCTOR, FECINI, PAIS, IDREGION, PROCEDENCIA, TPPERIODO,USUARIO_ALTA,F_ALTA ,num_tarj
     ORDER BY NUMREQ, IDCONDUCTOR, FECINI DESC, PAIS, IDREGION, PROCEDENCIA, TPPERIODO
   )
  ) 
 ) CDPERIODOS_TRABAJO, CDTIPO_PERIODO_TRAB, PAIS, CDREGIONES, CDCONDUCTORES_EMP, CDCONDUCTOR_CONT, CDVEMPRE_REQ_REALES
WHERE  CDPERIODOS_TRABAJO.TPPERIODO    = CDTIPO_PERIODO_TRAB.TPPERIODO
  AND  CDPERIODOS_TRABAJO.IDREGION     = CDREGIONES.IDREGION(+)
  AND  LPAD(cdperiodos_trabajo.pais,2,'0')    = PAIS.COD_PAIS(+)
  AND  CDPERIODOS_TRABAJO.IDCONDUCTOR  = CDCONDUCTORES_EMP.IDCONDUCTOR
  AND  CDPERIODOS_TRABAJO.NUMREQ       = CDCONDUCTOR_CONT.CG_CONTRATO
  AND  CDVEMPRE_REQ_REALES.CIF                 = CDCONDUCTORES_EMP.CIF
  AND  CDCONDUCTOR_CONT.CG_CONTRATO    = CDVEMPRE_REQ_REALES.NUMREQ
  AND  CDCONDUCTOR_CONT.IDCONDUCTOR            = CDCONDUCTORES_EMP.IDCONDUCTOR
/  
CREATE TABLE CDPERSONAL_EMP (
DNI	VARCHAR2(10),
NOMBRE	VARCHAR2(40),
APELLIDOS	VARCHAR2(100),
CIF	VARCHAR2(15),
F_ALTA	DATE,
USUARIO_ALTA	VARCHAR2(255),
MOVIL	VARCHAR2(20),
EMAIL	VARCHAR2(1024),
NOTIFICAR_MOVIL	NUMBER(1,0),
NOTIFICAR_EMAIL	NUMBER(1,0),
IDPERSONAL	VARCHAR2(14),
OBSR	CLOB,
IDDELEGACION	NUMBER(10,0),
F_NAC	DATE,
PHOTO	BLOB,
ENVIAR_A	VARCHAR2(10),
CONSTRAINT "CDPERSONAL_EMP_PK" PRIMARY KEY ("CIF", "IDPERSONAL"),
CONSTRAINT "CDPERSONAL_FK" FOREIGN KEY ("CIF")	  REFERENCES DFEMP ("CIF") ENABLE)
/