ALTER TABLE CDEMPRE_REQ ADD ESTADO_ACTIVIDAD VARCHAR2(12);
ALTER TABLE CDEMPRE_REQ ADD F_FIN_CONTRATO	DATE;
ALTER TABLE CDEMPRE_REQ ADD TIPO_FACTURACION VARCHAR2(10);



  CREATE OR REPLACE VIEW CDVEMPRE_REQ_REALES AS 
  SELECT  
  CDEMPRE_REQ.NUMREQ,
  CDEMPRE_REQ.CIF,
  DFEMP.NOMB,
  CDEMPRE_REQ.IDINSPECCION,
  CDEMPRE_REQ.F_REQ,
  CDEMPRE_REQ.USUARIO_ALTA,
  CDEMPRE_REQ.F_ALTA,
  CDEMPRE_REQ.F_MODIF,
  CDEMPRE_REQ.USUARIO_MODIF,
  CDEMPRE_REQ.F_BAJA,
  CDEMPRE_REQ.CG_ORGA,
  CDEMPRE_REQ.FECINI AS FECINID,
  CDEMPRE_REQ.FECFIN AS FECFIND,
  CDEMPRE_REQ.AVISO_EXPIRACION,
  CDEMPRE_REQ.CG_CONTRATO,
  CDEMPRE_REQ.F_CONTRATO,
  CDEMPRE_REQ.MAX_COND,
  CDEMPRE_REQ.MAX_VEH,
  DFEMP.FLOTA_AUTOM,
  CDEMPRE_REQ.TERMDATEDEMO,
  CDEMPRE_REQ.ENDDATEDEMO,
  CDEMPRE_REQ.ESTADO,
  CDEMPRE_REQ.DSCR,
  CDEMPRE_REQ.AGENTE,
  CDEMPRE_REQ.ZONA,
  CDEMPRE_REQ.F_RENOVACION,
  CDEMPRE_REQ.ESTADO_VALIDACION,
  CDEMPRE_REQ.IDKIT,
  CDEMPRE_REQ.DSCR_KIT,
  CDEMPRE_REQ.OBSR_KIT,
  CDEMPRE_REQ.MODALIDAD_DIGITAL,
  CDEMPRE_REQ.DSCR_MODALIDAD_DIGITAL,
  CDEMPRE_REQ.Z_FECHA,
  CDEMPRE_REQ.RENOV_CONTRATO,
  CDEMPRE_REQ.RENUEVA,
  CDEMPRE_REQ.Z_ERRORES,
  CDEMPRE_REQ.Z_PROCESADO,
  CDEMPRE_REQ.F_ANULACION,
  CDEMPRE_REQ.U_NUM_MAXIMO,
  CDEMPRE_REQ.FICTICIO,
  CDEMPRE_REQ.ESTADO_ACTIVIDAD,
  CDEMPRE_REQ.F_FIN_CONTRATO,
  CDEMPRE_REQ.TIPO_FACTURACION
FROM CDEMPRE_REQ, DFEMP WHERE CDEMPRE_REQ.CIF = DFEMP.CIF 
AND FICTICIO = 'N'
UNION ALL
SELECT   
  CDEMPRE_REQ.NUMREQ,
  DFEMP_FIC.CIF,
  DFEMP_FIC.NOMB,
  CDEMPRE_REQ.IDINSPECCION,
  CDEMPRE_REQ.F_REQ,
  CDEMPRE_REQ.USUARIO_ALTA,
  CDEMPRE_REQ.F_ALTA,
  CDEMPRE_REQ.F_MODIF,
  CDEMPRE_REQ.USUARIO_MODIF,
  CDEMPRE_REQ.F_BAJA,
  CDEMPRE_REQ.CG_ORGA,
  CDEMPRE_REQ.FECINI AS FECINID,
  CDEMPRE_REQ.FECFIN AS FECFIND,
  CDEMPRE_REQ.AVISO_EXPIRACION,
  CDEMPRE_REQ.CG_CONTRATO,
  CDEMPRE_REQ.F_CONTRATO,
  CDEMPRE_REQ.MAX_COND,
  CDEMPRE_REQ.MAX_VEH,
  DFEMP_FIC.FLOTA_AUTOM,
  CDEMPRE_REQ.TERMDATEDEMO,
  CDEMPRE_REQ.ENDDATEDEMO,
  CDEMPRE_REQ.ESTADO,
  CDEMPRE_REQ.DSCR,
  CDEMPRE_REQ.AGENTE,
  CDEMPRE_REQ.ZONA,
  CDEMPRE_REQ.F_RENOVACION,
  CDEMPRE_REQ.ESTADO_VALIDACION,
  CDEMPRE_REQ.IDKIT,
  CDEMPRE_REQ.DSCR_KIT,
  CDEMPRE_REQ.OBSR_KIT,
  CDEMPRE_REQ.MODALIDAD_DIGITAL,
  CDEMPRE_REQ.DSCR_MODALIDAD_DIGITAL,
  CDEMPRE_REQ.Z_FECHA,
  CDEMPRE_REQ.RENOV_CONTRATO,
  CDEMPRE_REQ.RENUEVA,
  CDEMPRE_REQ.Z_ERRORES,
  CDEMPRE_REQ.Z_PROCESADO,
  CDEMPRE_REQ.F_ANULACION,
  CDEMPRE_REQ.U_NUM_MAXIMO,
  CDEMPRE_REQ.FICTICIO,
  CDEMPRE_REQ.ESTADO_ACTIVIDAD,
  CDEMPRE_REQ.F_FIN_CONTRATO,
  CDEMPRE_REQ.TIPO_FACTURACION
  FROM CDEMPRE_REQ, (SELECT DFEMP.CIF, DFEMP.NOMB,CIF_COOPERATIVA, NUMREQ, FLOTA_AUTOM FROM CDEMPRE_REQ, DFEMP WHERE CDEMPRE_REQ.CIF = DFEMP.CIF AND FICTICIO='S')DFEMP_FIC
  WHERE FICTICIO='N'  AND DFEMP_FIC.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND CIF_COOPERATIVA IS NOT NULL AND F_BAJA IS NULL;

  
  
  CREATE OR REPLACE VIEW CDVCONTRATO_EMPRESA AS 
  SELECT 
	(case when DFEMP.CONTRATO_COOP='S' then ( SELECT  CDEMPRE_REQ.NUMREQ  FROM DFEMP DF, CDEMPRE_REQ WHERE DF.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND CDEMPRE_REQ.F_BAJA IS NULL AND DFEMP.CIF = DF.CIF) else CDEMPRE_REQ.NUMREQ end) as NUMREQ,
	(case when DFEMP.CONTRATO_COOP='S' then ( SELECT  CDEMPRE_REQ.NUMREQ  FROM DFEMP DF, CDEMPRE_REQ WHERE DF.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND CDEMPRE_REQ.F_BAJA IS NULL AND DFEMP.CIF = DF.CIF) else CDEMPRE_REQ.NUMREQ end) as CG_CONTRATO,	
	CDEMPRE_REQ.F_CONTRATO,
	DFEMP.CIF,
	CDEMPRE_REQ.IDINSPECCION,
	CDEMPRE_REQ.F_REQ,
	CDEMPRE_REQ.USUARIO_ALTA,
	CDEMPRE_REQ.F_ALTA,
	CDEMPRE_REQ.F_ANULACION,
	CDEMPRE_REQ.USUARIO_MODIF,
	CDEMPRE_REQ.F_MODIF,
	CDEMPRE_REQ.F_BAJA,
	DFEMP.NOMB,
	DFEMP.NOMB as NOMB_EMP,
	TO_CHAR(CDEMPRE_REQ.FECINID,'DD/MM/YYYY')||' - '|| TO_CHAR(CDEMPRE_REQ.FECFIND,'DD/MM/YYYY') AS NOMBRECOMPLETO,
	CDEMPRE_REQ.CG_ORGA,
	CDEMPRE_REQ.AVISO_EXPIRACION,
	CDEMPRE_REQ.FECINID AS FECINI,
	CDEMPRE_REQ.FECFIND AS FECFIN,
	CDEMPRE_REQ.MAX_COND,
	CDEMPRE_REQ.MAX_VEH,	
	CDEMPRE_REQ.TERMDATEDEMO,
	CDEMPRE_REQ.ENDDATEDEMO,
	CDEMPRE_REQ.ESTADO,
	CDEMPRE_REQ.DSCR,
	CDEMPRE_REQ.AGENTE,
	CDEMPRE_REQ.ZONA,
	CDEMPRE_REQ.F_RENOVACION,
	CDEMPRE_REQ.ESTADO_VALIDACION,
	CDEMPRE_REQ.IDKIT,
	CDEMPRE_REQ.DSCR_KIT,
	CDEMPRE_REQ.OBSR_KIT,
	CDEMPRE_REQ.MODALIDAD_DIGITAL,
	CDEMPRE_REQ.Z_FECHA,
	CDEMPRE_REQ.RENOV_CONTRATO,
	CDEMPRE_REQ.RENUEVA,
	CDEMPRE_REQ.Z_ERRORES,
	CDEMPRE_REQ.Z_PROCESADO,
	DFEMP.FLOTA_AUTOM,
	CDEMPRE_REQ.FICTICIO,
	CDEMPRE_REQ.U_NUM_MAXIMO,
	CDEMPRE_REQ.DSCR_MODALIDAD_DIGITAL,
    CDEMPRE_REQ.ESTADO_ACTIVIDAD,
    CDEMPRE_REQ.F_FIN_CONTRATO,
    CDEMPRE_REQ.TIPO_FACTURACION
FROM 	
	DFEMP,
	cdvempre_req_reales CDEMPRE_REQ
WHERE 
	DFEMP.CIF = CDEMPRE_REQ.CIF AND
	CDEMPRE_REQ.F_BAJA IS NULL 
UNION ALL
select 
	CDEMPRE_REQ.NUMREQ,
	CDEMPRE_REQ.CG_CONTRATO,
	CDEMPRE_REQ.F_CONTRATO,
	CDEMPRE_REQ.CIF,
	CDEMPRE_REQ.IDINSPECCION,
	CDEMPRE_REQ.F_REQ,
	CDEMPRE_REQ.USUARIO_ALTA,
	CDEMPRE_REQ.F_ALTA,
	CDEMPRE_REQ.F_ANULACION,
	CDEMPRE_REQ.USUARIO_MODIF,
	CDEMPRE_REQ.F_MODIF,
	CDEMPRE_REQ.F_BAJA,
	DFEMP.NOMB,
	DFEMP.NOMB as NOMB_EMP,	
	TO_CHAR(CDEMPRE_REQ.FECINI,'DD/MM/YYYY')||' - '|| TO_CHAR(CDEMPRE_REQ.FECFIN,'DD/MM/YYYY') AS NOMBRECOMPLETO,
	CDEMPRE_REQ.CG_ORGA,
	CDEMPRE_REQ.AVISO_EXPIRACION,
	CDEMPRE_REQ.FECINI,
	CDEMPRE_REQ.FECFIN,
	CDEMPRE_REQ.MAX_COND,
	CDEMPRE_REQ.MAX_VEH,	
	CDEMPRE_REQ.TERMDATEDEMO,
	CDEMPRE_REQ.ENDDATEDEMO,
	CDEMPRE_REQ.ESTADO,
	CDEMPRE_REQ.DSCR,
	CDEMPRE_REQ.AGENTE,
	CDEMPRE_REQ.ZONA,
	CDEMPRE_REQ.F_RENOVACION,
	CDEMPRE_REQ.ESTADO_VALIDACION,
	CDEMPRE_REQ.IDKIT,
	CDEMPRE_REQ.DSCR_KIT,
	CDEMPRE_REQ.OBSR_KIT,
	CDEMPRE_REQ.MODALIDAD_DIGITAL,
	CDEMPRE_REQ.Z_FECHA,
	CDEMPRE_REQ.RENOV_CONTRATO,
	CDEMPRE_REQ.RENUEVA,
	CDEMPRE_REQ.Z_ERRORES,
	CDEMPRE_REQ.Z_PROCESADO,
	DFEMP.FLOTA_AUTOM,
	CDEMPRE_REQ.FICTICIO,
	CDEMPRE_REQ.U_NUM_MAXIMO,
	CDEMPRE_REQ.DSCR_MODALIDAD_DIGITAL,
    CDEMPRE_REQ.ESTADO_ACTIVIDAD,
    CDEMPRE_REQ.F_FIN_CONTRATO,
    CDEMPRE_REQ.TIPO_FACTURACION
from 
	CDEMPRE_REQ, 
	DFEMP
where
	CDEMPRE_REQ.CIF = DFEMP.CIF AND 
	CDEMPRE_REQ.F_BAJA IS NOT NULL AND
	(CONTRATO_COOP IS NULL OR CONTRATO_COOP = 'N');

	
	
	
	
ALTER TABLE DFEMP ADD NUM_MAX_VEHICLES NUMBER(5,0);


  CREATE OR REPLACE VIEW CDVDFEMP AS 
  SELECT 
    DFEMP.CIF,
    DFEMP.NOMB,
    DFEMP.IS_DEMO,
    CG_EMPR,
    DOMI,
    CG_PROV,
    CG_MUNI,
    CG_POBL,
    CG_POSTAL,
    TELF,
    FAX,
    CIF_CO,
    F_FIN_HF,
    CL_PROR,
    IDENTIFICADOR,
    REGI_IDEN,
    TIPO_IDEN,
    F_ALTA,
    EMAIL,
    PAG_WEB,
    DFEMP.CG_NACI,
    DIRECCION,
    USUARIO_ALTA,
    F_MODIF,
    USUARIO_MODIF,
    MUNI,
    POBL,
    OBSR,
    TIPO,
    IDGRUPO,
    MOVIL,
    PCONTACTO,
    MCONTACTO,
    LOCALE,
    MAILINFORMEANALISIS,
    PAIS.DSCR    AS PAIS,
    PAIS.PREFIJO AS PREFIJO,
    FLOTA_AUTOM,
    IS_COOPERATIVA,
    DFEMP.CIF_COOPERATIVA,
    CONTRATO_COOP,
    DFEMP.TDI,
    DFEMP.TDI_IP,
    DFEMP.TDI_PORT,
    DFEMP.TDI_USER,
    DFEMP.TDI_PASS,
    DFEMP.TDI_GROUPID,
    DFEMP.GRUPOCLIENTE,
    DFEMP.MOVIL2,
    DFEMP.Z_ERRORES,
    DFEMP.Z_PROCESADO,
    DFEMP.Z_FECHA,
    DFEMP.EMP_FTPSYNC,
    DFEMP.EMP_FTP_URL,
    DFEMP.EMP_FTP_USR,
    DFEMP.EMP_FTP_PAS,
    DFEMP.EMP_FTP_PATH,
    DFEMP.NUM_MAX_VEHICLES,
    (SELECT COUNT(*) FROM CDVEHICULOS_EMP WHERE CIF = DFEMP.CIF) AS NUM_VEHICLES
FROM 
    DFEMP,
    PAIS
WHERE 
    DFEMP.CG_NACI = PAIS.CG_NACI (+);
    
    
    
    

  CREATE TABLE TSK_TASK_MADE_BY  (	
    TKM_ID NUMBER, 
	TKM_NAME VARCHAR2(25 BYTE), 
	CONSTRAINT TSK_TASK_MADEBY_PK PRIMARY KEY (TKM_ID));
    
 CREATE TABLE TSK_TASK_COMMUNICATED_BY (	
   TKCM_ID NUMBER, 
   TKCM_NAME VARCHAR2(25 BYTE), 
   CONSTRAINT TSK_TASK_COMMUNICATED_BY_PK PRIMARY KEY (TKCM_ID));
    
    
ALTER TABLE TSK_TASK ADD TKCM_ID	NUMBER;
ALTER TABLE TSK_TASK ADD TKM_ID	NUMBER;
ALTER TABLE TSK_TASK ADD TSK_IS_NEW_VEHICLE	VARCHAR2(1);
ALTER TABLE TSK_TASK ADD TSK_IS_MONTHLY_TURNOVER	VARCHAR2(1);
ALTER TABLE TSK_TASK ADD TSK_IS_OUTPUT	VARCHAR2(1);
ALTER TABLE TSK_TASK ADD TSK_IS_WAITING_FOR_AGREEMENT	VARCHAR2(1);
ALTER TABLE TSK_TASK ADD TSK_IS_NEXT_RENEWAL	VARCHAR2(1);

ALTER TABLE TSK_TASK ADD  CONSTRAINT TSK_TASK_COMMUNICATED_BY_FK FOREIGN KEY (TKCM_ID)
	  REFERENCES TSK_TASK_COMMUNICATED_BY (TKCM_ID) ENABLE;
	  
ALTER TABLE TSK_TASK ADD  CONSTRAINT TSK_TASK_MADEBY_FK FOREIGN KEY (TKM_ID)
	  REFERENCES TSK_TASK_MADE_BY (TKM_ID) ENABLE;
	  
	  
	  
	  

  CREATE OR REPLACE VIEW VTSK_TASK AS 
  select 
  tsk.TSK_ID,
  tsk.TSK_TITLE,
  tsk.TSK_DESCRIPTION,
  tsk.CIF,
  tsk.ECN_ID,
  tsk.TKS_ID,
  tsk.TKC_ID,
  tsk.TSU_ID,
  tsk.USUARIO_CREATOR,
  tsk.USUARIO_ASIGNEE,
  tsk.TPR_ID,
  tsk.TSK_CREATION_DATE,
  tsk.TSK_CLOSED_DATE,
  nvl(tsk.TSK_IS_NEW_VEHICLE,'N') as TSK_IS_NEW_VEHICLE,
  nvl(tsk.TSK_IS_MONTHLY_TURNOVER,'N') as TSK_IS_MONTHLY_TURNOVER,
  nvl(tsk.TSK_IS_OUTPUT,'N') as TSK_IS_OUTPUT,
  nvl(tsk.TSK_IS_WAITING_FOR_AGREEMENT,'N') as TSK_IS_WAITING_FOR_AGREEMENT,
  nvl(tsk.TSK_IS_NEXT_RENEWAL,'N') as TSK_IS_NEXT_RENEWAL,       
  pri.TPR_NAME,
  sta.TKS_NAME,
  cla.TKC_NAME,
  subcla.TSU_NAME,
  madeby.TKM_ID,
  commby.TKCM_ID,
  madeby.TKM_NAME,
  commby.TKCM_NAME,
  comp.NOMB as COMPANY_NAME,
  cont.ECN_NAME as CONTACT_NAME,
  cont.ECN_TLF1,
  cont.ECN_TLF2,
  cont.ECN_MAIL
from
  TSK_TASK tsk,
  TSK_TASK_PRIORITY pri,
  TSK_TASK_STATUS sta,
  TSK_TASK_CLASSIFIER cla,
  TSK_TASK_SUBCLASSIFIER subcla,
  TSK_TASK_MADE_BY madeby,
  TSK_TASK_COMMUNICATED_BY commby,
  DFEMP comp,
  DFEMP_CONTACT cont
where
  tsk.TPR_ID = pri.TPR_ID(+)
  and tsk.TKS_ID = sta.TKS_ID(+)
  and tsk.TKC_ID = cla.TKC_ID(+)
  and tsk.TSU_ID = subcla.TSU_ID(+)
  and tsk.CIF = comp.CIF(+)
  and tsk.ECN_ID = cont.ECN_ID(+)
  and tsk.TKM_ID = madeby.TKM_ID(+)
  and tsk.TKCM_ID = commby.TKCM_ID(+);

  
  
  
ALTER TABLE CDRESTRICCIONES ADD IDTIPO_AMBITO	NUMBER;
ALTER TABLE CDRESTRICCIONES ADD MMA	VARCHAR2(10);
--ALTER TABLE CDRESTRICCIONES ADD POBL_INICIAL VARCHAR2(255);
--ALTER TABLE CDRESTRICCIONES ADD POBL_FINAL VARCHAR2(255);

 CREATE OR REPLACE VIEW CDVRESTRICCIONES AS 
  (
SELECT 
CDRESTRICCIONES.IDRESTRICCION,
CDRESTRICCIONES.IDTIPO_RESTRICCION,
CDRESTRICCIONES.CARRETERA,
CDRESTRICCIONES.PK_INICIAL,
CDRESTRICCIONES.CG_PROV_INICIAL,
CDRESTRICCIONES.PK_FINAL,
CDRESTRICCIONES.CG_PROV_FINAL,
CDRESTRICCIONES.F_INICIAL,
CDRESTRICCIONES.F_FINAL,
CDRESTRICCIONES.SENTIDO,
CDRESTRICCIONES.F_ALTA,
CDRESTRICCIONES.POBL_INICIAL,
CDRESTRICCIONES.POBL_FINAL,
CDRESTRICCIONES.USUARIO_ALTA,
CDRESTRICCIONES.MMA,
CDTIPO_RESTRICCIONES.DSCR AS TIPO_RESTRICCION,
PV_INI.PROVINCIA AS PROVINCIA_INICIAL,
PV_FIN.PROVINCIA AS PROVINCIA_FINAL,
CDTIPO_AMBITO.IDTIPO_AMBITO,
CDTIPO_AMBITO.NOMBRE_AMBITO
FROM CDRESTRICCIONES, CDTIPO_RESTRICCIONES, CDTIPO_AMBITO,
(SELECT  CG_PROV, NOMB AS PROVINCIA  FROM PROVINCIAS )PV_INI, 
(SELECT  CG_PROV, NOMB AS PROVINCIA  FROM PROVINCIAS )PV_FIN
WHERE CDRESTRICCIONES.IDTIPO_RESTRICCION =CDTIPO_RESTRICCIONES.IDTIPO_RESTRICCION AND
CDTIPO_AMBITO.IDTIPO_AMBITO(+) = CDRESTRICCIONES.IDTIPO_AMBITO AND
PV_INI.CG_PROV =CDRESTRICCIONES.CG_PROV_INICIAL AND 
PV_FIN.CG_PROV =CDRESTRICCIONES.CG_PROV_FINAL);




-----NUEVOS INFORMES

create view CDVCONDUCTORES_AGENTE AS 
select 
 agentes.agente,  cdconductores_emp.idconductor, cdconductor_cont.f_alta, cdconductor_cont.f_baja
from ( select
    cdusu.usuario as agente,
    dfemp.nomb as empresa,
    dfemp.cif,
    dfemp.nomb
  from
    cdusu,
    cdusu_dfemp,
    dfemp
  where
    cdusu.usuario  =cdusu_dfemp.usuario
    and cdusu_dfemp.cif =dfemp.cif
    and cdusu.NIVEL_CD = (select nivel_cd from cdniveles where dscr = 'AGENTE')) agentes, cdconductores_emp, cdconductor_cont, cdvempre_req_reales 
where cdconductores_emp.cif = agentes.cif and 
cdvempre_req_reales.cif  = agentes.cif and
cdvempre_req_reales.numreq = cdconductor_cont.cg_contrato and
cdconductores_emp.idconductor = cdconductor_cont.idconductor 
order by agentes.nomb,cdconductor_cont.f_alta
;


create or replace view CDVVEHICULOS_AGENTE AS 
select 
 agentes.agente, agentes.cif, agentes.nomb, cdvehiculos_emp.dscr, cdvehiculos_emp.matricula, cdvehiculo_cont.f_alta, cdvehiculo_cont.f_baja
from ( select
    cdusu.usuario as agente,
    dfemp.nomb as empresa,
    dfemp.cif,
    dfemp.nomb
  from
    cdusu,
    cdusu_dfemp,
    dfemp
  where
    cdusu.usuario  =cdusu_dfemp.usuario
    and cdusu_dfemp.cif =dfemp.cif
    and cdusu.NIVEL_CD = (select nivel_cd from cdniveles where dscr = 'AGENTE')) agentes, cdvehiculos_emp, cdvehiculo_cont, cdvempre_req_reales 
where cdvehiculos_emp.cif = agentes.cif and 
cdvempre_req_reales.cif  = agentes.cif and
cdvempre_req_reales.numreq = cdvehiculo_cont.cg_contrato and
cdvehiculos_emp.matricula = cdvehiculo_cont.matricula 
order by agentes.nomb,cdvehiculo_cont.f_alta
;


 CREATE OR REPLACE VIEW CDVVEHICULOS_EMP AS
 SELECT CDVEHICULOS_EMP.CIF,
    EMPRE_REQ.NOMB,
    CDVEHICULOS_EMP.MATRICULA,
    CDVEHICULOS_EMP.DSCR,
    CDVEHICULOS_EMP.F_ALTA,
    CDVEHICULOS_EMP.USUARIO_ALTA,
    CDVEHICULOS_EMP.OBSR,
    CDVEHICULOS_EMP.IDDELEGACION,
    CDVEHICULOS_EMP.DURMIENTE,
    CDVEHICULO_CONT.F_BAJA,
    CDVEHICULOS_EMP.IDVEHICLETYPE,
	PROVINCIAS.CG_PROV,
	PROVINCIAS.NOMB AS PROVINCIA
  FROM CDVEHICULOS_EMP,
    CDVEHICULO_CONT,
     (SELECT
      CDEMPRE_REQ.CIF,
      CDEMPRE_REQ.NUMREQ,
      DFEMP.NOMB,
	  DFEMP.CG_PROV
      FROM CDEMPRE_REQ, DFEMP
      WHERE CDEMPRE_REQ.CIF = DFEMP.CIF AND  FICTICIO!='S' 
      UNION ALL
      SELECT
      DFEMP.CIF,
      EMP.NUMREQ,
      DFEMP.NOMB,
	  DFEMP.CG_PROV
      FROM CDEMPRE_REQ REQ ,DFEMP, CDEMPRE_REQ EMP, DFEMP DF2
      WHERE 
      REQ.CIF = DFEMP.CIF AND REQ.FICTICIO='S' AND DFEMP.CIF_COOPERATIVA = EMP.CIF AND DF2.CIF = REQ.CIF) EMPRE_REQ, PROVINCIAS
  WHERE CDVEHICULOS_EMP.CIF       = EMPRE_REQ.CIF
  AND CDVEHICULO_CONT.CG_CONTRATO =EMPRE_REQ.NUMREQ
  AND CDVEHICULOS_EMP.MATRICULA   = CDVEHICULO_CONT.MATRICULA
 AND PROVINCIAS.CG_PROV(+) = EMPRE_REQ.CG_PROV  ;
 
 
 
 
CREATE OR REPLACE VIEW CDVFLOTA AS
select 
dfemp.cif,dfemp.nomb, count(cdvehiculos_emp.matricula) as vehiculos
from dfemp, cdvehiculos_emp, cdvehiculo_cont, cdvempre_req_reales 
where 
cdvehiculos_emp.cif = dfemp.cif and 
cdvempre_req_reales.cif  = dfemp.cif and
cdvempre_req_reales.numreq = cdvehiculo_cont.cg_contrato and
cdvehiculos_emp.matricula = cdvehiculo_cont.matricula and
dfemp.flota_autom = 'S' and cdvehiculo_cont.f_baja is null
group by dfemp.cif,dfemp.nomb;


CREATE OR REPLACE VIEW CDVCONEXION_DESCARGAS AS
SELECT CDCDO.USUARIO, MAX(CDLOGSESION.F_INI) AS F_SESSION ,MAX(CDFICHEROS.F_ALTA) AS F_ULTIMO_FICH, 
COUNT (CDFICHEROS.IDFICHERO) AS NUM_FICHEROS
FROM CDLOGSESION, CDCDO, CDFICHEROS
WHERE CDLOGSESION.USUARIO = CDCDO.USUARIO
AND  CDCDO.USUARIO = CDFICHEROS.USUARIO_ALTA(+)
GROUP BY CDCDO.USUARIO
ORDER BY CDCDO.USUARIO