ALTER TABLE DFEMP RENAME COLUMN FLOTA_AUTOM TO FLOTA_AUTOM_OLD;
ALTER TABLE DFEMP ADD COND_AUTOM VARCHAR2(1);
ALTER TABLE DFEMP ADD VEH_AUTOM VARCHAR2(1);

UPDATE DFEMP SET COND_AUTOM = 'S', VEH_AUTOM='S' WHERE FLOTA_AUTOM_OLD = 'S';
COMMIT;

CREATE OR REPLACE VIEW CDVDFEMP AS 
  SELECT 
    DFEMP.CIF,
    DFEMP.NOMB,
    DFEMP.IS_DEMO,
    CG_EMPR,
    DOMI,
    CG_PROV,
    CG_MUNI,
    CG_POBL,
    CG_POSTAL,
    TELF,
    FAX,
    CIF_CO,
    F_FIN_HF,
    CL_PROR,
    IDENTIFICADOR,
    REGI_IDEN,
    TIPO_IDEN,
    F_ALTA,
    EMAIL,
    PAG_WEB,
    DFEMP.CG_NACI,
    DIRECCION,
    USUARIO_ALTA,
    F_MODIF,
    USUARIO_MODIF,
    MUNI,
    POBL,
    OBSR,
    TIPO,
    IDGRUPO,
    MOVIL,
    PCONTACTO,
    MCONTACTO,
    LOCALE,
    MAILINFORMEANALISIS,
    PAIS.DSCR    AS PAIS,
    PAIS.PREFIJO AS PREFIJO,
    COND_AUTOM,
    VEH_AUTOM,
    IS_COOPERATIVA,
    DFEMP.CIF_COOPERATIVA,
    CONTRATO_COOP,
    DFEMP.TDI,
    DFEMP.TDI_IP,
    DFEMP.TDI_PORT,
    DFEMP.TDI_USER,
    DFEMP.TDI_PASS,
    DFEMP.TDI_GROUPID,
    DFEMP.CCC,
    DFEMP.SYNCH,
    DFEMP.F_LAST_SYNCH
FROM 
    DFEMP,
    PAIS
WHERE 
    DFEMP.CG_NACI = PAIS.CG_NACI (+);
    
    
    
    

  CREATE OR REPLACE VIEW CDVDFEMP_COOP AS 
  SELECT 
	CIF,
	NOMB,
	CG_EMPR,
	DOMI,
	CG_PROV,
	CG_MUNI,
	CG_POBL,
	CG_POSTAL,
	TELF,
	FAX,
	CIF_CO,
	F_FIN_HF,
	CL_PROR,
	IDENTIFICADOR,
	REGI_IDEN,
	TIPO_IDEN,
	F_ALTA,
	EMAIL,
	PAG_WEB,
	DFEMP.CG_NACI,
	DIRECCION,
	USUARIO_ALTA,
	F_MODIF,
	USUARIO_MODIF,
	MUNI,
	POBL,
	OBSR,
	TIPO,
	IDGRUPO,
	MOVIL,
	PCONTACTO,
	MCONTACTO,
	LOCALE,
	MAILINFORMEANALISIS,
	PAIS.DSCR    AS PAIS,
	PAIS.PREFIJO AS PREFIJO,
	COND_AUTOM,
    VEH_AUTOM,
	IS_COOPERATIVA,
	NULL AS CIF_COOPERATIVA,
	CONTRATO_COOP
FROM 
	DFEMP,
	PAIS
WHERE 
	DFEMP.CG_NACI = PAIS.CG_NACI (+) 
	AND (IS_COOPERATIVA = 'S' OR CIF_COOPERATIVA IS NULL);

    
    
 
 
 
  
  CREATE OR REPLACE VIEW CDVDFEMP_NO_COOP AS 
  SELECT 
	DFEMP.CIF,
	DFEMP.NOMB,
	DFEMP.CG_EMPR,
	DFEMP.DOMI,
	DFEMP.CG_PROV,
	DFEMP.CG_MUNI,
	DFEMP.CG_POBL,
	DFEMP.CG_POSTAL,
	DFEMP.TELF,
	DFEMP.FAX,
	DFEMP.CIF_CO,
	DFEMP.F_FIN_HF,
	DFEMP.CL_PROR,
	DFEMP.IDENTIFICADOR,
	DFEMP.REGI_IDEN,
	DFEMP.TIPO_IDEN,
	DFEMP.F_ALTA,
	DFEMP.EMAIL,
	DFEMP.PAG_WEB,
	DFEMP.CG_NACI,
	DFEMP.DIRECCION,
	DFEMP.USUARIO_ALTA,
	DFEMP.F_MODIF,
	DFEMP.USUARIO_MODIF,
	DFEMP.MUNI,
	DFEMP.POBL,
	DFEMP.OBSR,
	DFEMP.TIPO,
	DFEMP.IDGRUPO,
	DFEMP.MOVIL,
	DFEMP.PCONTACTO,
	DFEMP.MCONTACTO,
	DFEMP.LOCALE,
	DFEMP.MAILINFORMEANALISIS,
	PAIS.DSCR    AS PAIS,
	PAIS.PREFIJO AS PREFIJO,
	DFEMP.COND_AUTOM,
    DFEMP.VEH_AUTOM,
	DFEMP.IS_COOPERATIVA,
	DFEMP.CIF_COOPERATIVA,
	NVL((SELECT D.NOMB FROM DFEMP D WHERE D.CIF = DFEMP.CIF_COOPERATIVA), NULL) AS NOMB_COOP,
	DFEMP.CONTRATO_COOP
FROM 
	DFEMP, 
	PAIS
WHERE 
	DFEMP.CG_NACI = PAIS.CG_NACI(+) 
	AND (DFEMP.IS_COOPERATIVA = 'N');


 CREATE OR REPLACE VIEW CDVEMPRE_REQ_REALES AS 
  SELECT  
  CDEMPRE_REQ.NUMREQ,
  CDEMPRE_REQ.CIF,
  DFEMP.NOMB,
  CDEMPRE_REQ.IDINSPECCION,
  CDEMPRE_REQ.F_REQ,
  CDEMPRE_REQ.USUARIO_ALTA,
  CDEMPRE_REQ.F_ALTA,
  CDEMPRE_REQ.F_MODIF,
  CDEMPRE_REQ.USUARIO_MODIF,
  CDEMPRE_REQ.F_BAJA,
  CDEMPRE_REQ.CG_ORGA,
  CDEMPRE_REQ.FECINI AS FECINID,
  CDEMPRE_REQ.FECFIN AS FECFIND,
  CDEMPRE_REQ.AVISO_EXPIRACION,
  CDEMPRE_REQ.CG_CONTRATO,
  CDEMPRE_REQ.F_CONTRATO,
  CDEMPRE_REQ.MAX_COND,
  CDEMPRE_REQ.MAX_VEH,
  DFEMP.COND_AUTOM,
  DFEMP.VEH_AUTOM,
  CDEMPRE_REQ.TERMDATEDEMO,
  CDEMPRE_REQ.ENDDATEDEMO,
  CDEMPRE_REQ.F_ANULACION
FROM CDEMPRE_REQ, DFEMP WHERE CDEMPRE_REQ.CIF = DFEMP.CIF 
AND FICTICIO = 'N'
UNION ALL
SELECT   
  CDEMPRE_REQ.NUMREQ,
  DFEMP_FIC.CIF,
  DFEMP_FIC.NOMB,
  CDEMPRE_REQ.IDINSPECCION,
  CDEMPRE_REQ.F_REQ,
  CDEMPRE_REQ.USUARIO_ALTA,
  CDEMPRE_REQ.F_ALTA,
  CDEMPRE_REQ.F_MODIF,
  CDEMPRE_REQ.USUARIO_MODIF,
  CDEMPRE_REQ.F_BAJA,
  CDEMPRE_REQ.CG_ORGA,
  CDEMPRE_REQ.FECINI AS FECINID,
  CDEMPRE_REQ.FECFIN AS FECFIND,
  CDEMPRE_REQ.AVISO_EXPIRACION,
  CDEMPRE_REQ.CG_CONTRATO,
  CDEMPRE_REQ.F_CONTRATO,
  CDEMPRE_REQ.MAX_COND,
  CDEMPRE_REQ.MAX_VEH,
  DFEMP_FIC.COND_AUTOM,
  DFEMP_FIC.VEH_AUTOM,
  CDEMPRE_REQ.TERMDATEDEMO,
  CDEMPRE_REQ.ENDDATEDEMO,
  CDEMPRE_REQ.F_ANULACION
  FROM CDEMPRE_REQ, (SELECT DFEMP.CIF, DFEMP.NOMB,CIF_COOPERATIVA, NUMREQ,COND_AUTOM, VEH_AUTOM FROM CDEMPRE_REQ, DFEMP WHERE CDEMPRE_REQ.CIF = DFEMP.CIF AND FICTICIO='S')DFEMP_FIC
  WHERE FICTICIO='N'  AND DFEMP_FIC.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND CIF_COOPERATIVA IS NOT NULL AND F_BAJA IS NULL;

 
  CREATE OR REPLACE VIEW CDVCONTRATO_EMPRESA AS 
  SELECT 
	(case when DFEMP.CONTRATO_COOP='S' then ( SELECT  CDEMPRE_REQ.NUMREQ  FROM DFEMP DF, CDEMPRE_REQ WHERE DF.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND CDEMPRE_REQ.F_BAJA IS NULL AND DFEMP.CIF = DF.CIF) else CDEMPRE_REQ.NUMREQ end) as NUMREQ,
	(case when DFEMP.CONTRATO_COOP='S' then ( SELECT  CDEMPRE_REQ.NUMREQ  FROM DFEMP DF, CDEMPRE_REQ WHERE DF.CIF_COOPERATIVA = CDEMPRE_REQ.CIF AND CDEMPRE_REQ.F_BAJA IS NULL AND DFEMP.CIF = DF.CIF) else CDEMPRE_REQ.NUMREQ end) as CG_CONTRATO,	
	CDEMPRE_REQ.F_CONTRATO,
	DFEMP.CIF,
	CDEMPRE_REQ.IDINSPECCION,
	CDEMPRE_REQ.F_REQ,
	CDEMPRE_REQ.USUARIO_ALTA,
	CDEMPRE_REQ.F_ALTA,
	CDEMPRE_REQ.F_ANULACION,
	CDEMPRE_REQ.USUARIO_MODIF,
	CDEMPRE_REQ.F_MODIF,
	CDEMPRE_REQ.F_BAJA,
	DFEMP.NOMB,
	DFEMP.NOMB as NOMB_EMP,
	TO_CHAR(CDEMPRE_REQ.FECINID,'DD/MM/YYYY')||' - '|| TO_CHAR(CDEMPRE_REQ.FECFIND,'DD/MM/YYYY') AS NOMBRECOMPLETO,
	CDEMPRE_REQ.CG_ORGA,
	CDEMPRE_REQ.AVISO_EXPIRACION,
	CDEMPRE_REQ.FECINID AS FECINI,
	CDEMPRE_REQ.FECFIND AS FECFIN,
	CDEMPRE_REQ.MAX_COND,
	CDEMPRE_REQ.MAX_VEH,	
	CDEMPRE_REQ.TERMDATEDEMO,
	CDEMPRE_REQ.ENDDATEDEMO,
	DFEMP.COND_AUTOM,
    DFEMP.VEH_AUTOM
FROM 	
	DFEMP,
	cdvempre_req_reales CDEMPRE_REQ
WHERE 
	DFEMP.CIF = CDEMPRE_REQ.CIF AND
	CDEMPRE_REQ.F_BAJA IS NULL 
UNION ALL
select 
	CDEMPRE_REQ.NUMREQ,
	CDEMPRE_REQ.CG_CONTRATO,
	CDEMPRE_REQ.F_CONTRATO,
	CDEMPRE_REQ.CIF,
	CDEMPRE_REQ.IDINSPECCION,
	CDEMPRE_REQ.F_REQ,
	CDEMPRE_REQ.USUARIO_ALTA,
	CDEMPRE_REQ.F_ALTA,
	CDEMPRE_REQ.F_ANULACION,
	CDEMPRE_REQ.USUARIO_MODIF,
	CDEMPRE_REQ.F_MODIF,
	CDEMPRE_REQ.F_BAJA,
	DFEMP.NOMB,
	DFEMP.NOMB as NOMB_EMP,	
	TO_CHAR(CDEMPRE_REQ.FECINI,'DD/MM/YYYY')||' - '|| TO_CHAR(CDEMPRE_REQ.FECFIN,'DD/MM/YYYY') AS NOMBRECOMPLETO,
	CDEMPRE_REQ.CG_ORGA,
	CDEMPRE_REQ.AVISO_EXPIRACION,
	CDEMPRE_REQ.FECINI,
	CDEMPRE_REQ.FECFIN,
	CDEMPRE_REQ.MAX_COND,
	CDEMPRE_REQ.MAX_VEH,	
	CDEMPRE_REQ.TERMDATEDEMO,
	CDEMPRE_REQ.ENDDATEDEMO,
	DFEMP.COND_AUTOM,
    DFEMP.VEH_AUTOM
from 
	CDEMPRE_REQ, 
	DFEMP
where
	CDEMPRE_REQ.CIF = DFEMP.CIF AND 
	CDEMPRE_REQ.F_BAJA IS NOT NULL AND
	(CONTRATO_COOP IS NULL OR CONTRATO_COOP = 'N');  
  

CREATE OR REPLACE VIEW CDVVEHICULO_CONT_VALIDO AS
SELECT A.CG_CONTRATO,  
  A.MATRICULA,
  A.F_ALTA,
  A.F_BAJA,
  A.USUARIO_ALTA,
  CDVEHICULOS_EMP.DSCR,
  CDVEHICULOS_EMP.CIF,
  CDVEHICULOS_EMP.IDDELEGACION
FROM
(SELECT 
  CDVEHICULO_CONT.MATRICULA,
  CDVEHICULO_CONT.F_ALTA,
  CDVEHICULO_CONT.F_BAJA,
  CDVEHICULO_CONT.USUARIO_ALTA,
  CDEMPRE_REQ.CIF,
  CDVEHICULO_CONT.CG_CONTRATO
FROM  CDVEHICULO_CONT,  CDEMPRE_REQ
WHERE CDVEHICULO_CONT.CG_CONTRATO =  CDEMPRE_REQ.CG_CONTRATO
AND  CDEMPRE_REQ.F_BAJA IS NULL
) A, CDVEHICULOS_EMP 
WHERE A.MATRICULA = CDVEHICULOS_EMP.MATRICULA(+)
  AND A.CIF       = CDVEHICULOS_EMP.CIF(+)
  AND CDVEHICULOS_EMP.MATRICULA IS NOT NULL
  AND A.F_BAJA IS NULL;
  

  
  DROP VIEW CDVEMPRE_REQ;
  



  CREATE OR REPLACE VIEW CDVEMPRE_REQ_PROPIOS AS 
  SELECT
	CDEMPRE_REQ.NUMREQ,
	CDEMPRE_REQ.CIF,
	IDINSPECCION,
	F_REQ,
	TP_EMPRESA,
	COD_AGENTE,
	AMBITO,REGULAR,
	CDEMPRE_REQ.USUARIO_ALTA,
	CDEMPRE_REQ.F_ALTA,
	F_CARGADATOS,
	F_ANALISIS,
	F_ANULACION,
	ACTIVIDAD,
	NUM_COPIAS,
	CDEMPRE_REQ.F_MODIF,
	NIF_INSPEC,
	CDEMPRE_REQ.USUARIO_MODIF,
	CDEMPRE_REQ.NOMB,
	GRUPO,
	F_BAJA,
	AREA,
	PROCEDENCIA,
	CG_ORGA,
	FECFIN,
	FECINI,
	CG_RENOVACION,
	AVISO_EXPIRACION,
	CG_CONTRATO,
	F_CONTRATO,
	MAX_COND,
	MAX_VEH,
	CDEMPRE_REQ.TIPO,
	DFEMP.COND_AUTOM,
    DFEMP.VEH_AUTOM,
	TO_CHAR(CDEMPRE_REQ.FECINI,'DD/MM/YYYY')||' - '|| TO_CHAR(CDEMPRE_REQ.FECFIN,'DD/MM/YYYY') AS NOMBRECOMPLETO,
	CDEMPRE_REQ.ITEMCODE,
	CDEMPRE_REQ.U_CODE_CARGADOR,
	SITCONTRACT,
	CDEMPRE_REQ.ENTREPRISE_CODE,
	CDEMPRE_REQ.STATUS,
	CDEMPRE_REQ.U_CODE_COMERCIAL,
	CDEMPRE_REQ.U_CODE_AGENTE,
	U_CODE_FACTURACION,
	CDEMPRE_REQ.U_CODE_PAGO,
	TERMDATEDEMO,
	ENDDATEDEMO,
	REMARKS2,
	U_NUM_MAXIMO,
	U_CUOTA,
	DFEMP.NOMB as NOMB_EMP
FROM 
	CDEMPRE_REQ,
	DFEMP
WHERE 
	CDEMPRE_REQ.CIF = DFEMP.CIF AND 
	FICTICIO='N';

  
  
  