
package com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2018-06-20T10:59:16.086+02:00
 * Generated source version: 3.2.0
 * 
 */
public final class IWsJaltestTelematicsAPI_BasicHttpBindingIWsJaltestTelematicsAPI_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "WsJaltestTelematicsAPI");

    private IWsJaltestTelematicsAPI_BasicHttpBindingIWsJaltestTelematicsAPI_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsJaltestTelematicsAPI.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsJaltestTelematicsAPI ss = new WsJaltestTelematicsAPI(wsdlURL, SERVICE_NAME);
        IWsJaltestTelematicsAPI port = ss.getBasicHttpBindingIWsJaltestTelematicsAPI();  
        
        {
        System.out.println("Invoking generateCompanyTachographCard...");
        java.lang.String _generateCompanyTachographCard_cif = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfString _generateCompanyTachographCard__return = port.generateCompanyTachographCard(_generateCompanyTachographCard_cif);
        System.out.println("generateCompanyTachographCard.result=" + _generateCompanyTachographCard__return);


        }
        {
        System.out.println("Invoking getVehicles...");
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _getVehicles__return = port.getVehicles();
        System.out.println("getVehicles.result=" + _getVehicles__return);


        }
        {
        System.out.println("Invoking createDriver...");
        java.lang.String _createDriver_cif = "";
        java.lang.String _createDriver_name = "";
        java.lang.String _createDriver_surnames = "";
        java.lang.String _createDriver_dni = "";
        java.lang.String _createDriver_notificationsPhone = "";
        java.lang.String _createDriver_homePhone = "";
        java.lang.String _createDriver_address = "";
        java.lang.String _createDriver_email = "";
        java.lang.String _createDriver_tachographCardCountry = "";
        java.lang.String _createDriver_tachographCardNumber = "";
        java.lang.String _createDriver_tachographCardExpirationDate = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResult _createDriver__return = port.createDriver(_createDriver_cif, _createDriver_name, _createDriver_surnames, _createDriver_dni, _createDriver_notificationsPhone, _createDriver_homePhone, _createDriver_address, _createDriver_email, _createDriver_tachographCardCountry, _createDriver_tachographCardNumber, _createDriver_tachographCardExpirationDate);
        System.out.println("createDriver.result=" + _createDriver__return);


        }
        {
        System.out.println("Invoking setTachoScheduleForVehicle...");
        java.lang.String _setTachoScheduleForVehicle_cif = "";
        java.lang.String _setTachoScheduleForVehicle_numberPlate = "";
        boolean _setTachoScheduleForVehicle_firstDayOfMonth = false;
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfTachoScheduleInfo _setTachoScheduleForVehicle__return = port.setTachoScheduleForVehicle(_setTachoScheduleForVehicle_cif, _setTachoScheduleForVehicle_numberPlate, _setTachoScheduleForVehicle_firstDayOfMonth);
        System.out.println("setTachoScheduleForVehicle.result=" + _setTachoScheduleForVehicle__return);


        }
        {
        System.out.println("Invoking createNewFleet...");
        java.lang.String _createNewFleet_name = "";
        java.lang.String _createNewFleet_cif = "";
        java.lang.String _createNewFleet_address = "";
        java.lang.String _createNewFleet_phone = "";
        java.lang.String _createNewFleet_email = "";
        int _createNewFleet_distributorId = 0;
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.ContractInfo _createNewFleet_contractInfo = null;
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResult _createNewFleet__return = port.createNewFleet(_createNewFleet_name, _createNewFleet_cif, _createNewFleet_address, _createNewFleet_phone, _createNewFleet_email, _createNewFleet_distributorId, _createNewFleet_contractInfo);
        System.out.println("createNewFleet.result=" + _createNewFleet__return);


        }
        {
        System.out.println("Invoking downloadTachoFiles...");
        java.lang.String _downloadTachoFiles_cif = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.ArrayOfInt _downloadTachoFiles_fileIds = null;
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.TachoFileExtension _downloadTachoFiles_extensionFile = null;
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfListOfTachoFileInfo _downloadTachoFiles__return = port.downloadTachoFiles(_downloadTachoFiles_cif, _downloadTachoFiles_fileIds, _downloadTachoFiles_extensionFile);
        System.out.println("downloadTachoFiles.result=" + _downloadTachoFiles__return);


        }
        {
        System.out.println("Invoking createVehicle...");
        java.lang.String _createVehicle_cif = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.VehicleType _createVehicle_vehicleType = null;
        java.lang.String _createVehicle_numberPlate = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResult _createVehicle__return = port.createVehicle(_createVehicle_cif, _createVehicle_vehicleType, _createVehicle_numberPlate);
        System.out.println("createVehicle.result=" + _createVehicle__return);


        }
        {
        System.out.println("Invoking getInfoDay...");
        java.lang.String _getInfoDay_dateInfo = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _getInfoDay__return = port.getInfoDay(_getInfoDay_dateInfo);
        System.out.println("getInfoDay.result=" + _getInfoDay__return);


        }
        {
        System.out.println("Invoking setTachoScheduleForDriver...");
        java.lang.String _setTachoScheduleForDriver_cif = "";
        java.lang.String _setTachoScheduleForDriver_driverCardNumber = "";
        int _setTachoScheduleForDriver_weekDay = 0;
        int _setTachoScheduleForDriver_hour = 0;
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfTachoScheduleInfo _setTachoScheduleForDriver__return = port.setTachoScheduleForDriver(_setTachoScheduleForDriver_cif, _setTachoScheduleForDriver_driverCardNumber, _setTachoScheduleForDriver_weekDay, _setTachoScheduleForDriver_hour);
        System.out.println("setTachoScheduleForDriver.result=" + _setTachoScheduleForDriver__return);


        }
        {
        System.out.println("Invoking startCardDriverDownload...");
        java.lang.String _startCardDriverDownload_cif = "";
        java.lang.String _startCardDriverDownload_driverCardNumber = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfTachoDownloadInfo _startCardDriverDownload__return = port.startCardDriverDownload(_startCardDriverDownload_cif, _startCardDriverDownload_driverCardNumber);
        System.out.println("startCardDriverDownload.result=" + _startCardDriverDownload__return);


        }
        {
        System.out.println("Invoking setMessageKey...");
        java.lang.String _setMessageKey_login = "";
        java.lang.String _setMessageKey_password = "";
        java.lang.Integer _setMessageKey_idUsuarioWeb = null;
        java.lang.String _setMessageKey_key = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telapidto.WebResult _setMessageKey__return = port.setMessageKey(_setMessageKey_login, _setMessageKey_password, _setMessageKey_idUsuarioWeb, _setMessageKey_key);
        System.out.println("setMessageKey.result=" + _setMessageKey__return);


        }
        {
        System.out.println("Invoking saveUnidentifiedDriving...");
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.ConduccionNoIdentificadaELDDto _saveUnidentifiedDriving_unidentifiedDrivingToSave = null;
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _saveUnidentifiedDriving__return = port.saveUnidentifiedDriving(_saveUnidentifiedDriving_unidentifiedDrivingToSave);
        System.out.println("saveUnidentifiedDriving.result=" + _saveUnidentifiedDriving__return);


        }
        {
        System.out.println("Invoking saveSignature...");
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.FirmaELDDto _saveSignature_signatureToSave = null;
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _saveSignature__return = port.saveSignature(_saveSignature_signatureToSave);
        System.out.println("saveSignature.result=" + _saveSignature__return);


        }
        {
        System.out.println("Invoking saveInfoDay...");
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.RegistroELDDto _saveInfoDay_recordToSave = null;
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _saveInfoDay__return = port.saveInfoDay(_saveInfoDay_recordToSave);
        System.out.println("saveInfoDay.result=" + _saveInfoDay__return);


        }
        {
        System.out.println("Invoking getCicles...");
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _getCicles__return = port.getCicles();
        System.out.println("getCicles.result=" + _getCicles__return);


        }
        {
        System.out.println("Invoking saveEvents...");
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.ArrayOfEventoELDDto _saveEvents_eventsToSave = null;
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _saveEvents__return = port.saveEvents(_saveEvents_eventsToSave);
        System.out.println("saveEvents.result=" + _saveEvents__return);


        }
        {
        System.out.println("Invoking getGeneralInfo...");
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _getGeneralInfo__return = port.getGeneralInfo();
        System.out.println("getGeneralInfo.result=" + _getGeneralInfo__return);


        }
        {
        System.out.println("Invoking getVehicleLocations...");
        java.lang.String _getVehicleLocations_cif = "";
        java.lang.String _getVehicleLocations_numberPlate = "";
        java.lang.String _getVehicleLocations_startDate = "";
        java.lang.String _getVehicleLocations_endDate = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfListOfGPSPositionInfo _getVehicleLocations__return = port.getVehicleLocations(_getVehicleLocations_cif, _getVehicleLocations_numberPlate, _getVehicleLocations_startDate, _getVehicleLocations_endDate);
        System.out.println("getVehicleLocations.result=" + _getVehicleLocations__return);


        }
        {
        System.out.println("Invoking startTachoDownload...");
        java.lang.String _startTachoDownload_cif = "";
        java.lang.String _startTachoDownload_numberPlate = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.ActivityBlockDownloadType _startTachoDownload_activityBlockDownloadType = null;
        java.lang.String _startTachoDownload_startDate = "";
        java.lang.String _startTachoDownload_endDate = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfTachoDownloadInfo _startTachoDownload__return = port.startTachoDownload(_startTachoDownload_cif, _startTachoDownload_numberPlate, _startTachoDownload_activityBlockDownloadType, _startTachoDownload_startDate, _startTachoDownload_endDate);
        System.out.println("startTachoDownload.result=" + _startTachoDownload__return);


        }
        {
        System.out.println("Invoking createWebUser...");
        java.lang.String _createWebUser_cif = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebUserType _createWebUser_webUserType = null;
        java.lang.String _createWebUser_name = "";
        java.lang.String _createWebUser_surnames = "";
        java.lang.String _createWebUser_login = "";
        java.lang.String _createWebUser_email = "";
        java.lang.String _createWebUser_country = "";
        java.lang.String _createWebUser_language = "";
        java.lang.String _createWebUser_mobilePhone = "";
        java.lang.String _createWebUser_dni = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResult _createWebUser__return = port.createWebUser(_createWebUser_cif, _createWebUser_webUserType, _createWebUser_name, _createWebUser_surnames, _createWebUser_login, _createWebUser_email, _createWebUser_country, _createWebUser_language, _createWebUser_mobilePhone, _createWebUser_dni);
        System.out.println("createWebUser.result=" + _createWebUser__return);


        }
        {
        System.out.println("Invoking getTachoFilesList...");
        java.lang.String _getTachoFilesList_cif = "";
        java.lang.String _getTachoFilesList_numberPlate = "";
        java.lang.String _getTachoFilesList_driverCardNumber = "";
        java.lang.String _getTachoFilesList_downloadStartDate = "";
        java.lang.String _getTachoFilesList_downloadEndDate = "";
        boolean _getTachoFilesList_activityBlock = false;
        boolean _getTachoFilesList_eventBlock = false;
        boolean _getTachoFilesList_detailedSpeedBlock = false;
        boolean _getTachoFilesList_technicalDataBlock = false;
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfListOfTachoFileInfo _getTachoFilesList__return = port.getTachoFilesList(_getTachoFilesList_cif, _getTachoFilesList_numberPlate, _getTachoFilesList_driverCardNumber, _getTachoFilesList_downloadStartDate, _getTachoFilesList_downloadEndDate, _getTachoFilesList_activityBlock, _getTachoFilesList_eventBlock, _getTachoFilesList_detailedSpeedBlock, _getTachoFilesList_technicalDataBlock);
        System.out.println("getTachoFilesList.result=" + _getTachoFilesList__return);


        }
        {
        System.out.println("Invoking sendMailDOT...");
        java.lang.String _sendMailDOT_recipientEmail = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _sendMailDOT__return = port.sendMailDOT(_sendMailDOT_recipientEmail);
        System.out.println("sendMailDOT.result=" + _sendMailDOT__return);


        }
        {
        System.out.println("Invoking getAccessELD...");
        java.lang.String _getAccessELD_login = "";
        java.lang.String _getAccessELD_password = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _getAccessELD__return = port.getAccessELD(_getAccessELD_login, _getAccessELD_password);
        System.out.println("getAccessELD.result=" + _getAccessELD__return);


        }
        {
        System.out.println("Invoking setGPSPosition...");
        java.lang.Integer _setGPSPosition_webUserId = null;
        java.lang.String _setGPSPosition_mobileKey = "";
        java.lang.String _setGPSPosition_gpsPosition = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telapidto.WebResult _setGPSPosition__return = port.setGPSPosition(_setGPSPosition_webUserId, _setGPSPosition_mobileKey, _setGPSPosition_gpsPosition);
        System.out.println("setGPSPosition.result=" + _setGPSPosition__return);


        }
        {
        System.out.println("Invoking getCandidates...");
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _getCandidates__return = port.getCandidates();
        System.out.println("getCandidates.result=" + _getCandidates__return);


        }
        {
        System.out.println("Invoking getAccess...");
        java.lang.String _getAccess_login = "";
        java.lang.String _getAccess_password = "";
        java.lang.String _getAccess_mobileKey = "";
        java.lang.String _getAccess_mobileUuid = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telapidto.WebResultOfUsuarioWebDto1YD7O3EO _getAccess__return = port.getAccess(_getAccess_login, _getAccess_password, _getAccess_mobileKey, _getAccess_mobileUuid);
        System.out.println("getAccess.result=" + _getAccess__return);


        }
        {
        System.out.println("Invoking confirmCandidate...");
        java.lang.Integer _confirmCandidate_idCandidate = null;
        java.lang.Boolean _confirmCandidate_confirm = null;
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _confirmCandidate__return = port.confirmCandidate(_confirmCandidate_idCandidate, _confirmCandidate_confirm);
        System.out.println("confirmCandidate.result=" + _confirmCandidate__return);


        }
        {
        System.out.println("Invoking getSignature...");
        java.lang.String _getSignature_id = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _getSignature__return = port.getSignature(_getSignature_id);
        System.out.println("getSignature.result=" + _getSignature__return);


        }
        {
        System.out.println("Invoking getDriver...");
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _getDriver__return = port.getDriver();
        System.out.println("getDriver.result=" + _getDriver__return);


        }
        {
        System.out.println("Invoking setTelematicsUnitToVehicle...");
        java.lang.String _setTelematicsUnitToVehicle_cif = "";
        java.lang.String _setTelematicsUnitToVehicle_telematicsUnitNumber = "";
        java.lang.String _setTelematicsUnitToVehicle_numberPlate = "";
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResult _setTelematicsUnitToVehicle__return = port.setTelematicsUnitToVehicle(_setTelematicsUnitToVehicle_cif, _setTelematicsUnitToVehicle_telematicsUnitNumber, _setTelematicsUnitToVehicle_numberPlate);
        System.out.println("setTelematicsUnitToVehicle.result=" + _setTelematicsUnitToVehicle__return);


        }
        {
        System.out.println("Invoking updateSettings...");
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.ConductorELDDto _updateSettings_newSettings = null;
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD _updateSettings__return = port.updateSettings(_updateSettings_newSettings);
        System.out.println("updateSettings.result=" + _updateSettings__return);


        }

        System.exit(0);
    }

}
