package com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2018-06-20T10:59:16.152+02:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IWsJaltestTelematicsAPI")
@XmlSeeAlso({com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telcliconstanteseld.ObjectFactory.class, com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.ObjectFactory.class, com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.serialization.ObjectFactory.class, com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telmanagecomunconstants.ObjectFactory.class, ObjectFactory.class, com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.system.ObjectFactory.class, com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.gesttelematica.telmanagecomunwebuser.ObjectFactory.class, com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telapidto.ObjectFactory.class})
public interface IWsJaltestTelematicsAPI {

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/generateCompanyTachographCard")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/generateCompanyTachographCard", output = "http://tempuri.org/IWsJaltestTelematicsAPI/generateCompanyTachographCardResponse")
    @RequestWrapper(localName = "generateCompanyTachographCard", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GenerateCompanyTachographCard")
    @ResponseWrapper(localName = "generateCompanyTachographCardResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GenerateCompanyTachographCardResponse")
    @WebResult(name = "generateCompanyTachographCardResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfString generateCompanyTachographCard(
        @WebParam(name = "CIF", targetNamespace = "http://tempuri.org/")
        java.lang.String cif
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/getVehicles")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/getVehicles", output = "http://tempuri.org/IWsJaltestTelematicsAPI/getVehiclesResponse")
    @RequestWrapper(localName = "getVehicles", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetVehicles")
    @ResponseWrapper(localName = "getVehiclesResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetVehiclesResponse")
    @WebResult(name = "getVehiclesResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD getVehicles();

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/createDriver")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/createDriver", output = "http://tempuri.org/IWsJaltestTelematicsAPI/createDriverResponse")
    @RequestWrapper(localName = "createDriver", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.CreateDriver")
    @ResponseWrapper(localName = "createDriverResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.CreateDriverResponse")
    @WebResult(name = "createDriverResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResult createDriver(
        @WebParam(name = "CIF", targetNamespace = "http://tempuri.org/")
        java.lang.String cif,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        java.lang.String name,
        @WebParam(name = "surnames", targetNamespace = "http://tempuri.org/")
        java.lang.String surnames,
        @WebParam(name = "DNI", targetNamespace = "http://tempuri.org/")
        java.lang.String dni,
        @WebParam(name = "notificationsPhone", targetNamespace = "http://tempuri.org/")
        java.lang.String notificationsPhone,
        @WebParam(name = "homePhone", targetNamespace = "http://tempuri.org/")
        java.lang.String homePhone,
        @WebParam(name = "address", targetNamespace = "http://tempuri.org/")
        java.lang.String address,
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        java.lang.String email,
        @WebParam(name = "tachographCardCountry", targetNamespace = "http://tempuri.org/")
        java.lang.String tachographCardCountry,
        @WebParam(name = "tachographCardNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String tachographCardNumber,
        @WebParam(name = "tachographCardExpirationDate", targetNamespace = "http://tempuri.org/")
        java.lang.String tachographCardExpirationDate
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/setTachoScheduleForVehicle")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/setTachoScheduleForVehicle", output = "http://tempuri.org/IWsJaltestTelematicsAPI/setTachoScheduleForVehicleResponse")
    @RequestWrapper(localName = "setTachoScheduleForVehicle", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SetTachoScheduleForVehicle")
    @ResponseWrapper(localName = "setTachoScheduleForVehicleResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SetTachoScheduleForVehicleResponse")
    @WebResult(name = "setTachoScheduleForVehicleResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfTachoScheduleInfo setTachoScheduleForVehicle(
        @WebParam(name = "CIF", targetNamespace = "http://tempuri.org/")
        java.lang.String cif,
        @WebParam(name = "numberPlate", targetNamespace = "http://tempuri.org/")
        java.lang.String numberPlate,
        @WebParam(name = "firstDayOfMonth", targetNamespace = "http://tempuri.org/")
        boolean firstDayOfMonth
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/createNewFleet")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/createNewFleet", output = "http://tempuri.org/IWsJaltestTelematicsAPI/createNewFleetResponse")
    @RequestWrapper(localName = "createNewFleet", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.CreateNewFleet")
    @ResponseWrapper(localName = "createNewFleetResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.CreateNewFleetResponse")
    @WebResult(name = "createNewFleetResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResult createNewFleet(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        java.lang.String name,
        @WebParam(name = "CIF", targetNamespace = "http://tempuri.org/")
        java.lang.String cif,
        @WebParam(name = "address", targetNamespace = "http://tempuri.org/")
        java.lang.String address,
        @WebParam(name = "phone", targetNamespace = "http://tempuri.org/")
        java.lang.String phone,
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        java.lang.String email,
        @WebParam(name = "distributorId", targetNamespace = "http://tempuri.org/")
        int distributorId,
        @WebParam(name = "contractInfo", targetNamespace = "http://tempuri.org/")
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.ContractInfo contractInfo
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/downloadTachoFiles")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/downloadTachoFiles", output = "http://tempuri.org/IWsJaltestTelematicsAPI/downloadTachoFilesResponse")
    @RequestWrapper(localName = "downloadTachoFiles", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.DownloadTachoFiles")
    @ResponseWrapper(localName = "downloadTachoFilesResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.DownloadTachoFilesResponse")
    @WebResult(name = "downloadTachoFilesResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfListOfTachoFileInfo downloadTachoFiles(
        @WebParam(name = "CIF", targetNamespace = "http://tempuri.org/")
        java.lang.String cif,
        @WebParam(name = "fileIds", targetNamespace = "http://tempuri.org/")
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.ArrayOfInt fileIds,
        @WebParam(name = "extensionFile", targetNamespace = "http://tempuri.org/")
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.TachoFileExtension extensionFile
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/createVehicle")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/createVehicle", output = "http://tempuri.org/IWsJaltestTelematicsAPI/createVehicleResponse")
    @RequestWrapper(localName = "createVehicle", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.CreateVehicle")
    @ResponseWrapper(localName = "createVehicleResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.CreateVehicleResponse")
    @WebResult(name = "createVehicleResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResult createVehicle(
        @WebParam(name = "CIF", targetNamespace = "http://tempuri.org/")
        java.lang.String cif,
        @WebParam(name = "vehicleType", targetNamespace = "http://tempuri.org/")
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.VehicleType vehicleType,
        @WebParam(name = "numberPlate", targetNamespace = "http://tempuri.org/")
        java.lang.String numberPlate
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/getInfoDay")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/getInfoDay", output = "http://tempuri.org/IWsJaltestTelematicsAPI/getInfoDayResponse")
    @RequestWrapper(localName = "getInfoDay", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetInfoDay")
    @ResponseWrapper(localName = "getInfoDayResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetInfoDayResponse")
    @WebResult(name = "getInfoDayResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD getInfoDay(
        @WebParam(name = "dateInfo", targetNamespace = "http://tempuri.org/")
        java.lang.String dateInfo
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/setTachoScheduleForDriver")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/setTachoScheduleForDriver", output = "http://tempuri.org/IWsJaltestTelematicsAPI/setTachoScheduleForDriverResponse")
    @RequestWrapper(localName = "setTachoScheduleForDriver", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SetTachoScheduleForDriver")
    @ResponseWrapper(localName = "setTachoScheduleForDriverResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SetTachoScheduleForDriverResponse")
    @WebResult(name = "setTachoScheduleForDriverResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfTachoScheduleInfo setTachoScheduleForDriver(
        @WebParam(name = "CIF", targetNamespace = "http://tempuri.org/")
        java.lang.String cif,
        @WebParam(name = "driverCardNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String driverCardNumber,
        @WebParam(name = "weekDay", targetNamespace = "http://tempuri.org/")
        int weekDay,
        @WebParam(name = "hour", targetNamespace = "http://tempuri.org/")
        int hour
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/startCardDriverDownload")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/startCardDriverDownload", output = "http://tempuri.org/IWsJaltestTelematicsAPI/startCardDriverDownloadResponse")
    @RequestWrapper(localName = "startCardDriverDownload", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.StartCardDriverDownload")
    @ResponseWrapper(localName = "startCardDriverDownloadResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.StartCardDriverDownloadResponse")
    @WebResult(name = "startCardDriverDownloadResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfTachoDownloadInfo startCardDriverDownload(
        @WebParam(name = "CIF", targetNamespace = "http://tempuri.org/")
        java.lang.String cif,
        @WebParam(name = "driverCardNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String driverCardNumber
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/setMessageKey")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/setMessageKey", output = "http://tempuri.org/IWsJaltestTelematicsAPI/setMessageKeyResponse")
    @RequestWrapper(localName = "setMessageKey", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SetMessageKey")
    @ResponseWrapper(localName = "setMessageKeyResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SetMessageKeyResponse")
    @WebResult(name = "setMessageKeyResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telapidto.WebResult setMessageKey(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "idUsuarioWeb", targetNamespace = "http://tempuri.org/")
        java.lang.Integer idUsuarioWeb,
        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        java.lang.String key
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/saveUnidentifiedDriving")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/saveUnidentifiedDriving", output = "http://tempuri.org/IWsJaltestTelematicsAPI/saveUnidentifiedDrivingResponse")
    @RequestWrapper(localName = "saveUnidentifiedDriving", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SaveUnidentifiedDriving")
    @ResponseWrapper(localName = "saveUnidentifiedDrivingResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SaveUnidentifiedDrivingResponse")
    @WebResult(name = "saveUnidentifiedDrivingResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD saveUnidentifiedDriving(
        @WebParam(name = "unidentifiedDrivingToSave", targetNamespace = "http://tempuri.org/")
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.ConduccionNoIdentificadaELDDto unidentifiedDrivingToSave
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/saveSignature")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/saveSignature", output = "http://tempuri.org/IWsJaltestTelematicsAPI/saveSignatureResponse")
    @RequestWrapper(localName = "saveSignature", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SaveSignature")
    @ResponseWrapper(localName = "saveSignatureResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SaveSignatureResponse")
    @WebResult(name = "saveSignatureResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD saveSignature(
        @WebParam(name = "signatureToSave", targetNamespace = "http://tempuri.org/")
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.FirmaELDDto signatureToSave
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/saveInfoDay")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/saveInfoDay", output = "http://tempuri.org/IWsJaltestTelematicsAPI/saveInfoDayResponse")
    @RequestWrapper(localName = "saveInfoDay", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SaveInfoDay")
    @ResponseWrapper(localName = "saveInfoDayResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SaveInfoDayResponse")
    @WebResult(name = "saveInfoDayResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD saveInfoDay(
        @WebParam(name = "recordToSave", targetNamespace = "http://tempuri.org/")
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.RegistroELDDto recordToSave
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/getCicles")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/getCicles", output = "http://tempuri.org/IWsJaltestTelematicsAPI/getCiclesResponse")
    @RequestWrapper(localName = "getCicles", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetCicles")
    @ResponseWrapper(localName = "getCiclesResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetCiclesResponse")
    @WebResult(name = "getCiclesResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD getCicles();

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/saveEvents")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/saveEvents", output = "http://tempuri.org/IWsJaltestTelematicsAPI/saveEventsResponse")
    @RequestWrapper(localName = "saveEvents", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SaveEvents")
    @ResponseWrapper(localName = "saveEventsResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SaveEventsResponse")
    @WebResult(name = "saveEventsResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD saveEvents(
        @WebParam(name = "eventsToSave", targetNamespace = "http://tempuri.org/")
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.ArrayOfEventoELDDto eventsToSave
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/getGeneralInfo")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/getGeneralInfo", output = "http://tempuri.org/IWsJaltestTelematicsAPI/getGeneralInfoResponse")
    @RequestWrapper(localName = "getGeneralInfo", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetGeneralInfo")
    @ResponseWrapper(localName = "getGeneralInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetGeneralInfoResponse")
    @WebResult(name = "getGeneralInfoResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD getGeneralInfo();

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/getVehicleLocations")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/getVehicleLocations", output = "http://tempuri.org/IWsJaltestTelematicsAPI/getVehicleLocationsResponse")
    @RequestWrapper(localName = "getVehicleLocations", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetVehicleLocations")
    @ResponseWrapper(localName = "getVehicleLocationsResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetVehicleLocationsResponse")
    @WebResult(name = "getVehicleLocationsResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfListOfGPSPositionInfo getVehicleLocations(
        @WebParam(name = "CIF", targetNamespace = "http://tempuri.org/")
        java.lang.String cif,
        @WebParam(name = "numberPlate", targetNamespace = "http://tempuri.org/")
        java.lang.String numberPlate,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        java.lang.String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        java.lang.String endDate
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/startTachoDownload")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/startTachoDownload", output = "http://tempuri.org/IWsJaltestTelematicsAPI/startTachoDownloadResponse")
    @RequestWrapper(localName = "startTachoDownload", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.StartTachoDownload")
    @ResponseWrapper(localName = "startTachoDownloadResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.StartTachoDownloadResponse")
    @WebResult(name = "startTachoDownloadResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfTachoDownloadInfo startTachoDownload(
        @WebParam(name = "CIF", targetNamespace = "http://tempuri.org/")
        java.lang.String cif,
        @WebParam(name = "numberPlate", targetNamespace = "http://tempuri.org/")
        java.lang.String numberPlate,
        @WebParam(name = "activityBlockDownloadType", targetNamespace = "http://tempuri.org/")
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.ActivityBlockDownloadType activityBlockDownloadType,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        java.lang.String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        java.lang.String endDate
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/createWebUser")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/createWebUser", output = "http://tempuri.org/IWsJaltestTelematicsAPI/createWebUserResponse")
    @RequestWrapper(localName = "createWebUser", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.CreateWebUser")
    @ResponseWrapper(localName = "createWebUserResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.CreateWebUserResponse")
    @WebResult(name = "createWebUserResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResult createWebUser(
        @WebParam(name = "CIF", targetNamespace = "http://tempuri.org/")
        java.lang.String cif,
        @WebParam(name = "webUserType", targetNamespace = "http://tempuri.org/")
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebUserType webUserType,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        java.lang.String name,
        @WebParam(name = "surnames", targetNamespace = "http://tempuri.org/")
        java.lang.String surnames,
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        java.lang.String login,
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        java.lang.String email,
        @WebParam(name = "country", targetNamespace = "http://tempuri.org/")
        java.lang.String country,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        java.lang.String language,
        @WebParam(name = "mobilePhone", targetNamespace = "http://tempuri.org/")
        java.lang.String mobilePhone,
        @WebParam(name = "DNI", targetNamespace = "http://tempuri.org/")
        java.lang.String dni
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/getTachoFilesList")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/getTachoFilesList", output = "http://tempuri.org/IWsJaltestTelematicsAPI/getTachoFilesListResponse")
    @RequestWrapper(localName = "getTachoFilesList", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetTachoFilesList")
    @ResponseWrapper(localName = "getTachoFilesListResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetTachoFilesListResponse")
    @WebResult(name = "getTachoFilesListResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResultOfListOfTachoFileInfo getTachoFilesList(
        @WebParam(name = "CIF", targetNamespace = "http://tempuri.org/")
        java.lang.String cif,
        @WebParam(name = "numberPlate", targetNamespace = "http://tempuri.org/")
        java.lang.String numberPlate,
        @WebParam(name = "driverCardNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String driverCardNumber,
        @WebParam(name = "downloadStartDate", targetNamespace = "http://tempuri.org/")
        java.lang.String downloadStartDate,
        @WebParam(name = "downloadEndDate", targetNamespace = "http://tempuri.org/")
        java.lang.String downloadEndDate,
        @WebParam(name = "activityBlock", targetNamespace = "http://tempuri.org/")
        boolean activityBlock,
        @WebParam(name = "eventBlock", targetNamespace = "http://tempuri.org/")
        boolean eventBlock,
        @WebParam(name = "detailedSpeedBlock", targetNamespace = "http://tempuri.org/")
        boolean detailedSpeedBlock,
        @WebParam(name = "technicalDataBlock", targetNamespace = "http://tempuri.org/")
        boolean technicalDataBlock
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/sendMailDOT")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/sendMailDOT", output = "http://tempuri.org/IWsJaltestTelematicsAPI/sendMailDOTResponse")
    @RequestWrapper(localName = "sendMailDOT", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SendMailDOT")
    @ResponseWrapper(localName = "sendMailDOTResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SendMailDOTResponse")
    @WebResult(name = "sendMailDOTResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD sendMailDOT(
        @WebParam(name = "recipientEmail", targetNamespace = "http://tempuri.org/")
        java.lang.String recipientEmail
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/getAccessELD")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/getAccessELD", output = "http://tempuri.org/IWsJaltestTelematicsAPI/getAccessELDResponse")
    @RequestWrapper(localName = "getAccessELD", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetAccessELD")
    @ResponseWrapper(localName = "getAccessELDResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetAccessELDResponse")
    @WebResult(name = "getAccessELDResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD getAccessELD(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/setGPSPosition")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/setGPSPosition", output = "http://tempuri.org/IWsJaltestTelematicsAPI/setGPSPositionResponse")
    @RequestWrapper(localName = "setGPSPosition", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SetGPSPosition")
    @ResponseWrapper(localName = "setGPSPositionResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SetGPSPositionResponse")
    @WebResult(name = "setGPSPositionResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telapidto.WebResult setGPSPosition(
        @WebParam(name = "webUserId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer webUserId,
        @WebParam(name = "mobileKey", targetNamespace = "http://tempuri.org/")
        java.lang.String mobileKey,
        @WebParam(name = "gpsPosition", targetNamespace = "http://tempuri.org/")
        java.lang.String gpsPosition
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/getCandidates")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/getCandidates", output = "http://tempuri.org/IWsJaltestTelematicsAPI/getCandidatesResponse")
    @RequestWrapper(localName = "getCandidates", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetCandidates")
    @ResponseWrapper(localName = "getCandidatesResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetCandidatesResponse")
    @WebResult(name = "getCandidatesResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD getCandidates();

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/getAccess")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/getAccess", output = "http://tempuri.org/IWsJaltestTelematicsAPI/getAccessResponse")
    @RequestWrapper(localName = "getAccess", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetAccess")
    @ResponseWrapper(localName = "getAccessResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetAccessResponse")
    @WebResult(name = "getAccessResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telapidto.WebResultOfUsuarioWebDto1YD7O3EO getAccess(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "mobileKey", targetNamespace = "http://tempuri.org/")
        java.lang.String mobileKey,
        @WebParam(name = "mobile_uuid", targetNamespace = "http://tempuri.org/")
        java.lang.String mobileUuid
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/confirmCandidate")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/confirmCandidate", output = "http://tempuri.org/IWsJaltestTelematicsAPI/confirmCandidateResponse")
    @RequestWrapper(localName = "confirmCandidate", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.ConfirmCandidate")
    @ResponseWrapper(localName = "confirmCandidateResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.ConfirmCandidateResponse")
    @WebResult(name = "confirmCandidateResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD confirmCandidate(
        @WebParam(name = "idCandidate", targetNamespace = "http://tempuri.org/")
        java.lang.Integer idCandidate,
        @WebParam(name = "confirm", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean confirm
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/getSignature")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/getSignature", output = "http://tempuri.org/IWsJaltestTelematicsAPI/getSignatureResponse")
    @RequestWrapper(localName = "getSignature", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetSignature")
    @ResponseWrapper(localName = "getSignatureResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetSignatureResponse")
    @WebResult(name = "getSignatureResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD getSignature(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        java.lang.String id
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/getDriver")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/getDriver", output = "http://tempuri.org/IWsJaltestTelematicsAPI/getDriverResponse")
    @RequestWrapper(localName = "getDriver", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetDriver")
    @ResponseWrapper(localName = "getDriverResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.GetDriverResponse")
    @WebResult(name = "getDriverResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD getDriver();

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/setTelematicsUnitToVehicle")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/setTelematicsUnitToVehicle", output = "http://tempuri.org/IWsJaltestTelematicsAPI/setTelematicsUnitToVehicleResponse")
    @RequestWrapper(localName = "setTelematicsUnitToVehicle", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SetTelematicsUnitToVehicle")
    @ResponseWrapper(localName = "setTelematicsUnitToVehicleResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.SetTelematicsUnitToVehicleResponse")
    @WebResult(name = "setTelematicsUnitToVehicleResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.WebResult setTelematicsUnitToVehicle(
        @WebParam(name = "CIF", targetNamespace = "http://tempuri.org/")
        java.lang.String cif,
        @WebParam(name = "telematicsUnitNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String telematicsUnitNumber,
        @WebParam(name = "numberPlate", targetNamespace = "http://tempuri.org/")
        java.lang.String numberPlate
    );

    @WebMethod(action = "http://tempuri.org/IWsJaltestTelematicsAPI/updateSettings")
    @Action(input = "http://tempuri.org/IWsJaltestTelematicsAPI/updateSettings", output = "http://tempuri.org/IWsJaltestTelematicsAPI/updateSettingsResponse")
    @RequestWrapper(localName = "updateSettings", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.UpdateSettings")
    @ResponseWrapper(localName = "updateSettingsResponse", targetNamespace = "http://tempuri.org/", className = "com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.tempuri.UpdateSettingsResponse")
    @WebResult(name = "updateSettingsResult", targetNamespace = "http://tempuri.org/")
    public com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.InfoELD updateSettings(
        @WebParam(name = "newSettings", targetNamespace = "http://tempuri.org/")
        com.opentach.server.remotevehicle.provider.jaltest.wsinvoker.telclield.ConductorELDDto newSettings
    );
}
